ClassicPress/ClassicPress

- src/wp-admin/about.php
This PR removes the Gutenberg section from the bottom of the About page:
> ![2018-09-04t21 41 20-05 00](https://user-images.githubusercontent.com/227022/45068045-4b981180-b08b-11e8-8789-03d50f912add.png)
I noticed this code while reviewing #23.
> Remove Gutenberg callout from About page

- src/wp-admin/about.php
- src/wp-admin/credits.php
- src/wp-admin/freedoms.php
- src/wp-includes/admin-bar.php
- src/wp-includes/css/admin-bar.css
- src/wp-includes/general-template.php
- src/wp-includes/images/classicpress-logo-dashicon-style.svg
- src/wp-includes/version.php
The intent of this PR is to get us to a place where we can show screenshots of our work in progress.  The PR does the following:
- Add a new `$cp_version` global variable.  There are lots of places in the code where `$wp_version` is used to compare and enable/disable various features, so it will be easiest to introduce our own version variable.
- Show the ClassicPress version instead of the WordPress version in the admin dashboard's About section, and begin updating the About page content accordingly.
- Replace the WP logo in the admin bar with an SVG of the ClassicPress logo.  This is a bit different than how it worked previously, since this logo in WP uses [an icon font](https://github.com/WordPress/dashicons).
Screenshots:
> Update about page, logo in admin bar

- .gitignore
- .travis.yml
- tests/phpunit/data/plugins/wordpress-importer/parsers.php
- tests/phpunit/data/plugins/wordpress-importer/readme.txt
- tests/phpunit/data/plugins/wordpress-importer/wordpress-importer.php
- tests/phpunit/tests/import/import.php
- tests/phpunit/tests/import/parser.php
- tests/phpunit/tests/import/postmeta.php
There are a good number of steps required to run the PHPUnit test suite locally.  This PR eliminates one of them (https://make.wordpress.org/core/handbook/contribute/git/#unit-tests):
> When downloading the repository from git, a few of the PHPUnit tests related to the importer plugin will fail because the `tests/phpunit/data/plugins/wordpress-importer` directory is not contained in the git repositories. Here’s how to fix that [...]
This PR will go ahead and fix this for anyone using this code, and it also eliminates some more references to WP.org.
> Add WordPress Importer plugin to unit tests

- .travis.yml
- src/wp-includes/version.php
See:
- https://vote.classicpress.net/posts/3/increase-the-minimum-php-version-to-5-6
- https://vote.classicpress.net/posts/6/minimum-php-version-should-be-7-0
- https://wordpress.org/about/stats/
- https://classicpress.slack.com/archives/CCQ01LKDX/p1536848528000100
This is an intermediate step to bumping the minimum PHP version to 7.x, which we will be looking at for v2.  I would love to go ahead and drop 5.6 now, but 38.3% of all WordPress sites are on it, which to me is way too many people to exclude.
The only immediate effect of this change is that Travis CI builds will now be significantly faster.
We _could_ go ahead and remove some compatibility code for PHP <= 5.5, but I don't really think it's necessary for v1.  Let's track that at #63.
To avoid any ill effects from this change, …
> Drop support for PHP 5.5 and lower

- src/wp-includes/widgets/class-wp-widget-meta.php
As per title, I guess we missed this during #34
> rename WP site name and link of Widget Meta

- src/wp-admin/setup-config.php
Update `wp_` to `cp_` (default database table prefix) and `wordpress` to `classicpress` (default database name) in the install procedure. Thanks @invisnet for pointing this out
> Change default database prefix and name during install

- src/wp-admin/includes/network.php
- src/wp-admin/maint/repair.php
- src/wp-admin/setup-config.php
- src/wp-includes/pluggable.php
- wp-config-sample.php
- wp-tests-config-sample.php
part of the renaming effort in issue #35
> replace SALTS API link and name

- renovate.json
https://renovatebot.com/ will be generating a lot of PRs for us (so far #88 #89 and #90).  This change should configure it to use a common prefix for all of its PR titles and commit messages.
> Add a common prefix to all Renovate PR titles

- src/wp-includes/update.php
There are few things to consider here.
1. Instead of disabling the auto updates I've changed the URL to point to the actual ClassicPress API to be able to use it in the future.
2. ~The actual ClassicPress API response is badly formatted~ Fixed!
~`offers` is an array of objects but ClassicPress is returned just an object, resulting in a lot of warnings~
3. The ClassicPress Version is `4.9.9-alpha-43554-src` we should start using `0.x.x` or something to be ready to the `1.0.0` release.
Closes #110.
There is no way to tests if an auto-update breaks a site see [43395](https://core.trac.wordpress.org/ticket/43395) 
But the  update flow is triggered in 3 points I run this functions manually.
- `_maybe_update_core` via an `admin_init` action
- `wp_version_check()` this is the function that call …
> Prepare the core auto-update system for the ClassicPress´ API 🚀

- Gruntfile.js
Also exclude a few other things which may get included from a working
development install.
Closes #74.
> Build: Remove Hello Dolly

- bin/compare-build-branch.sh
This PR adds a script to compare the contents of the `build/` folder (generated by `grunt build`) before and after the changes added by a branch.
This is intended to help with part of #113 for upgrades to our dependencies:
> No changes in the `build/` folder resulting from the upgrade, or all changes are harmless and non-breaking
In the future we can probably also use this to verify that other changes to the build are working as intended.
I'm not sure if this should be merged or not, but at least here it will be available for reference.
> Add a script to check for build changes

- bin/compare-build-branch.sh
With nvm, and the possibility for the node version to change in between builds, just ensuring that `js-beautify` is installed once isn't always enough.
> Compare build script: Install js-beautify after switching node versions

- src/wp-admin/includes/update.php
- All the instances of `get_bloginfo( 'version', 'display' )` were
changed for the `classicpress_version()` function
- Fix #137
- Fix #138
> Using the ClassicPress version function instead of WP version

- src/wp-admin/includes/update-core.php
Fixes #136.
Tested by running `grunt build`, zipping up the result, modifying the zip file URL and version number in the current version of the migration plugin, and attempting the migration.
Here is the result:
> Make migration and upgrades work

- Gruntfile.js
- package.json
- src/wp-includes/version.php
We've started using the convention `alpha0` for any builds before the first alpha, and `+dev` for development versions (ClassicPress installs from the source repository).  This PR updates the version string in the source accordingly and modifies the build process to either replace the `+dev` suffix or replace it with a nightly version string.
The inline documentation is related to ongoing discussion about versioning and can be improved as we refine our strategy there.
> Update version; start planning future versions

- src/wp-includes/functions.wp-scripts.php
- src/wp-includes/functions.wp-styles.php
- src/wp-includes/script-loader.php
- tests/phpunit/tests/dependencies/scripts.php
Closes #56 and addresses issues with cached WP stylesheets being loaded
after migrating to ClassicPress (note the missing logo in the top right, because its CSS rules were not loaded):
> Use ClassicPress version for asset cache busters

- src/wp-admin/setup-config.php
- src/wp-includes/class-wp-editor.php
- src/wp-includes/class-wp-locale.php
- src/wp-includes/default-constants.php
- src/wp-includes/general-template.php
- src/wp-includes/script-loader.php
- src/wp-includes/version.php
- tests/phpunit/includes/bootstrap.php
Closes #58.
Fixes some breakage introduced by the version string changes in #147 with installs directly from the source repository (note the blank space where the admin bar should be):
Introduces a more unified way to do the check for dev versions.  If we need something more sophisticated in the future then we can add another function, but I think we should keep it simple.
> Improve handling of development versions

- src/wp-includes/admin-bar.php
- src/wp-includes/css/admin-bar.css
Replace (W) icon in multisite sites list addresses issue #121 
open issue #121 
On live staging site, see screenshot
> Replace (W) icon in multisite sites list addresses issue #121

- src/wp-admin/about.php
- src/wp-admin/css/about.css
We're including the full ClassicPress version string in the dashboard, because the way WordPress does this is pretty confusing.
Since this string can be a good bit longer than the corresponding string in WP, which is never longer than 5 characters (e.g. `4.9.8`), we'll need to tweak the About screen a bit.
> Improve version display on wp-admin about screen

- src/wp-includes/version.php
Commits immediately after a release will have the `+dev` suffix without updating the base version string.
Reason: "we don't know at that point which version is going to be next, and when we branch for a hotfix later it'll look weird"
> Update version plan

- src/wp-includes/admin-bar.php
Update support URLs in admin bar logo pop-under. Changes made according to [this convo](https://classicpress.slack.com/archives/CCNEEH86P/p1540943310205800) and to address issue #195 .
Updated URLs for Documentation and Support, as well as related labels; re-pointed from WP properties to CP properties. Removed feedback URL. Updated comments.
CP users should be directed to CP channels for CP help.
Entirely on localhost w/ Alpha 1.0.0
None.
> Update admin-bar support URLs to point to CP properties

- src/wp-admin/update-core.php
- Pull URLs out into separate strings
- Link to new Updating ClassicPress documentation page
- Fixes #184
> Update "before updating" message

- src/wp-admin/includes/class-wp-automatic-updater.php
- src/wp-admin/includes/ms.php
- src/wp-admin/includes/upgrade.php
- src/wp-admin/maint/repair.php
- src/wp-admin/network/index.php
- src/wp-admin/network/site-new.php
- src/wp-admin/network/sites.php
- src/wp-admin/network/user-new.php
- src/wp-admin/network/users.php
For issue #194, #198. This PR corrects the default email of the example commenter installed with the system, and updates support URLs.
Changed email from wapuu@classicpress.example to social@classicpress.net. Updated source URLs to reflect current support channels.
Email address was invalid; support URLs invalid.
Locally. Manually updated database with new address to see that the new avatar worked correctly.
> Fix #194 and #198

- src/wp-includes/admin-bar.php
Added the missing alt tags:
* `alt="ClassicPress"` for the primary one
* `alt=""` for the multisite blogs list
> addresses #171 (Missing img alt attributes in admin menu)

- src/wp-includes/class-wp-customize-manager.php
Adjust upload site-con text Customizer, fix issue #219
See issue #219 (upload site-icon text in Customizer)
Text refers to ClassicPress mobile apps, which do not exist at this point
Fixes #219 
Local dev
> adjust upload site-icon text Customizer, fix issue #219

- src/wp-includes/css/buttons.css
Part of #210, alternative 2 of 2 (see #222 for gradient button background).
This changes the primary button style (colors) **across of all of wp-admin**.  Needs testing to make sure there are no core screens where this looks terrible.
Bonus: we are improving on WP's contrast ratios here.
> Update admin buttons: solid color background

- src/wp-admin/includes/schema.php
- tests/phpunit/data/export/small-export.xml
- tests/phpunit/data/export/test-serialized-postmeta-no-cdata.xml
- tests/phpunit/data/export/test-serialized-postmeta-with-cdata.xml
- tests/phpunit/data/export/test-utw-post-meta-import.xml
- tests/phpunit/data/export/valid-wxr-1.0.xml
- tests/phpunit/data/export/valid-wxr-1.1.xml
- tests/phpunit/tests/general/document-title.php
- tests/qunit/fixtures/wp-api-generated.js
Petitioned in https://petitions.classicpress.net/posts/97/update-the-default-just-another-tagline
But because not a major change and a nice way to differentiate ClassicPress from Wordpress, we have discussed it [on Slack](https://classicpress.slack.com/archives/CCQ01LKDX/p1541634907073100) and decided on the line in the title
Change "Just another ClassicPress site" to "Another great website powered by ClassicPress"
To stay with the original petition: to jazz it up a bit
> change tagline to "Another great website powered by ClassicPress"

- tests/phpunit/tests/media.php
When running the PHPUnit automated tests, `WP_TESTS_DOMAIN` is normally set to `example.org`, but it doesn't have to be.  This commit fixes a single failing test that appears when this value is set to a different domain in `wp-tests-config.php`.
> Fix the tests when `WP_TESTS_DOMAIN` is overridden

- tests/phpunit/tests/image/siteIcon.php
There are a couple of PHPUnit automated tests that ultimately call `getimagesize` through this code path:
https://github.com/ClassicPress/ClassicPress/blob/e18bef95/src/wp-admin/includes/class-wp-site-icon.php#L90
This call requires internet connectivity, because it's pointing to a URL at `example.org` by default.  Unit tests should not require internet connectivity.
Also, it actually takes 60 seconds to time out if you override the `WP_TESTS_DOMAIN` value in the `wp-tests-config.php` file (see #226).
As a workaround, this PR passes a local file path through to `getimagesize` instead.
The tests in question are `test_create_attachment_object` and `test_insert_cropped_attachment` in `tests/phpunit/tests/image/siteIcon.php`.
For more information about this timeout, see: …
> Prevent `getimagesize()` timeouts during tests

- tests/phpunit/includes/testcase-canonical.php
- tests/phpunit/tests/canonical.php
- tests/phpunit/tests/canonical/category.php
- tests/phpunit/tests/canonical/customRules.php
- tests/phpunit/tests/canonical/noRewrite.php
- tests/phpunit/tests/canonical/pageOnFront.php
There are some old tests for the `redirect_canonical` function that contain WP Trac ticket numbers in the test code.  These ticket numbers only show up when the tests fail, which has not happened in a long time because this is a stable part of the code.  Also, we can look back at the commit history if these references are ever needed, so I am ok with losing this information.
See also #145.
> Remove more references to WP Trac tickets in tests

- src/wp-admin/about.php
- src/wp-admin/credits.php
- src/wp-admin/css/about.css
- src/wp-admin/freedoms.php
- src/wp-admin/includes/misc.php
For **development installs** (running ClassicPress from this source repository), this PR adds a small marker next to the version number on the wp-admin About page that shows the current `git` commit and links it to GitHub:
The goal of the PR is to make it more clear exactly which version of ClassicPress you are running, since the version number in this repository looks like `1.0.0-alpha1+dev` which actually represents a pretty wide range of commits.
> Add more information about the current dev version

- src/wp-admin/includes/misc.php
- src/wp-includes/http.php
- #201: `wp_http_supports()`
- #231: `classicpress_dev_version_info()`
> Clean up '@ since' and '@ deprecated' from earlier PRs

- src/wp-includes/default-constants.php
- src/wp-settings.php
If you use XDEBUG breakpoint PHP code as a method of either debugging or learning, it is difficult when bare `if()`s are used, as WordPress core has so many of.  
Also, the current WordPress standard which ClassicPress has decided to follow says [braces are to be used even if not required](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style). 
Addition of braces on any `if()` statements found in those two files in the following form:
```
if ( expression ) 
statement;
```
Those were changed to be:
```
if ( expression ) {
statement;
}
```
No other changes were made.
It is harder to use XDEBUG with bare `if()`s because you can't breakpoint only for when the expression is true.
Loaded the site with WPLib Box.
No other testing really needed.
- [--] My …
> Add braces to bare if()s in default-constants.php and wp-settings.php.

- src/wp-admin/css/about.css
This PR updates the "logo badge" on the About screens in the dashboard to use the ClassicPress colors and gradient background.
While researching how to apply the gradient background, I found that the multiple-browser-compatibility CSS prefixes that we've been using elsewhere are no longer necessary:  https://codepen.io/thebabydino/full/pjxVWp
And a couple more resources specifically about declaring multiple sets of background properties on a single element, as we are doing here:
- https://stackoverflow.com/a/2547064/106302
- https://stackoverflow.com/a/11468866/106302
> Update ClassicPress logo background on About screens

- src/wp-admin/includes/update-core.php
Some selected parts of the code path of a ClassicPress upgrade:
https://github.com/ClassicPress/ClassicPress/blob/bf9c2057f0c212f0606d98576bd8126fe482942c/src/wp-admin/includes/update-core.php#L185
https://github.com/ClassicPress/ClassicPress/blob/bf9c2057f0c212f0606d98576bd8126fe482942c/src/wp-admin/includes/update-core.php#L216-L230
https://github.com/ClassicPress/ClassicPress/blob/bf9c2057f0c212f0606d98576bd8126fe482942c/src/wp-admin/includes/update-core.php#L520
When we are updating from ClassicPress to a newer ClassicPress version, the `wp-includes/version.php` file from the new build is loaded, but it's loaded inside the context of the `update_core()` function, so the global `$cp_version` variable is **not** modified until the next full page load.
This means `classicpress_version()` …
> Fix the new ClassicPress version message on upgrade

- src/wp-admin/includes/dashboard.php
Replaces links from the WordPress News to the ClassicPress Blog in the News widget on the Dashboard.
Changes number of fetching items from 1 to 5.
This is an early step of implementation #40. A small change to make news links consistent.
According to comment https://github.com/ClassicPress/ClassicPress/issues/40#issuecomment-441152556
Needs to clear the transient cache before testing.
Or alternatively, comment out a block of code:
https://github.com/ClassicPress/ClassicPress/blob/3d681412745ea3c51c934d39458b17182b450316/src/wp-admin/includes/dashboard.php#L985-L988
> Replace links from the WordPress News to the ClassicPress Blog

- src/wp-includes/general-template.php
- tests/phpunit/tests/xmlrpc/wp/getOptions.php
`get_bloginfo( 'version' )` is used all over the place, I noticed `get_the_generator()` was still showing 4.9.8 because it uses `get_bloginfo()` to get the version which in turn uses the `$wp_version` global.
> Update version for get_bloginfo() to use ClassicPress version.

- src/wp-includes/general-template.php
- tests/phpunit/tests/xmlrpc/wp/getOptions.php
Reverts ClassicPress/ClassicPress#253
Until we know how people rely on `get_bloginfo( 'version ')`, we need to update the specific uses of this function in core to use `classicpress_version()` instead.
Much like how we leave `$wp_version` intact (it still says `4.9.8`) we need to make sure `get_bloginfo( 'version' )` returns a version that is understandable by code looking for a WordPress version.  Otherwise this is a breaking change.
> Revert "Update version for get_bloginfo() to use ClassicPress version"

- src/wp-includes/load.php
Fixes issue #264
Explicitly define some constants to avoid PHP warnings, back ported fix from WordPress.
Resolves issues reported in tickets #264
Tested on WordPress installs
> Define constants to avoid PHP Warning

- README.md
The 'contributors' list in the readme is disingenuous and misleading. I'm going to assume good intentions here and hope that you haven't done it on purpose, but listing the WordPress core team (and many other easily recognisable faces from the WordPress community) as your contributors is hugely misleading and makes it seem like this is an 'official' fork of WordPress.
You are a legitimate fork - don't mar that legitimacy by appearing to use shady tactics to make your project seem more significant. While it's nominally true that all of those folks have contributed to ClassicPress by virtue of their WordPress contributions, it is very obviously disingenuous to publish them in a list of contributors here.
I'm sure you can find a proper way of listing contributors here, but for now removing …
> Remove contributors from readme

- src/wp-admin/includes/dashboard.php
- src/wp-includes/version.php
A small celebration of every release.
Once we get past 1.0.0 we'll drop this and only put the version number
(without alpha/beta/etc) in the `@ since` and `@ deprecated` tags.
> Update `@ since` tags to mention the beta version

- .gitignore
- src/wp-admin/includes/translation-install.php
This will change the endpoint that retrive translation packages https://github.com/ClassicPress/ClassicPress/issues/183
By running a first clean installation (that uses `translations_api` function defined in `src/wp-admin/includes/translation-install.php`).
Endpoint currently respond:
```json
{
"translations": [
{
"language": "it_IT",
"version": "1.0.0",
"package": "https://translate.classicpress.net/wp-content/translations/core/1.0.0/it_IT.zip",
"english_name": "Italian",
"native_name": "Italiano",
"iso": [
"it",
"ita",
null
],
"updated": "2018-12-15 16:00:32",
"strings": {
"continue": "Continue"
}
}
]
}
```
> Change endpoint for translation packages (temporary endpoint)

- src/wp-admin/includes/plugin-install.php
- src/wp-admin/includes/theme.php
- src/wp-admin/includes/translation-install.php
- src/wp-admin/includes/update.php
- src/wp-includes/update.php
Follow-up to #201 and #142.
Removes variables that were set to `$http_url` in WordPress, because
WordPress API calls support HTTP without SSL (ClassicPress API calls do
not).
Leaves the existing "request retry" logic in place, and adds comments to
make it easier to find places where requests are retried in the future.
> Remove `$http_url` cruft

- Gruntfile.js
- tests/phpunit/includes/testcase.php
- tests/phpunit/tests/rest-api/rest-schema-setup.php
Recent PRs like #302, #306, #307, #308 have a failing Travis build.  This is due to the `tests/qunit/fixtures/wp-api-generated.js` file changing when running `grunt precommit:verify`.  The differences are related to which meta keys are registered while running only the related PHPUnit tests, vs. running all PHPUnit tests:
```diff
diff --git a/tests/qunit/fixtures/wp-api-generated.js b/tests/qunit/fixtures/wp-api-generated.js
index a98ee997a6..e6272d2ce8 100644
--- a/tests/qunit/fixtures/wp-api-generated.js
+++ b/tests/qunit/fixtures/wp-api-generated.js
@@ -4278,11 +4278,7 @@ mockedApiResponse.CategoriesCollection = [
"taxonomy": "category",
"parent": 0,
"meta": {
-            "test_single": "",
-            "test_multi": [],
-            "meta_key": "",
-            "test_cat_single": "", …
```
> Fix problems with Travis build

- src/wp-includes/class-wp-network-query.php
- src/wp-includes/class-wp-site-query.php
See #263.
Merges https://core.trac.wordpress.org/changeset/43832 / https://github.com/WordPress/wordpress-develop/commit/894e8472389547757c2c0698cc6f2f6d4ac2015a to ClassicPress.
In PHP 7.3, the compact() function has been changed to issue an E_NOTICE level error if a passed string refers to an unset variable. In previous versions of PHP, this notice was silently skipped. The full RFC can be viewed here: https://wiki.php.net/rfc/compact
By initializing these variables, they can be compacted.
Props @desrosj.
> php7.3 compatibility: Fix compact throwing notices for multisite

- bin/compare-build-branch.sh
We have a script that shows the changes in the ClassicPress build due to the changes in a branch:  `bin/compare-build-branch.sh`
After #297 it is showing some noise in its diff.  See for example https://github.com/ClassicPress/ClassicPress/pull/306#issuecomment-449077815.
This PR fixes the issue by ignoring the `$default_version` variable when running this script.
> Avoid extra output when comparing build branches

- src/wp-admin/css/dashboard.css
Fixed an issue where the width of the petitions table wouldn't fit the widget box.
> Fix width issue with petitions widget

- src/wp-admin/includes/plugin-install.php
- src/wp-admin/includes/post.php
PR to test https://gist.github.com/Mte90/a8c06567855ecde19db245e64d96f739
---------
In PHP 7.3, the `compact()` function has been changed to issue an `E_NOTICE` level error if a passed string refers to an unset variable. In previous versions of PHP, this notice was silently skipped. This fixes a few more instances of unset variables in the WordPress admin.
The full RFC can be viewed here: https://wiki.php.net/rfc/compact.
See https://core.trac.wordpress.org/ticket/44416.
Fixes https://core.trac.wordpress.org/ticket/45483
----
Merges https://core.trac.wordpress.org/changeset/44185 / WordPress/wordpress-develop@7cda2404b5b86249d548b3215c1e5809d2b95541 to ClassicPress.
> WP-r44297: PHP 7.3 Compatibility: Fix compact related notices

- src/wp-admin/includes/post.php
…ierarchy in admin.
In [44185], a bug was introduced where hierarchical post types would not display in the correct default order (hierarchically).
This was caused by a `! isset()` check, which returned `false` after [44185], causing the correct default value to not be applied. This switches that conditional to use an `empty()` check, ignoring the new empty string assignment that was added to prevent a PHP notice when `compact()` is called.
Props davidbinda.
Fixes #45711.
git-svn-id: https://develop.svn.wordpress.org/trunk@44338 602fd350-edb4-49c9-b593-d223f7449a82
----
Merges https://core.trac.wordpress.org/changeset/44338 / WordPress/wordpress-develop@47584c7bc0 to ClassicPress.
> WP-r44338: Correctly show post type hierarchy in admin

- bin/backport-wp-commit.sh
When using the [backport script](https://forums.classicpress.net/t/backport-wp5-trac-tickets/110/8) to port WP commits to ClassicPress, the commit's original author information is only preserved when there is a merge conflict.
This is due to an implementation detail of the backport script.  When there are no conflicts, `git cherry-pick --no-commit` is used to allow editing the commit message.  This causes the original author information to be dropped.  When a commit has conflicting changes, we don't use `git cherry-pick --no-commit`, so the original author info is preserved.
You can see this in #359:
The first commit has the original author information because it included conflicting changes.  The last 2 commits should have the original author information preserved, but they didn't.  This …
> Backport script: Include original author in backported commits

- .travis.yml
- src/wp-includes/class-wp-comment-query.php
- src/wp-includes/class-wp-site-query.php
- src/wp-includes/class-wp-xmlrpc-server.php
- src/wp-includes/comment.php
- src/wp-includes/nav-menu.php
- src/wp-includes/post.php
- tests/phpunit/tests/dependencies/scripts.php
- tests/phpunit/tests/menu/nav-menu.php
This PR ports several WP commits to ClassicPress:
- WordPress/wordpress-develop@b4d7e7a "Build/Test Tools: Use 7.3 for PHP 7.3" (`.travis.yml` updates)
- WordPress/wordpress-develop@5a3ad21 "php7.3 compatibility: Fix compact throwing notices"
- WordPress/wordpress-develop@61ee6d9 "Nav Menus: Fix a PHP 7.3 error when switching themes"
A passing Travis build will mean that all PHP 7.3 issues in unit-tested code are now fixed.
Closes #263.
> Port all remaining WP changes for PHP 7.3 compatibility

- src/wp-admin/includes/class-wp-community-events.php
- src/wp-admin/includes/dashboard.php
- src/wp-admin/includes/import.php
- src/wp-admin/includes/plugin-install.php
- src/wp-admin/includes/theme.php
- src/wp-includes/class-http.php
- src/wp-includes/class-wp-xmlrpc-server.php
- src/wp-includes/comment.php
- src/wp-includes/http.php
- src/wp-includes/update.php
- tests/phpunit/tests/http/http.php
We've had several reports of users of premium plugins being unable to receive updates from custom update servers, services that connect from within WordPress not working properly, etc.
The cause we've identified so far is the modified `User-Agent` header that ClassicPress sends in `1.0.0-beta2` and older.
This PR changes the default `User-Agent` header to be recognizable to services that expect requests to come from WordPress.  This will fix the following reported issues:
- https://forums.classicpress.net/t/is-yoast-toast/685/53 (confirmed)
- https://forum.ait-pro.com/forums/topic/bps-pro-compatibility-with-classicpress/ (confirmed)
- https://forums.classicpress.net/t/genesis-update-doesnt-work/190/13 (potentially)
> Send a User-Agent header that looks more like WordPress

- src/wp-admin/about.php
- src/wp-admin/css/about.css
- src/wp-admin/css/common.css
- src/wp-admin/includes/dashboard.php
- src/wp-admin/index.php
cc @Mte90 
When you are using a language that is not English, this PR makes the following changes in the dashboard:
Also fixes an issue with a translated string reported by @ginsterbusch [here](https://forums.classicpress.net/t/how-to-localize-classicpress/459/11).
> Add call for translators

- src/wp-admin/css/common.css
- src/wp-admin/includes/admin-filters.php
- src/wp-admin/includes/class-wp-plugin-install-list-table.php
- src/wp-admin/includes/plugin-install.php
- src/wp-admin/js/plugin-install.js
- src/wp-admin/js/updates.js
This PR is related to the #117 
Several Tabs of the Plugin search were removed (beta, recommended, featured, favorites).
The auto search mechanism that was called when typing was disabled and it was added a button to perform the search only one click.
The Popular tab is now the dashboard page of the 'Add New' plugin page. 
It was also included Category navigation that will fill the input search with a predefined term and will execute a search using that term as a tag.
This new section was added using a hook so it can be removed easily.
Just part of the categories was filled with a corresponding tag so this content needs to be refined.
At the moment this is the list of the categories that are linked to a tag:
- Forms (form)
- eCommerce(ecommerce)
- SEO (seo)
- Newsletters (newsletter)
- …
> Remove WP-only features from the plugin installation section

- src/wp-includes/default-constants.php
Previously, a new install of ClassicPress would have the Twenty
Seventeen theme activated.  This will say "Powered by ClassicPress" in
the footer... until the site has a full theme update performed.  Then it
will change to "Powered by WordPress" because the default theme gets
updated too.
New installs of ClassicPress should continue to say "Powered by
ClassicPress" even after themes are updated, so this change sets the
default theme for new installations to ClassicPress TwentySeventeen, one
of the child themes added in #292.
See also #291.
> Update the default theme to ClassicPress TwentySeventeen

- src/wp-login.php
Now, after #265 the process of installing a new site is visually consistent with the ClassicPress brand.  When you get to the end, you see this:
Let's update the buttons on the login screen to match the "new" style of ClassicPress buttons:
This color change was previously made across all of wp-admin in #223, and reverted in #233.  This time it's a specific, targeted change to one screen so I feel more confident about it.
> Re-style the buttons on the login page(s)

- src/wp-admin/includes/update.php
- src/wp-admin/update-core.php
- src/wp-admin/upgrade.php
- Don't link to e.g. https://codex.wordpress.org/Version_1.0.0 for ClassicPress versions
- Another missing piece to enable automatic (background) upgrades
> A couple more updater fixes

- bin/check-release-files.pl
For future releases, this script will help us prevent the issues with `1.0.0-rc1` from reoccurring, where we had some [unexpected files packaged with the release](https://www.classicpress.net/blog/2019/02/24/classicpress-1-0-0-release-update/).
During the `1.0.0-rc1` release the output would have been the following:
```
✓ james@xps15 <CP>/build $ ../bin/check-release-files.pl
--- only in src/
+++ only in build/
+ wp-content/languages/es_ES.mo
+ wp-content/languages/es_ES.po
+ wp-content/mu-plugins/debug-logins.php
+ wp-content/mu-plugins/error-log-backtrace.php
+ wp-content/plugins/classic-editor/LICENSE.md
+ wp-content/plugins/classic-editor/classic-editor.php
+ wp-content/plugins/classic-editor/js/block-editor-plugin.js
+ wp-content/plugins/classic-editor/readme.txt
+ …
```
> Add a script to check the files in a release

- bin/backport-wp-commit.sh
Try (for example):
```
bin/backport-wp-commit.sh 44761
```
The backport script will fail to find this changeset before this PR.
> Enable backporting changes from the WP 5.1 branch

- src/wp-admin/css/themes.css
- src/wp-admin/includes/theme.php
- src/wp-admin/themes.php
- src/wp-includes/customize/class-wp-customize-theme-control.php
The blue notices are new:
Closes #299.  Other solutions are more complicated with lots of edge cases (even more edge cases).
Note, there are three places where this notice needs to be rendered:
- `/wp-admin/themes.php`, JavaScript disabled
- `/wp-admin/themes.php`, JavaScript enabled
- `/wp-admin/customize.php`, after clicking the Change button next to the active theme
Also, the new notice should only appear if both the child theme and the parent theme for a given year are present.
> Explain default themes better

- src/wp-admin/js/theme.js
- src/wp-admin/theme-install.php
Follow-up to #342.  Reported [on the forums](https://forums.classicpress.net/t/favorite-plugins-using-wordpress-org-account/834).
> Remove WP-only features from the theme installation section

- src/wp-includes/comment.php
- src/wp-includes/http.php
- src/wp-includes/update.php
- tests/phpunit/tests/http/http.php
Follow-up to https://github.com/ClassicPress/ClassicPress/pull/361.
Previously:
- `classicpress_user_agent() => "WordPress/4.9.9; https://www.classicpress.net/?wp_compatible=true&ver=1.0.0"`
- `classicpress_user_agent( false ) => "WordPress/4.9.9"`
With this PR:
- `classicpress_user_agent() => "WordPress/4.9.9; https://www.classicpress.net/?wp_compatible=true&ver=1.0.0"`
- `classicpress_user_agent( true ) => "WordPress/4.9.9; https://www.classicpress.net/?wp_compatible=true&ver=1.0.0&site=abcdef1234"`
> Update User-Agent header again

- src/wp-includes/http.php
> Make User-Agent identifier consistent regardless of trailing slashes

- src/wp-includes/version.php
WPCLI only fetches the first 2048 bytes of the version file with file_get_contents and so is returning invalid versions.
See https://forums.classicpress.net/t/wp-cli-compatibility/891/
This is where the parse instead of include was merged into wpcli https://github.com/wp-cli/wp-cli/pull/2459
```
wp core version --extra
WordPress version: 
Database revision: 
TinyMCE version:
Package language: en_US
```
Tested against latest develop branch
```pross@pross ~/public_html $ wp core version --extra
WordPress version: 4.9.9
Database revision: 38590
TinyMCE version:   4.800 (4800-20180716)
Package language:  en_US
```
> Move variables back to top of version.php file to fix WPCLI

- Gruntfile.js
Fix #445
The url is in 404 because the project changed the way how to manage assets
Locally the grunt task is not getting any issue anymore. Require further testing to see if the there are other errors.
> fix #445 - Update tweemoji url in gruntfile

- .browserslistrc
- Gruntfile.js
- package-lock.json
- package.json
- webpack.config.dev.js
- webpack.config.prod.js
Just some updates to the build scripts:
1. Convert to ES6
2. Replace `grunt-postcss` with `@lodder/grunt-postcss` (see note below)
3. Move browser list to `.browserslistrc` in conjunction with the PostCSS update
Point 2 is not at all supposed to be any form of personal endorsement. I forked the original `grunt-postcss` package and took on maintanence.
> Update build scripts

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/contributing.md
- README.md
Change in docs to make guided contributions in PRs 
Reference: https://github.com/ClassicPress/ClassicPress/issues/423
> Add contribution guidelines

- tests/phpunit/tests/http/base.php
The size of https://www.classicpress.net/wp-content/uploads/2019/02/celebrating-six-months-150x150.jpg has changed with the move of our site to a new server. This file is used in the HTTP tests during our build, so we need to update the size there.
A full solution to this issue is outlined in #25 but this will do for now.
> Fix the HTTP tests

- src/wp-content/plugins/hello.php
- tests/phpunit/tests/ajax/UpdatePlugin.php
This PR avoids an "update available" notice for the Hello Dolly plugin in ClassicPress sites **installed from the source repository** - our release builds do not contain Hello Dolly so "regular" users will never see this.
> Update Hello Dolly version for dev environments

- tests/phpunit/includes/factory/class-wp-unittest-factory-for-attachment.php
- tests/phpunit/includes/testcase.php
- tests/phpunit/tests/ajax/MediaEdit.php
- tests/phpunit/tests/media.php
When running the following PHPUnit tests without the `imagick` or `gd` extensions installed, or with incorrect file permissions in the `wp-content/uploads` directory, running the automated tests will generate some cryptic errors:
```
phpunit --group ajax
phpunit --filter Tests_Media
```
Example error messages for missing image extensions:
```
1) Tests_Media::test_wp_calculate_image_srcset
Undefined index: sizes
1) Tests_Ajax_MediaEdit::testCropImageThumbnail
attachment should have size data
Failed asserting that an array has the key 'sizes'.
```
And for incorrect filesystem permissions:
```
1) Tests_Ajax_Attachments::test_wp_ajax_send_attachment_to_editor_should_return_an_image
Undefined index: file
1) Tests_Media::test_wp_get_attachment_image_defaults
Failed asserting that two strings …
```
> Improve error handling for media and AJAX tests

- src/wp-includes/script-loader.php
Fixes #476 
This updates the jQuery version after applying the latest security fix from WP. The security fix has already been applied in ClassicPress 1.0.1. See #476 for more details.
Tested and integrated upstream
N/A
Simple update to jquery version numbers to enable browsers to download fixed versions sooner than current cache expiry.
> Update jQuery version after security patch

- wp-config-sample.php
Changed the second link in wp-config-sample.php to https://wordpress.org/support/article/debugging-in-wordpress/
After making a PR for https://github.com/ClassicPress/ClassicPress/pull/488 I decided to look at the other links in the root files of CP and found another one. Once again in wp-config-sample.php:
https://codex.wordpress.org/Debugging_in_WordPress
Tested quickly. Low chance of conflict elsewhere.
Old destination:
New destination:
- Bug fix
> Updating wp-config-sample.php's second link.

- Gruntfile.js
This helps track down the error more easily if someone is trying to run `grunt precommit` without `svn` installed.
See also #447 for another future improvement here.
```
Running "replace:emojiRegex" (replace) task
Fetching list of Twemoji files...
Fatal error: Unable to fetch Twemoji file list
```
```
Running "replace:emojiRegex" (replace) task
Fetching list of Twemoji files...
Command FAILED, try running it manually:
svn ls https://github.com/twitter/twemoji/branches/gh-pages/2/svg
Fatal error: Unable to fetch Twemoji file list
```
> Show a bit more info when listing Twemoji files fails

- src/wp-admin/css/customize-controls.css
- src/wp-admin/css/themes.css
- src/wp-admin/themes.php
- src/wp-includes/customize/class-wp-customize-theme-control.php
1. Wrapped notices with a common "div.notices". Notices now have responsive height and no top margin. External positioning is provided by a wrapper. (According to discussion: https://github.com/ClassicPress/ClassicPress/issues/414#issuecomment-505707842)
2. Wrapped secondary parts of related long messages to hide them on mobile (native breakpoint is 1120px).
3. Added __() to some strings that had no internalization. 
Issue, help wanted: https://github.com/ClassicPress/ClassicPress/issues/414
Proposal: https://github.com/ClassicPress/ClassicPress/issues/414#issuecomment-506892952
Visually tested changes in Chrome and Firefox. First at full witdh then decreasing viewport to activate breakpoint. Tested in English and Russian locales + adding hypothetical additional length
Desktop, FF: …
> Fixed theme update notices (overlapping, fixed height and excessive length)

- package-lock.json
- package.json
Adds classes to the &lt;h2&gt; tags on the profile editing page so they can be more carefully targeted with CSS selectors. Fixes #440.
Updated several h2 tags with unique classes.
The current h2 tags lack classes which make them difficult to select with CSS unless they are selected wholesale. This is not ideal when you're only trying to remove a section or two. Using nth-child selectors can work in some cases, but, that method quickly degrades if a plugin or theme adds custom sections and skews the element count.
Inspecting the source; visually in a browser.
> Add classes to H2 tags in user-edit.php

- src/wp-admin/about.php
This PR attempts to make the "changelog" section of the About page easier to read.
> Improve changelog version headings on About page

- src/wp-admin/includes/plugin-install.php
Add rel="noopener noreferrer" to plugins links. See attached screenshot.
This page a couple of JavaScript files running which leaves the website owner vulnerable. It is a common link click area.
When you open another page using target="_blank", the other page may run on the same process as your page, unless Site Isolation is enabled. If the other page is running a lot of JavaScript, your page's performance may also suffer. 
Ref: https://developers.google.com/web/tools/lighthouse/audits/noopener
> Add rel="noopener noreferrer" to plugins screen links

- bin/backport-wp-commit.sh
Case-insensitive matching for git remotes
This will allow the script to work if you have referenced ClassicPress
in all lower-case in the `git remote` definition, for example:
```
$ git remote -v
upstream  https://github.com/classicpress/classicpress (fetch)
upstream  https://github.com/classicpress/classicpress (push)
```
> Minor improvement to backport script

- src/wp-includes/pluggable.php
WP-r47086: Mail: Remove angle brackets from password reset URL in emails sent by `retrieve_password()` and `wp_new_user_notification()`.
The brackets were originally added in https://core.trac.wordpress.org/changeset/16285 per W3C recommendation in https://www.w3.org/Addressing/URL/5.1_Wrappers.html to avoid wrapping the URL across multiple lines in plain text in older email clients.
This doesn't seem like a common issue in modern email clients, and the current implementation causes more issues than it solves. Since the URL is on a line by itself, it should not require any delimiters.
The URL in recovery mode email introduced in https://core.trac.wordpress.org/changeset/44973 doesn't have angle brackets, so it's time to retire them in password reset email too if they're not used …
> Remove angle brackets from password reset URL in emails

- bin/backport-wp-commit.sh
This PR seeks to improve the output when a WP commit is backported to ClassicPress and the resulting commit message is copied into GitHub:
This is the default behavior when submitting a PR.  The new output should look like this:
---
WP:Props donmhico, jonoaldersonwp.
Fixes https://core.trac.wordpress.org/ticket/43590.
Conflicts:
- src/wp-includes/functions.php
- src/wp-includes/general-template.php
---
Merges https://core.trac.wordpress.org/changeset/45928 / WordPress/wordpress-develop@122cb2864b to ClassicPress.
> Improve backport script commit messages

- renovate.json
This library has had major issues in the past, that went unaddressed for a while. For example: https://github.com/mishoo/UglifyJS2/compare/v3.4.8...v3.5.3 and https://github.com/mishoo/UglifyJS2/issues/3245.
This PR will stop @renovate-bot from sending us new PRs for `uglify-js`, like #132, #402, #409, and #507.
> Ignore new versions of uglify-js

- .github/CONTRIBUTING.md
- bin/backport-wp-commit.sh
As previously discussed on Slack, this PR updates the backport script and its documentation to commit files that have merge conflicts. The idea of this change is to make it easier for reviewers to see how a conflict was resolved, and allow PR submitters to leave conflict resolution to the maintainers if they're not sure how to do it.
This change will also prevent the issue we've seen previously where commit messages edited by the backport script were lost - this happened when a user didn't use `git cherry-pick --continue` after resolving conflicts, which was easy to miss.
> Update backport script to preserve merge conflicts

- src/wp-includes/css/admin-bar.css
When running ClassicPress with the Twenty Twenty theme from WordPress, the pop-out menu from the ClassicPress logo in the admin bar is positioned incorrectly:
This happens because Twenty Twenty contains the following CSS rule:
`img { display: block }`
To fix the issue we set the display of these images to `inline` in the admin bar CSS:
A similar issue exists in the sites menu for multisite installations, and the fix is the same.
> Fix the admin bar logo position with the Twenty Twenty theme

- src/license.txt
- tests/phpunit/includes/testcase.php
- tests/phpunit/tests/basic.php
- tests/phpunit/tests/external-http/basic.php
The following 2 automated tests are not running currently:
https://github.com/ClassicPress/ClassicPress/blob/6a77df7e6cef814e6f15a63a90997ae78d800c58/tests/phpunit/tests/basic.php#L10-L24
https://github.com/ClassicPress/ClassicPress/blob/6a77df7e6cef814e6f15a63a90997ae78d800c58/tests/phpunit/tests/external-http/basic.php#L7-L39
Since we definitely want to know when one of these tests is failing, let's always run them on all branches.
> Always run 'skipOnAutomatedBranches' tests

- src/wp-includes/version.php
This PR updates the `classicpress_version_short()` function that is used internally to print or log the version number in a couple of places.
Previously, build metadata like `1.1.1+dev` or `1.1.1+migration.20191018` would be included here.
After this PR, this metadata will be stripped and the function will behave as expected, returning e.g. just `1.1.1`.
> Strip more build metadata from classicpress_version_short()

- tools/i18n/makepot.php
This PR gets our .pot (translation file) script generator ready to feed classicpress.crowdin.com. In particular:
- Change from `php tools/i18n/makepot.php generic` to `php tools/i18n/makepot.php cp-core`
- Remove frequently-changing information such as date from the .pot header (this metadata will be managed using `git` instead)
- Update URLs in .pot header
- Set the version in the .pot header based on the version string from `git describe`
- Remove some dead code
It's easier to review this diff ignoring whitespace since some lines were reformatted: https://github.com/ClassicPress/ClassicPress/pull/547/files?w=1
> Update the .pot generator script for Crowdin

- src/wp-includes/pluggable.php
- tests/phpunit/tests/mail.php
Fixes Issue #495 
Backport of 3 upstream change sets
https://core.trac.wordpress.org/changeset/46115
https://core.trac.wordpress.org/changeset/46116
https://core.trac.wordpress.org/changeset/46118
Fixes issue described in Issue #495
Unit tests are part of patch
- Bug fix
> Guard against duplicate MIME-Version header in emails

- .travis.yml
Travis mentions this config key once in their [notifications documentation page](https://docs.travis-ci.com/user/notifications), but their [config validator](https://travis-ci.com/ClassicPress/ClassicPress/builds/149741243/config) doesn't like it:
> Remove invalid Travis config key: 'on_start'

- src/wp-includes/wp-db.php
Starting with MySQL 5.7.5, the `ANSI` mode implies `ONLY_FULL_GROUP_BY`, which is already listed in `wpdb` as incompatible per https://core.trac.wordpress.org/changeset/27072.
When `ANSI` is enabled on MySQL 5.7.5+, `ONLY_FULL_GROUP_BY` remains enabled even after being "unset" by `wpdb::set_sql_mode()`.
To prevent this, the `ANSI` mode should also be listed as incompatible. It is not enabled on default MySQL installations.
WP:Props jnylen0.
Fixes https://core.trac.wordpress.org/ticket/48377.
Conflicts:
- src/wp-includes/wp-db.php
---
Merges https://core.trac.wordpress.org/changeset/47171 / WordPress/wordpress-develop@b26b0cc to ClassicPress.
>  WP-r47171: Database: Add `ANSI` to the list of incompatible SQL modes

- src/wp-admin/about.php
- src/wp-admin/credits.php
- src/wp-admin/freedoms.php
Since we've been around for a year now, this PR changes the "Introducing ClassicPress" heading on the About page to "About ClassicPress", and adds a link to the main ClassicPress website.
> Update first section of About page

- src/wp-content/themes/twentyfifteen/style.css
- src/wp-content/themes/twentyseventeen/style.css
- src/wp-content/themes/twentysixteen/style.css
Fixes #529. Alternative approach to #545.
>When you install ClassicPress from scratch you immediately get prompted to upgrade the base version of our default themes (Twenty Fifteen through Seventeen from WP). This is worth fixing.
The main reason we don't just ship the latest version of these themes is that they include a lot of Gutenberg files we don't need (see #326), and these will be going away entirely in v2.
This PR fixes this issue in the easiest and simplest way possible: bumping the version numbers of these base themes to something beyond what the WP directory has.
This way, users can still upgrade these themes and keep them up to date if they really want to - they just have to edit the version number back to what it used to be. Other approaches that involve filtering the upgrade …
> Prevent update notices from Twenty * default themes

- bin/backport-wp-commit.sh
This PR makes several improvements to the [WP backport script](https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md#backporting-changes-from-wordpress).
These improvements will be used to help backport the WP 4.9.15 changes from https://github.com/WordPress/wordpress-develop/commit/aa08e63c74de39fcb3f6dfd8d03321739c2ab3f1.
Self-explanatory. See also https://github.com/ClassicPress/ClassicPress-backports/commit/e8de096b3f1d2b5947c4167c3a036894d5aefd8c
Before:
```
Merges [47948-47951] to the 4.9  branch.
```
After:
```
Merges https://core.trac.wordpress.org/log/?revs=47948-47951 to the 4.9  branch.
```
Before:
```
=======
WARNING: Conflict detected!
Fix and commit the files that contain <<<< or >>>> conflict markers:
- Editor: Prevent HTML decoding on by setting …
```
> Backport script: Several updates

- src/wp-admin/includes/class-wp-filesystem-direct.php
- src/wp-admin/includes/class-wp-filesystem-ssh2.php
WP-r48031: Filesystem API: Avoid a PHP notice in `WP_Filesystem_Direct::owner()` and `::group()` methods and their `WP_Filesystem_SSH2` counterparts.
Although not officially documented in the PHP manual, `posix_getpwuid()` and `posix_getgrgid()` can return `false` in some circumstances.
WP:Props logig.
Fixes https://core.trac.wordpress.org/ticket/50373.
Conflicts:
- src/wp-admin/includes/class-wp-filesystem-direct.php
- src/wp-admin/includes/class-wp-filesystem-ssh2.php
---
Merges https://core.trac.wordpress.org/changeset/48031 / WordPress/wordpress-develop@d32ec3352b to ClassicPress.
> WP-r48031: Avoid a PHP notice in several `WP_Filesystem` methods

- tests/phpunit/includes/bootstrap.php
- wp-tests-config-sample.php
When you run `phpunit` (or a command that runs `phpunit`) and you haven't set up the automated tests yet, you get a message like the following:
```
$ grunt precommit
[...]
Running "phpunit:wp-api-client-fixtures" (phpunit) task
ERROR: wp-tests-config.php is missing! Please use wp-tests-config-sample.php to create a config file.
```
This PR changes the error message to be a bit clearer:
```
ERROR: wp-tests-config.php is missing! Please see wp-tests-config-sample.php for setup instructions.
```
And it also adds a link from `wp-tests-config-sample.php` to our phpunit testing documentation: https://github.com/ClassicPress/ClassicPress/tree/develop/tests/phpunit
> Improve messages that point to the phpunit tests documentation

- Gruntfile.js
- package-lock.json
- package.json
This PR attempts to cut down on the absurd number of npm dependencies required to test and build ClassicPress. Three unneeded/unused dependencies were removed. There is still much more to be done here, for example:
- change color schemes to use CSS vars or some other technique that is lighter than node-sass
- use rollup instead of webpack to build the media JS
- find a way to run the qunit tests without puppeteer (this downloads all of chromium, which accounts for the majority of the `node_modules` folder size)
However this is about as far as we can go with quick, straightforward changes that definitely won't break anything.
The following table lists each **top-level dependency** (i.e. directly declared in `package.json`) and the **number of lines** in the `npm ls` output associated with …
> Prune build dependencies (1 of ?)

- src/wp-admin/options-general.php
- src/wp-includes/script-loader.php
This is consistent with the way other built-in script files are declared and managed.
> Add "Custom Login Image" JS to the script loader

- src/wp-admin/freedoms.php
This PR updates the privacy policy wording to be a little more clear, and to link to the page that is going to contain the full policy.
The previous link was pointing to iubenda.com which is no longer active and was not very useful anyway. The new link is not live yet, but it is using our redirect server at link.classicpress.net / https://github.com/ClassicPress/subdomain-link so that we can put up a page wherever we want without having to change the core code again.
> Update privacy policy

- bin/check-release-files.pl
#607 added some new files in `src/` that should not be present in `build/`. This PR updates a script for the release process accordingly.
> Update list of files in release

- Gruntfile.js
- bin/backport-wp-commit.sh
Issue reported by @bahiirwa:
```
$ bin/backport-wp-commit.sh -c 42832
Found git remote 'wp' for WordPress/wordpress-develop
Found git remote 'origin' for ClassicPress/ClassicPress
Updating repositories from GitHub: WordPress...
Updating repositories from GitHub: ClassicPress...
Searching for r42832 in WP git: wp/4.9
Searching for r42832 in WP git: wp/5.0
Searching for r42832 in WP git: wp/5.1
Searching for r42832 in WP git: wp/5.2
Searching for r42832 in WP git: wp/5.3
Searching for r42832 in WP git: wp/5.4
Searching for r42832 in WP git: wp/master
Found commit: 5f56921131 on wp/master branch
Backporting commit using git cherry-pick
Modifying commit message
git status before:
UU src/wp-admin/css/dashboard.css
UU src/wp-admin/includes/dashboard.php
UU src/wp-includes/capabilities.php
UU …
```
> Fix backport script on OS X

- src/wp-includes/general-template.php
This is a backport from https://core.trac.wordpress.org/changeset/45042/. 
Merges https://core.trac.wordpress.org/changeset/45042 / WordPress/wordpress-develop@01882f477b to ClassicPress.
Closes #646
**Description from WP:**
> Bundled Theme: trigger a new `wp_body_open` action immediately after the opening `body` tag.
> 
> - Enables inserting (asynchronous) JavaScript right after the opening `body` tag.
> - Add a `wp_body_open` helper function that triggers the `wp_body_open` action.
> - Call `wp_body_open` in core themes immediately after the opening `body` tag. 
---
1. One file changed: `src/wp-includes/general-template.php`
2. Other files were intentionally omitted from this PR. Such files include:
- src/wp-content/themes/twentyfifteen/header.php
- …
> WP-r45042: Adds support for the `wp_body_open()` hook introduced in WP5.2.0.

- .github/workflows/coding-standards.yml
- .github/workflows/javascript-tests.yml
- .github/workflows/php-compatibility.yml
- .github/workflows/phpunit-tests.yml
Adds the `workflow_dispatch` event to each GitHub Action `yml` file.
This allows actions to be triggered manually as detailed here:
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
Once integrated, a ‘Run workflow’ button will appear on the Actions tab.
> Add workflow_dispatch to GitHub Actions

- README.md
Replaces the Travis badge with the Github Actions Workflow badges, based on the `develop` branch.
> Add Github Action Workflow Badges

- .github/workflows/phpunit-tests.yml
Ubuntu 20.04 now installs MySQL 8 as default which is causing the tests to fail. As a workaround while this can be fully fixed, drop back to `ubuntu-18.04` which includes MySQL 5.7.
> Lock Ubuntu version for PHPUnit tests

- src/wp-includes/js/wplink.js
Avoids change the selected link when using the Shift + Up/Down arrow keys
to select text in the form fields.
WP:Props afercia.
Merges https://core.trac.wordpress.org/changeset/42807 to the 5.0 branch.
Fixes https://core.trac.wordpress.org/ticket/43253.
---
Merges https://core.trac.wordpress.org/changeset/44405 / WordPress/wordpress-develop@3f6df95e64 to ClassicPress.
> WP-r44405: Accessibility: Insert Link modal: Improve keyboard interaction.

- Gruntfile.js
- package-lock.json
This makes sure that we won't commit any package-lock.json changes which suffer from https://github.com/npm/cli/issues/1685, which doesn't seem to break anything but also isn't correct and adds more useless changes to the already noisy package-lock.json file.
Tested locally. I will also push another commit here that will fail this check, and so GitHub Actions should fail the build for that commit.
> Add check for broken package-lock.json file

- .github/workflows/welcome-new-contributors.yml
Closes #730 
I think, it will be of great value to add an automation to welcome new contributors like we do on the forums.
If this is accepted, we would need to have a `GITHUB_TOKEN` to run the bot.
It auto responds to the PR and also sends an email to the new contributor welcoming them like the image below.
> Welcome new Contributors

- src/wp-admin/includes/class-wp-comments-list-table.php
- src/wp-admin/includes/class-wp-posts-list-table.php
- src/wp-admin/includes/class-wp-terms-list-table.php
- src/wp-admin/js/edit-comments.js
- src/wp-admin/js/inline-edit-post.js
- src/wp-admin/js/inline-edit-tax.js
This adds these 4 related changesets in one batch:
- https://core.trac.wordpress.org/changeset/42725
- https://core.trac.wordpress.org/changeset/42727
- https://core.trac.wordpress.org/changeset/42767
- https://core.trac.wordpress.org/changeset/45553
This improves the semantics for the inline actions in the Posts table. Conceptually, these are buttons, and should also be exposed to screen readers as such, not as links (as is the case now). More context can be found in this ticket: https://core.trac.wordpress.org/ticket/38677
It's been on WP since version 5.1, and the regression was fixed in 5.3, which I rolled up into the above set of changes.
N/A
Screenshots not available, to sighted people this should not make a difference. For screen reader users, the Edit, Quick Edit etc. elements …
> Semantic elements for non-link links: class-wp-posts-list-table.php

- src/wp-admin/includes/misc.php
- src/wp-includes/general-template.php
Currently, when an SVG is used as a menu icon, the color is inconsistent with the other, default dashicons and the contrast ratio does not meet the minimum requirement for accessibility. This updates the base color for the default `fresh` color scheme to ensure consistency and proper contrast.
Props swift, dschalk.
Fixes [44209](https://core.trac.wordpress.org/ticket/44209).
> Merge/wp r44353: Administration: Update default fallback color for SVG icons.

- src/wp-admin/css/deprecated-media.css
https://core.trac.wordpress.org/changeset/43019 improved the table pagination link styling, but introduced a regression in the old media dialog.
Merges https://core.trac.wordpress.org/changeset/44747 to the 5.1 branch.
WP:Props afercia, joneiseman.
Fixes https://core.trac.wordpress.org/ticket/41858.
---
Merges https://core.trac.wordpress.org/changeset/44750 / WordPress/wordpress-develop@67384779e5 to ClassicPress.
> WP-r44750: Accessibility: Fix a regression in the old media modal pagtion links.

- src/wp-includes/media-template.php
Label elements should only be used for labelable elements.
- `Uploaded By` and `Uploaded To` aren't form controls and shouldn't be associated with labels
- changes the labels for media source, alternate sources, poster image, and tracks to solve a layout issue and explicitly associate the labels to their form fields (previously, the labels were wrapping also the Remove buttons)
Merges https://core.trac.wordpress.org/changeset/42444 to the 5.0 branch.
WP:Props Presskopp, afercia.
Fixes https://core.trac.wordpress.org/ticket/38759, https://core.trac.wordpress.org/ticket/40468.
---
Merges https://core.trac.wordpress.org/changeset/43829 / WordPress/wordpress-develop@9cd32b93da to ClassicPress.
> WP-r43829: Accessibility: Media: Improve the usage of a few label elements in the media templates.

- README.md
- src/composer.json
- src/readme.html
- src/wp-admin/about.php
- src/wp-admin/credits.php
- src/wp-admin/freedoms.php
Closes #653
Chaging the tagline and byline from
```
ClassicPress
A business-focused CMS
Powerful. Versatile. Predictable.
```
to
```
ClassicPress
The CMS for Creators
Stable. Secure. Instantly Familiar.
```
No tests to write as these are changes to texts. 
Clarity can be made on `tests/phpunit/data/admin/features.json` file. Do we need to rephrase the wording? Many instances of this appear like below.
- Branding texts
> Add new tagline - The CMS for Creators. Stable. Secure. Instantly Familiar.

- tests/phpunit/tests/ajax/Autosave.php
This is a backport for changes 51450 and it fixes #752
Upstream backport, bug confirmed on develop and fox confirmed in PR
Unit tests and manual `var_dump()`ing of test content to command line.
N/A
- Bug fix
> Fix for Ajax Autosave Unit Tests

- src/wp-admin/includes/class-core-upgrader.php
- src/wp-admin/includes/update-core.php
- src/wp-admin/includes/update.php
Fixes #679 (an issue where the incorrect checksums were being used when upgrading ClassicPress, leading to some files not being upgraded correctly). Supersedes #681. See those links for more information.
> Use the correct checksums when updating

- bin/backport-wp-commit.sh
The current backport script works very well in the majority of cases however upstream some javascript files are located in a folder called `_enqueues` and they are built and moved into the correct location from there. This causes issue in back porting and currently any changes in these file are conflicts and must be manually back ported.
We can try to enhance the script to automatically located renames files and do the backporting for us and then report that this files were conflicting still bu perhaps a little differently than major code conflicts.
This PR aims to:
- Add --find-renames to cherry-pick command to enable backporting of file changes in different locations
- Update `perl` conflict reporting to show issues with these backports a little differently
I have veen testing by back …
> Enhance backport script

- src/wp-admin/includes/class-wp-posts-list-table.php
- src/wp-admin/includes/screen.php
This is a PR for the petition [Show Post/Page ID](https://forums.classicpress.net/t/show-post-page-id/2950/1).
It works fine. By default the ID column is hidden and can be enabled via screen options.
> PR to show posts and pages id

- src/wp-includes/option.php
Options, Meta APIs: Avoid a race condition causing the first of two subsequent requests updating different options at the same time to lose changes.
Every time an autoloaded option is updated or deleted, the alloptions cache is similarly updated. Due to the race condition, on any autoloaded option being updated, every other autoloaded option had its value set to the value at load time, causing a mismatch between the data in the persistent cache and the database.
This change introduces a $force_cache parameter for wp_load_alloptions() to force an update of the local alloptions cache from the persistent cache when an option is added, updated, or deleted, to minimize the chance of affecting other options.
Props fabifott, rmccue, tollmanz, johnjamesjacoby, spacedmonkey, dd32, jipmoors, …
> Minimize a race condition when using an object cache

- src/wp-admin/menu.php
- src/wp-admin/plugin-install.php
- src/wp-admin/plugins.php
This PR gives the option to go straight to a simple upload plugin screen without having to first load the WP plugin repo. There are 2 links - one as a sub menu item in the main menu, and one button at the top of the plugins screen.
These links both open this screen:
There are also some edits to the help screen to explain the new feature (and a few minor fixes for some phrases that were incorrectly swapped out when WP was changed to CP).
ClassicPress users are increasingly uploading plugins manually. When doing this you have to load the whole WP plugin repo page (which takes 4-5 seconds and shows many plugins as incompatible), then do another step to get to the upload panel. This is slow and pointless when you are just wanting to upload a plugin. 
Further discussion here: …
> Add two direct plugin upload links to admin to bypass loading the WP plugin repo

- src/wp-includes/class-wp-comment-query.php
- src/wp-includes/comment.php
Pr fixes the PHP 8.0 compatibility issues and closes #713 (Issue is detailed)
PR constains Merge conflicts and Backport changesets 
as [#comment:2](https://core.trac.wordpress.org/ticket/51957#comment:2) suggests.
After the patch, my admin area has not issue as in screenshot.
Yet pre-patch, we had
> Fix get comment 8 0

- src/wp-admin/includes/template.php
- tests/phpunit/tests/admin/includesTemplate.php
See Issue #777 and upstream ticket https://core.trac.wordpress.org/ticket/50019
Since PHP 7.4 the `remove_meta_box()` function can trigger PHP warnings 
This is a bug fix correcting an issue facing some plugins that are in-use on ClassicPress.
This is an upstream backport and also contains an additional unit test with the PR
N/A
- Bug fix
> remove_meta_box triggers warning in PHP 7.4

- src/wp-admin/css/widgets.css
This is a potential fix for #637 
Currently there is a toggle switch that is hidden from users unless hovered, focussed or if the Active Widget section is already collapsed.
Addresses an open issue and improves usability of the admin by by revealing a hidden toggle feature.
Manual testing on a local install. Not that on page load a small 'up' arrow is now visible above the word 'widget' above the right hand column of available widgets.
- New feature
> CSS amended for Widgets page

- bin/backport-wp-commit.sh
Upstream main development branch name has been changed from `master` to `trunk`, this updates our backporting script.
Unchanged the backport script cannot find changeset to backport
We need to search in `trunk` for changes, ability to search `branches` already exists and is unchanged, if we `leaf` this unfixed our backport script is useless.
Update applied locally and several backports have been successfully created in the last half hour with this change locally in place.
<!--
N/A
- Bug fix
> Update main branch name for upstream searching

- bin/backport-wp-commit.sh
Separate conflicting and absent files into 2 lists in backport script…reporting
The `backport-wp-commit.sh` has been evolving and improving. This is a further minor improvement.
A recent minor improvement was committed that lists non-existent files in red. As per the discussion on [slack](https://classicpress.slack.com/archives/CCCF22HG8/p1634829680014400) it was proposed listing the conflicting files and non-existent files separately would be an enhancement.
Local testing in branch with:
`bin/backport-wp-commit.sh -c -v 49539`
- New feature / enhancement
> Separate conflicting and absent files into 2 lists

- src/wp-includes/user.php
- tests/phpunit/tests/user/wpDropdownUsers.php
Add a `multiple` and a `value_field` argument to the $args array, so to allow the User Dropdown to be a multiple select, and to control the select option `value` attribute.
This change will allow a developer to instantiate the `wp_dropdown_users` function as a Multiple Select Dropdown instead of just as as single select.
It also allows to control the `value` value of the `option` in the select dropdown, which by default is the User ID, and that is not only limited, but most of the times, undesired.
Example usage 
`wp_dropdown_users( array( 'value_field' => 'user_login', 'multiple' => 'multiple' ) );`
See also https://forums.classicpress.net/t/update-wp-dropdown-users-args-to-support-a-proper-select-option-value-html-attribute/
Often it is required to create multiple selects for Users - …
> Add multiple and value field arguments to wp_dropdown_users

- src/wp-admin/includes/misc.php
- src/wp-includes/class-simplepie.php
- src/wp-includes/general-template.php
For example: The wp_body_open function and hook backported from WP 5.2.0 in #647 both say `@since 5.2.0` - this should be `@since WP-5.2.0` instead.
Once this change is merged and included in a new release, it will flow through to https://docs.classicpress.net/reference/functions/wp_body_open/.
> Fix WP and other version specifiers in inline docs

- package-lock.json
- package.json
The PR #813 is not running GitHub Actions checks even after rebasing, adding empty commits, etc. I have seen this happen a couple of times and the only way to make it work has been to open a new PR.
Closing/reopening the PR might also work, but since that action has special meaning for the Renovate bot (it will tell the bot to ignore that specific upgrade), let's not do that.
I propose to do the following instead:
- Make sure the GitHub Actions checks run on this PR
- Trust the automated review from https://github.com/ClassicPress/ClassicPress/pull/813#issuecomment-973107086 which tells us that there are no build changes resulting from this dependency upgrade (the commit hash is the same on this PR and on #813)
- Merge this PR
- Renovate should then automatically close #813 by itself.
> Renovate[bot]: Update dependency grunt-contrib-concat to v2

- .gitignore
@viktorix had an issue where `wp-content/plugins/hello.php` was deleted accidentally. His git client didn't pick up on this change and didn't make it easy to restore the file, because the entire `wp-content/plugins` folder has been incorrectly listed in `.gitignore` as ignored. We should ignore everything in this folder _except for_ the `hello.php` and `index.php` files which really are part of the ClassicPress development code.
This PR also changes the comment at the top of `.gitignore` from WordPress to ClassicPress.
> Do not ignore existing PHP files in wp-content/plugins folder

- tests/phpunit/includes/plural-form-function.php
- tests/phpunit/tests/external-http/basic.php
- tests/phpunit/tests/pomo/pluralForms.php
Changes on the PHP site about current supported versions are breaking unit testing as reported upstream nd spooned by `joyously`
This PR backports an upstream fix for the time being and while there ensures some tests are not skipped in PHP > 7.2 in the `pomo` tests by also backporting changeset 48790
https://core.trac.wordpress.org/changeset/52260
https://core.trac.wordpress.org/changeset/48790
Upstream changes via backport
These are current failing and skipped tests
N/A
- Bug fix
> Fix for failing Unit Tests

- src/wp-admin/includes/theme.php
Possible fix for #878
Backporting to enable zip uploads for themes and plugins has introduce additional and unnecessary auto-update code. A fragment of this code produces a PHP error on the `wp-admin/themes.php` page.
This PR fixes #878 by removing the unnecessary code fragments.
Local Testing, see screen shots below
- Bug fix
> Fix fatal error in themes.php admin page

- src/wp-admin/css/list-tables.css
- src/wp-admin/includes/class-plugin-installer-skin.php
- src/wp-admin/menu.php
- src/wp-admin/network/menu.php
- src/wp-admin/plugins.php
- tests/qunit/index.html
Currently (after #788) there are two links "Upload" and "Add New" right next to each other under the Plugins admin menu and on the Plugins admin page. This is a bit confusing, since "Upload" is also a way to "Add New". I suggest changing "Add New" to "Add WP Plugin", which also makes it a bit clearer that plugins added this way come from the WP plugin repo:
| Before | After |
|--|--|
| ![2021-12-09T19-36-18Z](https://user-images.githubusercontent.com/227022/145464132-0296bf12-2a36-473a-9856-40a6bf457eee.png) | ![2021-12-09T19-43-50Z](https://user-images.githubusercontent.com/227022/145464928-eb98f1e5-4c12-474c-aa54-06a311440fb0.png) |
Finally this PR also updates the "Go to Plugin Installer" message that appears after installing or upgrading a plugin to go to the installed plugins page …
> Change "Add New" plugins menu entry to "Add WP Plugin"

- .github/workflows/phpunit-tests.yml
- src/license.txt
- tests/phpunit/tests/external-http/basic.php
As described in Issue #891 the external-http group of unit tests are currently failing for us as PHP.net is detecting our parsing of `supported-versions.php` as being non-human in origin.
It would be ideal to maintain the unit test, but running it on every supported branch of PHP is probably unnecessary.
This PR provides a possible solution by cloning the PHP.net GitHub repository and locally re-creating the `supported-versions.php` file for comparison.
Local development has included lost of repeated testing in finding a solution.
N/A
- Bug fix
> Potential fix for failing external-http tests

- package.json
This PR removes the reference to OpenCollective from the `package.json` file and fixes and open Issue
Potential fix for #855
N/A
N/A
- Update
> Remove OpenCollective from package.json

- src/wp-admin/includes/upgrade.php
- src/wp-includes/class-wp-meta-query.php
- src/wp-includes/class-wp-tax-query.php
- src/wp-includes/formatting.php
- src/wp-includes/post.php
See: https://wordpress.org/news/2022/01/wordpress-5-8-3-security-release/
This is a backport of an upstream set of security fixes affecting WP back to version 3.7.
The patch applied to the  4.9 trunk has been backported here.
Upstream backport with visual comparison only.
N/A
- Bug fix
> Backport of security release

- src/wp-admin/menu-header.php
CP choose what to highlight in `src/wp-admin/menu-header.php`.
The PR try to address the very specific bug reported. This is not a good approach for me, but the file changed already have very specific cases that are handled.
Fix #924 
Local install.
Can't write unit tests.
> Fix #924 Incorrect menu item highlights as current

- src/wp-admin/includes/update-core.php
In #695 we updated Dashicons to the most recent and final iteration from upstream.
In the upgrade code we list a file as an '$_old_file' that we now include in our build.
This fix removes the affected file from the '$_old_file' list.
Issue was noted during PHPUnit testing after a build process. The removal of this file listing fixed the reported PHPUnit failure.
N/A
- Bug fix
> Remove wp-includes/fonts/dashicons.woff2 from $_old_files

- package-lock.json
Restore GitHub actions by updating package-lock.json to lockfileVersion 2
Currently there are 2 Renovate bot PRs that are failing tests because `grunt-cli` fails to install correctly during the GitHub action. This seems like it may be linked to the package-lock.json file being on lockfileVersion 1
Locally testing I was able to reproduce the same issued when running `npm ci` on the command line. Updating package-lock.json with `npm update` and trying `npm ci` again now works.
With this commit we can see if GitHub Actions now pass.
N/A
- Bug fix
> Update package-lock.json to lockfileVersion 2

- composer.json
Build/Test Tools: Allow the PHPCS plugin in Composer configuration.
The dealerdirect/phpcodesniffer-composer-installer Composer plugin is used to register external PHPCS standards with PHPCS.
As of Composer 2.2, Composer plugins need to be explicitly allowed to run. This commit adds the necessary configuration for that to prevent Composer asking every single time composer install or composer update is run.
Reference: [Composer 2.2: More secure plugin execution](https://blog.packagist.com/composer-2-2/#more-secure-plugin-execution).
Props jrf, johnbillion.
Fixes [#54686](https://core.trac.wordpress.org/ticket/54686).
Maintains functionality of some GitHub Actions
Upstrem backport, locally tested on another PR that wasn't a backport:
https://github.com/ClassicPress/ClassicPress/pull/960 …
> Add 'allow-plugins' to composer.json

- src/wp-includes/js/tinymce/plugins/wordpress/plugin.js
Version 1.4.0 contained changes to `src/wp-includes/js/tinymce/plugins/wordpress/plugin.js` that results in a bug in the visual editor whereby paragraph are stripped.
This PR revery prior changes and restores expected behaviour and this is a potent hot fix #967
Locally tested and reproduced the issue in `develop`
- Bug fix
> Restore removed code to TinyMCE plugin

- src/wp-includes/js/wp-util.js
This PR improves the error that appears in the browser console when one of the JavaScript templates used in various places in the admin screens is malformed and cannot compile. This still results in a broken site, potentially with other JavaScript errors appearing later on, but this change makes it much easier to track down the real problem.
The previous error message is not very helpful about what is going on:
This PR improves the error message to explain more about what operation was being performed when the error occurred, and also provides a way to see more data using a new variable `wp.template.errorData`:
Cause a syntax error in one of the templates, for example by removing these two lines from `wp-admin/themes.php`:
https://github.com/ClassicPress/ClassicPress/blob/b7562b7b4594971a0 …
> Improve JS template error handling

- src/wp-admin/includes/class-wp-filesystem-direct.php
Backporting of upstream changes for PHP Compatibility (#958) included a bug that has also been fixed upstream in a further ticket. Unfortunately this was not noted in testing or code review before committing - thanks to @xxsimoxx for raising awareness.
Change upstream reference an undeclared variable as an incorrect variable name was used, this was fixed in the change set below.
WP-r45613: Filesystem API: Check correct variable in `WP_Filesystem_Direct::dirlist()` after https://core.trac.wordpress.org/changeset/45611.
WP:Props zinigor.
Fixes https://core.trac.wordpress.org/ticket/47668. See https://core.trac.wordpress.org/ticket/47632.
---
Merges https://core.trac.wordpress.org/changeset/45613 / WordPress/wordpress-develop@40d9fdf1f9 to ClassicPress.
See screenshots below
- Bug fix
> Filesystem API: Correct variable name

- src/wp-includes/rest-api.php
During the backport of 48256 that was merge in #732 we have used an incorrect variable name.
The upstream code also contains checks to ensure that REST API namespaces do not start or end with a slash, this is part of [47842](https://core.trac.wordpress.org/changeset/47842)
Backporting the above may well be a breaking change for any code using a namespace with a slash included at the tart or end of the namespace, so the easiest fix is a variable name correction in our code.
Will need testing under conditions that identified the issue as reported in issue #974 
As such, this may Fix #974 
N/A
- Bug fix
> Fix variable name in REST API

- src/wp-includes/PHPMailer/PHPMailer.php
- src/wp-includes/PHPMailer/SMTP.php
This PR updates PHPMailer from 6.6.0 to 6.6.2
See: https://core.trac.wordpress.org/changeset/53500
> Update PHPMailer from 6.6.0 to 6.6.3

- .github/CONTRIBUTING.md
- composer.json
Add a script to composer to make it easier to backport changes.
I have to check the contributions.md file everytime I have to backport changes. Remembering the bash script is mind taxing yet we have composer usage in the repo. If I have to check and type this for 4 changesets in one task, it is limiting.
In addition to  `bin/backport-wp-commit.sh -c CHANGESET_NUMBER` can we make this easier with `composer run backport CHANGESET_NUMBER`?
This does not break anything but allows us to utilize the tools already available to make the task easier.
See manual tests below in screenshots.
Using the `composer run backport without changeset`
Using the `composer run backport with changeset`
> Add backport script to composer

- README.md
"Become a sponsor" URL was wrong.
Issue reported in PR #1040 
https://github.com/ClassicPress/ClassicPress/pull/1040#issuecomment-1185764958
Checked README.md in my own fork on Github.
- Bug fix
> Fixed "Become a sponsor" URL in README.md

- src/wp-includes/css/dashicons.css
WP-r45310: Administration: Remove duplicate `font-face` declaration n Dashicons CSS.
This was causing console warnings in some browsers.
WP:Props aduth, joen, afercia, timph, ianbelanger.
Fixes https://core.trac.wordpress.org/ticket/47183.
---
Merges https://core.trac.wordpress.org/changeset/45310 / WordPress/wordpress-develop@cc12950d41 to ClassicPress.
I noticed a console error in my browser when viewing my site, the error related to a missing server resource:
https://www.example.com/wp-includes/fonts/dashicons.eot?50db0456fde2a241f005968eede3f987
The upstream ticket and changeset I located was merged 3 years ago as a fix for this issue. After applying the patch the issue is resolved in the browser.
Upstream testing was done and I have applied the patch on my live sites and confirmed …
> WP-r45310: Remove duplicate `font-face` declaration

- src/wp-admin/includes/image.php
Changeset [43750](https://core.trac.wordpress.org/changeset/43750) passes EXIF Data to the wp_read_image_metadata filter and changeset [43749](https://core.trac.wordpress.org/changeset/43749) fixes a merge conflict by replacing sourceImageType with image_type.
Fixes #904. See ticket ticket [43624](https://core.trac.wordpress.org/ticket/43624) for details.
A quick way to test it is to add the following code to your functions.php. Make sure to upload a photo with exif data and replace the file path in the code. Load the website, it should show you exif data and the word "Yes!". See screenshot below.
```
add_action( 'wp_read_image_metadata', 'exif_data', 10, 5 );
function exif_data( $meta, $file, $image_type, $iptc = null, $exif = null ) {
// If there is no Exif Version set return.
if ( …
```
> Pass EXIF Data to the wp_read_image_metadata filter #904

- src/wp-admin/includes/class-wp-filesystem-ssh2.php
As per upstream [ticket](https://core.trac.wordpress.org/ticket/52409) the current WP_Filesystem_SSH2  file needs updating to avoid update errors on more modern servers. This is because support for `ssh-rsa` is being phased out.
See above
Upstream ticket and patch, we may need a broader understanding of this but PR is minimal.
N/A
- Bug fix
- New feature
> Update ssh-rsa hostkey options for  SSH2

- src/wp-includes/vars.php
Update the `$is_edge` global to be `true` if the browser's user-agent contains `Edg` rather than `Edge`. Microsoft have dropped an E from the UA string.
Refer to [https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-guidance#identifiers-for-microsoft-edge-on-various-platforms Microsoft's documentation on detecting edge].
WP:Props costdev, abdullahramzan, mukesh27, Boniu91.
Fixes https://core.trac.wordpress.org/ticket/55297.
---
Merges https://core.trac.wordpress.org/changeset/52825 / WordPress/wordpress-develop@177c315c12 to ClassicPress.
Upstream ticket backport to improve browser detection.
This change improves detection of the Edge browser.
Testing on upstream ticket and references to best practices for browser detection as per Edge development team
N/A
- Bug fix / …
> WP-r52825: General: Improve MS Edge user-agent sniff.

- src/wp-includes/wp-db.php
WP-r51582: Code Modernization: Set the MySQLi error reporting off for PHP 8.1.
Prior to PHP 8.1, the default error handling mode was `MYSQLI_REPORT_OFF`. An error in the extension, database, query, or the database connection returned `false` and emitted a PHP warning:
{{{
$mysqli = new mysqli("localhost", "non-existing-user", "", "");
Warning: mysqli::__construct(): (HY000/2002): No connection could be made because the target machine actively refused it in ... on line ...
}}}
From PHP 8.1 and later, the default error mode is set to `MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT`. An error in the extension, database, query, or the database connection throws an exception:
{{{
$mysqli = new mysqli("localhost", "non-existing-user", "", "");
Fatal error: Uncaught mysqli_sql_exception: Connection …
> WP-r51582: Set the MySQLi error reporting off for PHP 8.1

- src/wp-includes/class-walker-nav-menu.php
This is a slightly different PR. The main thing it does is backports [changeset 42808](https://core.trac.wordpress.org/changeset/42808). This changeset introduced a bug that causes PHP errors, reported in [ticket 46382](https://core.trac.wordpress.org/ticket/46382). The ticket has a patch that's 3 years old and WP hasn't fixed it. It simply misses `empty()`.
Changeset does improve accessibility of the nav menu, so it's good to have. While the patch fixes PHP errors. This was originally requested as [a petition](https://forums.classicpress.net/t/add-empty-check-to-class-walker-nav-menu-php/2929/4). 
No merge conflicts.
The changeset improves the accessibility of the nav menu, while the patch fixes a bug introduced by that changeset.
When you have an active theme and a menu, click on a menu …
> Accessibility: Themes: use aria-current for the Walker_Nav_Menu current link (and patch)

- phpunit.xml.dist
- src/wp-includes/general-template.php
- src/wp-includes/php-compat/readonly.php
- tests/phpunit/multisite.xml
- tests/phpunit/tests/general/template.php
- tests/phpunit/tests/general/template_CheckedSelectedHelper.php
Backport of upstream fix for PHP8.1 reserved name.
This change ensure future compatibility with PHP8.1 and closes #775
Upstream backport
Unit test files included in backport changes
N/A
- Bug fix
> WP-r51586: Rename the readonly() function to `wp_readonly()`

- src/wp-admin/includes/update-core.php
WordPress 3.2 introduced several enhancements to the copy_dir() function via a wrapper function.
However, the version of copy_dir() that runs during the upgrade process is the one from the older install, not the newer, which means that these enhancements would only be available after upgrading to WordPress 3.2 first, e.g. in a subsequent upgrade to WordPress 3.3.
Since this code was added well before ClassicPress was created, and it has been removed from WordPress core, we can consider removing to reduce code size.
Code based checked for calls to function via `grep` and upstream patch has been reviewed and committed.
N/A
- Enhancement
> Upgrade/Install: Remove _copy_dir() function

- src/wp-admin/includes/schema.php
- tests/phpunit/tests/avatar.php
- tests/phpunit/tests/rest-api/rest-comments-controller.php
- tests/phpunit/tests/rest-api/rest-users-controller.php
- tests/phpunit/tests/schema.php
- tests/qunit/fixtures/wp-api-generated.js
***Originally Pull Request 803***
[Original Pull Request](https://github.com/ClassicPress/ClassicPress/pull/803) repository has been deleted.
Change a setting so that avatars are set to "off" by default.
This PR changes the default setting of the show avatars checkbox to be unchecked on any new CP installation.
All of the avatar options (including the default mystery option) involve a call out to Gravatar, which is run by Automattic. This is a privacy concern for CP.
The petition has a lot of popular support. More discussion here: https://forums.classicpress.net/t/disable-gr-avatar-by-default/2801
On a new install change this line in schema.php from 1 to 0.
```
// 2.5
'show_avatars' => '0',
```
Set up the new site and check in the settings.
**NOTE:** As with the other previous change to …
> Set default show_avatars option to off

- src/wp-admin/includes/schema.php
- tests/phpunit/tests/comment-submission.php
- tests/phpunit/tests/comment.php
- tests/phpunit/tests/comment/commentForm.php
- tests/phpunit/tests/feed/rss2.php
- tests/phpunit/tests/post.php
- tests/phpunit/tests/rest-api.php
- tests/phpunit/tests/rest-api/rest-comments-controller.php
- tests/phpunit/tests/rest-api/rest-schema-setup.php
- tests/phpunit/tests/schema.php
- tests/phpunit/tests/xmlrpc/wp/newComment.php
- tests/qunit/fixtures/wp-api-generated.js
***Originally Pull Request 793***
[Original Pull Request](https://github.com/ClassicPress/ClassicPress/pull/793) repository has been deleted.
Will need addition of a test for default setting once #1109 is merged.
This changes a setting that gets loaded into the database when CP initially installs, so that comments are turned **off** by default, not **on**.
The comment system is something that users should _choose_ to use, rather than have it forced on them and have to remember to disable it.
We no longer have Akismet as an included plugin, so we are currently enabling comments by default but not providing any way to deal with the mountains of spam this will generate. 
There is also the issue that comments can be enabled on media items by accident, even though the user is not even using …
> Change default_comment_status to closed

- src/wp-includes/post.php
Backport of Changeset [47856](https://core.trac.wordpress.org/changeset/47856): Posts, Post Types: Pass the post object to the delete_attachment action. Follows PR #805
Also add the missing `$post` parameter to the `delete_post` and `deleted_post actions` in `wp_delete_attachment()`.
Upstream
> WP-r47856: Posts, Post Types: Pass the post object to the delete_attachment action.

- src/wp-admin/includes/post.php
WP-r52141: Posts, Post Types: Update `_edit_last` meta when posts are edited in bulk.
When posts are edited in bulk, the `_edit_last` meta was not updated for each post.  This change adds a call to update the `_edit_last` meta to the current user ID for each post the is updated.
WP:Props calebwoodbridge, peterwilsoncc, guillaumeturpin, audrasjb.
Fixes https://core.trac.wordpress.org/ticket/42446.
---
Merges https://core.trac.wordpress.org/changeset/52141 / WordPress/wordpress-develop@04f62997d3 to ClassicPress.
Backport of know issue reported upstream at:
https://core.trac.wordpress.org/ticket/42446
Currently, bulk editing a post does not amend the last editing user information, while it does update the last edited date and time.
This seems like a simple and good bug fix for bulk editing …
> WP-r52141: Update `_edit_last` meta when posts are bulk edited

- src/wp-includes/post.php
Backports changeset [47582](https://core.trac.wordpress.org/changeset/47582): Posts, Post Types: Pass the post object to the before_delete_post, delete_post, deleted_post, and after_delete_post actions.
From [Trac](https://core.trac.wordpress.org/ticket/30940):  When using `wp_delete_post()`, four actions are fired: `before_delete_post`, `delete_post`, `deleted_post` and `after_delete_post`. All of them get the `$postid` argument.
In some situations, it might be useful to have some extra information about the post being deleted, to perform different actions depending on things like the post date or the post type. With extensive usage of custom post types, this becomes more evident.
We can always get that data from the post ID being passed as an argument on those four actions, but that …
> WP-r47582: Pass the post object to the before_delete_post, delete_post, deleted_post, and after_delete_post actions.

- src/wp-admin/includes/class-wp-plugin-install-list-table.php
- src/wp-admin/includes/plugin.php
- src/wp-admin/includes/update.php
- src/wp-includes/update.php
This allows third-party plugins to avoid accidentally being overwritten with an update of a plugin of a similar name from the WordPress.org Plugin Directory.
Additionally, introduce the `update_plugins_{$hostname}` filter, which third-party plugins can use to offer updates for a given hostname.
1. Give plugin developers to specify that the updates are not handled by the WP repo.
2. Add a filter that can be useful in the integration of the new ClassicPress directory.
With this code I've successfully update a plugin trom a fork of the new directory.
**Note: the 'View Details' link with this code don't work.**
```
add_filter('update_plugins_dir.educatorecinofilo.dog', 'xsx_test', 10, 4);
function xsx_test($update, $plugin_data, $plugin_file, $locales) {
$slug = dirname($plugin_file); …
```
> WP-r50921: Add support for `Update URI` plugin header

- src/wp-includes/PHPMailer/PHPMailer.php
- src/wp-includes/PHPMailer/SMTP.php
This is a maintenance release with minor changes:
* Don't try to issue `RSET` if there has been a connection error.
* Reject attempts to add folders as attachments.
* Don't suppress earlier error messages on `close()`.
* Handle `Host === null` better.
Release notes:
https://github.com/PHPMailer/PHPMailer/releases/tag/v6.6.5
For a full list of changes in this update, see the PHPMailer GitHub: https://github.com/PHPMailer/PHPMailer/compare/v6.6.4...v6.6.5
Follow-up to https://core.trac.wordpress.org/changeset/50628, https://core.trac.wordpress.org/changeset/50799, https://core.trac.wordpress.org/changeset/51169, https://core.trac.wordpress.org/changeset/51634, https://core.trac.wordpress.org/changeset/51635, https://core.trac.wordpress.org/changeset/52252, …
> WP-r54427: External Libraries: Upgrade PHPMailer to version 6.6.5

- src/wp-admin/includes/media.php
Backport https://core.trac.wordpress.org/changeset/47251
In `media_sideload_image()`, store the original attachment URL in the `_source_url` post meta value.
Picks https://core.trac.wordpress.org/changeset/47251 as a follow-up of https://github.com/ClassicPress/ClassicPress/pull/950
Thanks to @dshanske via https://github.com/ClassicPress/ClassicPress/issues/1026#issuecomment-1272182273
> wp-r47251:: Store the original attachment URL in the `_source_url` post meta value 

- src/wp-admin/includes/template.php
WP-r52841: Quick/Bulk Edit: Check the `show_in_quick_edit` taxonomy property when populating the data for the posts list table.
Previously, setting the `show_in_quick_edit` property to `false` removed the taxonomy from the inline edit form, but the terms were still being populated in the data for each table row via the `get_inline_data()` function, which only checked the `$taxonomy->show_ui` property.
This commit:
* Improves performance by ensuring that taxonomy terms are not unnecessarily populated for each table row when `show_in_quick_edit` is `false`.
* Properly populates the taxonomy terms when `show_in_quick_edit` is `true` and `show_ui` is `false`.
Follow-up to https://core.trac.wordpress.org/changeset/31307.
WP:Props jazbek, figureone, sabernhardt, ovidiul, webcommsat, …
> WP-r52841: Quick/Bulk Edit taxonomy improvement

- src/wp-includes/version.php
In src/wp-includes/version.php should be as in [WP 4.9 branch](https://github.com/WordPress/WordPress/blob/8564a4a082705b9984e3361b78259d840feafe91/wp-includes/version.php#L7):
$wp_version = '4.9.22';
- Bug fix
> Bump `$wp_version` to 4.9.22 fixes #1149

- .github/workflows/coding-standards.yml
- .github/workflows/javascript-tests.yml
- .github/workflows/php-compatibility.yml
- .github/workflows/phpunit-tests.yml
While merging PRs on 13th October, some deprecation notices were noted in the GitHub Actions runner.
In order to avoid future failure of out GitHub actions the utilised versions of several action steps have been updated in this PR.
The Triage and Welcome workflows should not currently be affected.
The Workflows should run successfully in this PR and without those same warnings if this PR is correct.
- Bug fix
> Update GitHub actions to avoid node deprecation warnings

- .github/workflows/coding-standards.yml
- .github/workflows/javascript-tests.yml
- .github/workflows/phpunit-tests.yml
- bin/compare-build-branch.sh
- renovate.json
This PR makes the build and compare bash script work on MacOS locally as well as Unix, it adds a section to the Renovate PR message about what tests need to be performed and also updates the Workflow actions to avoid the deprecated `set-output` command
Maintain unit testing and ease Renovate creation and testing
- new NVMRC reading has been testing in a private repository and tests should work on this PR
- build script can be tested on unix and MacOS after merge but has been tests on MacOS locally.
- Renovate added section will need to await next Renovate PR creation
N/A
- Enhancement
> Enhancements to Renovate

- src/wp-includes/theme.php
Themes: After https://core.trac.wordpress.org/changeset/46164, make sure `$type_attr` is always defined in `_custom_background_cb()`.
WP:Props davidbaumwald.
Fixes #1162.
---
Merges https://core.trac.wordpress.org/changeset/46270 / WordPress/wordpress-develop@d88473fa2f to ClassicPress.
> WP-r46270:: Make sure `$type_attr` is always defined in `_custom_background_cb()`.

- src/wp-includes/class-wp-xmlrpc-server.php
XML-RPC: Avoid a PHP warning in wp_xmlrpc_server::minimum_args() if $args is not an array.
Correct the documentation to clarify that array is the only acceptable type for $args.
Props bitcomplex, dkarfa.
Fixes [#48046](https://core.trac.wordpress.org/ticket/48046).
Fixes #1079
> WP-r46148: Avoid a PHP warning in wp_xmlrpc_server::minimum_args() if $args is not an array.

- src/wp-includes/class-wp-feed-cache.php
- src/wp-includes/feed.php
Fixes #1164 
This PR backports an upstream fix for instantiation of SimplePie for the dashboard "ClassicPress News" widget that affects PHP8.
This PR fixes an issue identified in testing and continues the work towards PHP8 compatibility.
Local testing before and after.
- Bug fix
> Fix for PHP8 error in "ClassicPress News" widget

- src/wp-admin/import.php
- src/wp-admin/includes/import.php
Replace the hard-coded API URL used for collecting a list of importer plugins.
Fixes #1168 however it should be noted that the Wordpress importer can no be installed due to the plugin declaring it is incompatible.
It also seems that the default list contained in the `` file is in use prior to this PR so maybe the WordPress API is failing.
Local testing and viewing of database transient entry.
- New feature
> Update importer API

- src/wp-includes/media.php
- tests/phpunit/tests/media.php
This ia a backport if an upstream ticket found that addresses an edge case I have seen locally about image sizez:
https://core.trac.wordpress.org/ticket/50543
There are 2 more subsequent tickets that impact on this function:
https://core.trac.wordpress.org/ticket/50722
https://core.trac.wordpress.org/ticket/51865
But so far it seems that they are not required.
This appears to be a edge case bug that may affect end users on the releast of ClassicPress 1.5.0
Local testing shows this backport of the upstream change fixes the issue observed, screenshots attached.
Unit tests are also included in the PR.
- Bug fix
> wp_image_src_get_dimensions() may throw warning or return wrong values

- src/wp-includes/formatting.php
- src/wp-includes/functions.php
- tests/phpunit/tests/formatting/cpAttributes.php
To account for easy output of a HTML tag with no attributes, the `cp_attributes` function should handle the leading space. This PR changes the function to handle the space (and URL escaping for action attributes). Spaces are removed from the HTML surrounding the calls to `cp_attributes`, including in tests.
When using the new `cp_attributes` function, cases of plain tags, like `<li>`, failed unit tests with `<li >`. This should be handled correctly by the function, from the outset.
unit tests, local theme calls to the function
> change cp_attributes to account for the space (or not) at the beginning

- src/wp-login.php
Two HTML tags are missing their closing tags.
Reported in forum: https://forums.classicpress.net/t/reporting-a-cosmetic-bug-in-the-login-module/4438
> add missing end tags for the Go to site link and paragraph

- src/wp-admin/includes/class-wp-automatic-updater.php
This is related to [issue 32 in Documentation Tracker](https://github.com/ClassicPress/Documentation-Issue-Tracker/issues/32).
Changed URL to the correct bug reporting URL and updated wording to be more helpful.
An email sent when beta testing contained a broken bug reporting link. 
I haven't tested this yet. I need help understanding how the email is triggered. There are no code changes, only text in the email body sent to the user.
- Bug fix
> Updated bug reporting link

- src/wp-includes/functions.php
- tests/phpunit/tests/functions/wpNonceField.php
- tests/phpunit/tests/functions/wpRefererField.php
Remove instances of _wp_http_referer from GET forms in the admin.
This changeset removes all instances of _wp_http_referer variable from the URL when creating a hidden input for _wp_http_referer. It prevents the hidden field from having an additional version of _wp_http_referer each time the form is submitted.
Props msolution, justinahinon, pbearne, mikeschroder, mukesh27, audrasjb, Clorith, chaion07, robinwpdeveloper, hztyfoon, davidbaumwald, costdev, adamsilverstein.
See: https://core.trac.wordpress.org/ticket/54106#comment:21 and https://core.trac.wordpress.org/ticket/54106#comment:22
> wp-r54420:: Remove instances of _wp_http_referer from GET forms in the admin.

- tests/phpunit/tests/external-http/basic.php
- tests/phpunit/tests/http/base.php
The PHPUnit tests compare the readme to currently supported versions of PHP and MySQL.
This PR updates the test with improved redundancy when the remote servers fail to respond with the expected content.
For the PHP test we already clone the GitHub repository and use that rather than querying the php.net site repeatedly.
There is no option to do this for the MySQL site, but what this PR dose is introduce a skipped test on a 503 response from the server rather than failing the test. (When the server is unavailable).
This will help to reduce failed unit test runs seen when external sites are busy.
It is a manual backport of an upstream fix.
Local testing done and automated tests will run on this PR.
N/A
- New feature
> Make external tests less flaky

- src/wp-admin/includes/ajax-actions.php
- src/wp-admin/includes/class-theme-upgrader.php
- src/wp-admin/includes/theme.php
- src/wp-admin/js/theme.js
- src/wp-admin/theme-install.php
- src/wp-includes/class-wp-customize-manager.php
WP-r42632: Themes: Use api.wordpress.org/themes/info/1.2/ to query theme information.
See https://core.trac.wordpress.org/ticket/43192.
Also Hide console logging in Theme Installer.
To fix a warning that came out testing this backport added to PR:
WP-r48493: Upgrade/Install: Check if the theme installer skin's `overwrite` property exists in `Theme_Upgrader::install_strings()`.
This ensures consistency with `Plugin_Upgrader::install_strings()` and resolves an issue caused by the property not existing in other upgrader implementations.
> WP-r42632: Themes: Use api v. 1.2 to query theme information.

- src/wp-admin/includes/plugin.php
`get_plugin_data()` and so `get_plugins()` don't return the `Requires CP` header value.
This is very useful for directory integration. This is a small change so can be included in version 1.5.0.
> Add support for Require CP header in plugins

- src/wp-includes/post-thumbnail-template.php
As reported on the [forums](https://forums.classicpress.net/t/upgrade-to-1-5-0-two-issues-cant-edit-archives-tags-and-categories-and-warning-preg-match-no-ending-delimiter/4495/7) - there is an issue in 1.5.0 related to post thumbails.
This is a bug introduced in version 1.5.0 that produces PHP warnings for some users.
It seems it may be theme dependent and requires that the theme supports `post-thumbnails` and also calls the `get_the_post_thumbnail()` function with a string passed for the third function parameter, an optional query string of attributes.
By making some changes to the TwentySeveneteen theme locally I was able to produce the Warning locally on a post with a Featured Image. I then applied the proposed fix - adding a trailing slash to the Regex as per this PR and that …
> Fix incomplete `preg_match` regex in `get_the_post_thumbnail()`

- src/wp-includes/compat.php
- tests/phpunit/tests/compat/strContains.php
This PR is a backport of changeset [52039](https://core.trac.wordpress.org/changeset/52039). It introduces some polyfills for newly introduced PHP functions for compatibility reasons.
This should help with new installs for user still on PHP 5.6.x (although they should be strongly encouraged to move to at lease PHP 7.4 for security reasons.
Upstream patch.
Locally installed fresh vanilla site on PHP 5.6.40
N/A
- Bug fix
> Introduce polyfill for str_contains()

- src/wp-includes/admin-bar.php
As reported on the [forums](https://forums.classicpress.net/t/upgrade-to-1-5-0-two-issues-cant-edit-archives-tags-and-categories-and-warning-preg-match-no-ending-delimiter/4495), version 1.5.0 includes a call to a function we have not backported.
This PR reverts to the previous way of checking if a taxonomy (or category) is public and restores functionality of the aility to edit categories.
Comparison to previous and upstream code. Localhost testing complete (see screen shots)
- Bug fix
> Avoid call to non-existent `is_taxonomy_viewable()` function

- src/wp-includes/bookmark.php
With `WP_DEBUG` and `WP_DEBUG_DISPLAY` set as true I noted some errors in the sidebar of one of my sites about an undefined variable, this is due to some instances of `$r` having been missed when backporting and updating to use of `$parsed_args`.
This is a bug fix
Tested on on of my production sites. Force re-produced locally as Links Manager needs to be enabled and in use.
- Bug fix
> Fix parsed variable names

- src/wp-admin/setup-config.php
During the setup process for a fresh install the `wp-config.php` file is created or the contents displayed to the new user for manual creation. Since the layout of the `wp-config-sample.php` was made more readable some of the values fail to populate in either the created file or in the displayed file for manual creation.
The above essentially breaks the setup process for new users, the file needs to be amended before it will work and connect to the database and allow a new installation.
This PR corrects the creation process and now populates several values into `wp-config.php` to re-enable a more effective fresh install process.
Locally tested both methods of creation of the wp-config.php file, both automatic and manual, with and without this change.
N/A
- Bug fix
> Allow for spaces in config-sample `defines`

- src/wp-includes/functions.php
- tests/phpunit/tests/functions/isSerialized.php
This changeset adds support for Enums in `is_serialized()`. It also adds new unit tests for this function.
WP:Props ayeshrajans, konradyoast, peterwilsoncc, costdev, dennisatyoast, mukesh27. Fixes https://core.trac.wordpress.org/ticket/53299.
Conflicts:
- src/wp-includes/functions.php
---
Merges https://core.trac.wordpress.org/changeset/53886 / WordPress/wordpress-develop@38037ebb2c to ClassicPress.
PHP compatibility and partially addresses #1098
Backport, includes new unit testing.
N/A
- Enhancement
> WP-r53886: Formatting: Add support for Enums in `is_serialized()`.

- src/wp-admin/includes/dashboard.php
Add a dashboard widget warning about PHP support, security maintenance status of `v1` and future release of `v2` of ClassicPress
Deprecation notice and user warning about PHP support, and `v2`
Local Testing so far only.
- Enhancement
> Add dashboard upgrade widget

- src/wp-admin/includes/class-wp-plugin-install-list-table.php
This PR is a Cherry pick of wp-r47198
This should fix an issue reported on the forums:
https://forums.classicpress.net/t/php-fatal-error-cannot-redeclare-plugins-api-previously-declared-in-wp-admin-includes-plugin-install-php-101/4885
OP on forum reports this fix is good.
See forum post
- Bug fix
> Fixes potential issue in plugin modal

- .github/workflows/phpunit-tests.yml
- src/wp-admin/includes/dashboard.php
To comply with SemVer, a deprecation notice added for #1247 
See #1247
Locally.
> feat: XHTML deprecation notice added

- src/wp-content/themes/twentysixteen/js/functions.js
Fix for deprecated jQuery in TwentySixteen theme.
>  Fix deprecated jQuery warning message

- .github/workflows/coding-standards.yml
- .github/workflows/javascript-tests.yml
- .github/workflows/php-compatibility.yml
- .github/workflows/phpunit-tests.yml
GitHub actions have a protection to ensure they only run on pull requests and within this repository. Currently, checks are not running on merge to `develop` following the repository migration, this PR fixes this issue.
Testing should run after merges to the `develop` branch,
Visual changes seem correct, will know for sure when this is merged.
N/A
- Bug fix
> Fix: Enable Actions on code merge

- phpcs.xml.dist
This PR updates and refactors the phpcs rule definitions, it is more consistent with the PWCS 3.x standards in use and hopefully will fix the failing GitHub test.
Fix for failing GitHub test
Local testing works, but always has done.
- Bug fix
> Refactor and update phpcs rules

- src/wp-includes/class-wp-http.php
This changeset prevents a PHP 8.3 deprecation shown when enabling debug and calling `get_class()` without arguments.
For more info about this deprecation, see https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures#get_class_and_get_parent_class.
WP:Props ipajen, rajinsharwar, SergeyBiryukov, jrf. Fixes https://core.trac.wordpress.org/ticket/58876.
---
Merges https://core.trac.wordpress.org/changeset/56495 / WordPress/wordpress-develop@98284ae792 to ClassicPress.
> WP-r56495: HTTP API: Update `WP_Http` class to avoid PHP deprecation

- src/wp-includes/kses.php
- tests/phpunit/tests/kses.php
Update `wp_kses`* functions to accept `null` as `$content` parameter.
Starting from PHP 8.1: [(source)](https://www.php.net/manual/en/migration81.deprecated.php)
> Scalar types for built-in functions are nullable by default. This behaviour is deprecated to align with the behaviour of user-defined functions, where scalar types need to be marked as nullable explicitly.
`wp_kses`* functions pass `$content` to `preg_replace` and similar, triggering a deprecation if `$content` is `null`.
Many plugins are using those functions without checking if the `$content` is null.
Said that is up to plugin developers to do this check, this PR helps with many plugins not doing that.
Unit tests.
Tested also with this code:
```php
echo 'wp_kses_stripslashes: ';
$x=wp_kses_stripslashes(null, ''); …
```
> Update `wp_kses`* functions to accept `null` as `$content` parameter

- .eslintrc.js
- src/wp-admin/js/code-editor.js
This PR futher enhances the new ESLiniting configuration to check for trailing white space at the end of lines.
Saving this space in the code reduces (minimally) file sizes for development but is a very easy fix and addition.
Local testing already identified trailing space in one file.
N/A
- New feature
> Add ESlinting for trailing spaces

- src/wp-admin/includes/network.php
- src/wp-admin/network/site-info.php
- src/wp-includes/ms-site.php
- tests/phpunit/tests/multisite/site.php
This PR is copied from https://github.com/WordPress/wordpress-develop/pull/5675/files.
WordPress don't allow custom ports in MultiSite.
Can be a plus for ClassicPress to let users do this.
Having users doing tests on LAMP-like stacks, it's easier to test pull request for multisite on those stacks that use non standard port.
Localhost and unit tests
- New feature
> Support Ports on Multisite Domains

- src/wp-admin/setup-config.php
During new setup, the `wp-admin/setup-config.php` page displays a database name placeholder of `wordpress` in the text field, this should be changed.
Branding as ClassicPress in as many places as possible, especially for new installs.
Locally tested, see screenshots below.
- Bug fix
> Use classicpress as example database name at setup

- src/wp-admin/freedoms.php
In `wp-admin/freedoms.php` we removed a link to WordPress that it's already in place in (some) translations.
Can be checked with italian.
That throws a fatal error for a missing argument in `sprintf`.
Adding a link to GPL solves the issue, and the string is no more localized.
Local testing
Italian:
English:
- Bug fix
> Fix fatal with some translations

- src/wp-admin/includes/class-file-upload-upgrader.php
- src/wp-admin/includes/schema.php
- src/wp-admin/update.php
- Install: When populating options, maybe_serialize instead of always serialize.
- Uploads: Check for and verify ZIP archives.
Merges https://core.trac.wordpress.org/changeset/57388 and https://core.trac.wordpress.org/changeset/57389 to the 6.2 branch.
WP:Props costdev, peterwilsoncc, azaozz, tykoted, johnbillion, desrosj, afragen, jorbin, xknown.
---
Merges https://core.trac.wordpress.org/changeset/57393 / WordPress/wordpress-develop@867c01b844 to ClassicPress.
Backport from release of WP 6.4.2 and backported versions
Unit tests will run and this is a clean backport
N/A
- Bug fix
> WP-r57393: Grouped Backports to the 6.2 branch

- src/wp-includes/Text/Diff/Engine/native.php
Dynamic (non-explicitly declared) properties are deprecated as of PHP 8.2 and are expected to become a fatal error in PHP 9.0.
There are a number of ways to mitigate this:
* If it is an accidental typo for a declared property: fix the typo.
* For known properties: declare them on the class.
* For unknown properties: add the magic `__get()`, `__set()`, et al. methods to the class or let the class extend `stdClass` which has highly optimized versions of these magic methods built in.
* For unknown ''use'' of dynamic properties, the `#[AllowDynamicProperties]` attribute can be added to the class. The attribute will automatically be inherited by child classes.
In this case, the properties, as used in the class methods, fall in the “known property” category.
Reference: …
> WP-r55752: Code Modernization: Declare properties in `Text_Diff_Engine_native`

- src/wp-includes/class-fix-wpcli.php
As reported on Zulip, wp-cli is missing:
- `$cp_version`
- `classicpress_version()`
- `classicpress_version_short()`
- `classicpress_is_dev_install()`
This is due to how wp-cli bootstraps ClassicPress.
`wp eval 'global $cp_version; echo $cp_version . "\n";echo classicpress_version()."\n";echo classicpress_version_short()."\n"; echo classicpress_is_dev_install()."\n";'`
- Bug fix
> Fix `wp-cli` to bring `$cp_version` into scope

- src/wp-admin/includes/template.php
This adds an empty `span` to a specific product metabox whenever WooCommerce is active. It fixes the problem reported at https://forums.classicpress.net/t/woocommerce-3-9-5-broken-in-rc1-nightly/5094/1
It does so by implementing in the core `template.php` file the fix identified at https://forums.classicpress.net/t/woocommerce-3-9-5-broken-in-rc1-nightly/5094/3?u=simone
> Fix compatibility issue between CP v.2 and WooCommerce v.3.9.5

- src/wp-admin/about.php
This PR updates the release announcement link for the "Bella" release from the about.php page in admin.
Correct link will avoid redirect path on the server for a slightly faster user experience.
Local testing.
N/A
- Bug fix
> Update about.php with correct forum link

- .github/workflows/phpunit-tests.yml
- tests/phpunit/tests/admin/wpSiteHealth.php
- tests/phpunit/tests/customize/manager.php
- tests/phpunit/tests/file.php
- tests/phpunit/tests/hooks/addFilter.php
- tests/phpunit/tests/includes/factory.php
- tests/phpunit/tests/post/query.php
- tests/phpunit/tests/post/revisions.php
- tests/phpunit/tests/post/slashes.php
- tests/phpunit/tests/theme/WPTheme.php
- tests/phpunit/tests/user/capabilities.php
- tests/phpunit/tests/user/slashes.php
Currently PHP 8.2 based GitHub tests are experimental. This PR aims to backport upstream fixes as found in [ticket 56033](https://core.trac.wordpress.org/ticket/56033) to resolve these issue.
This PR should allow removal of the `experimental` flag from the PHP 8.2 tests and we can formally support PHP 8.2
Local testing during backporting and merge now show 0 errors.
Will need to ensure GitHub tests are passing and removal of the PHP 8.2 experimental flag can also be implemented as part of this PR.
N/A
- Bug fix
> Fix: Test errors in PHP 8.2 tests

- Gruntfile.js
Images included at `wp-admin/images/` and `wp-includes/images/` are minified by a Grunt task.
This task uses [grunt-contrib-imagemin](https://www.npmjs.com/package/grunt-contrib-imagemin) and this task writes files even if there is now file size change.
On MacOS running `grunt precommit:image` results in many file changes (see screen grabs below. This means development on MacOS where `precommit` is needed creates images changes that should not occur.
A [PR](https://github.com/gruntjs/grunt-contrib-imagemin/pull/400) has been made upstream about 6 months ago but it seems that the project is poorly maintained or abandoned.
I cannot find a suitable alternative npm package so have created a platform conditional workaround that skips this step on all platforms except Linux.
Local Testing Only …
> Conditionally run `imagemin:core` on linux only

- src/wp-includes/class-wp-editor.php
WP-r56235: Editir: Fix open_basedir warnings on the classic Edit Post screen when additional TinyMCE plugins are used.
WP:Props: rembem, MadtownLems, njsamsatli, sabernhardt, azaozz.
Fixes: https://core.trac.wordpress.org/ticket/54354.
---
Merges https://core.trac.wordpress.org/changeset/56235 / WordPress/wordpress-develop@e77bf1ec99 to ClassicPress.
Local MAMP stack with `open_basedir` restrictions activated and `it_IT` locale.
- Bug fix
> WP-r56235: Editor: Fix open_basedir warnings on Edit Post screen

- src/wp-admin/import.php
- src/wp-admin/includes/import.php
At the moment, when a user wishes to import an exported WXR file, they are told that the default Import tool (WordPress Importer plugin) is incompatible with ClassicPress. But the latest version (0.8.2) is now compatible with ClassicPress v2.
Closes #1339.
I've left the default description used un WordPress because the tool is in the WP repo and it's not designed (even if it works) for ClassicPress.
- Bug fix
> Restore automatic installation for WordPress Import Tool

- src/wp-includes/media.php
Fix for #1223 
By default media upload date is not editable, but it can be edited with plugins like [Media Library Assistant](https://wordpress.org/plugins/media-library-assistant/)
This can create odd situations where the "Next" media has a date and time stamp before the "Previous" image, or voce versa.
Sorting media attachments by date rather than ID avoids this fringe issue.
Local testing with multiple images on one post in TwentySixteen theme after using the plugin mentioned above.
N/A
- Bug fix
> Order media by update date

- src/wp-includes/script-loader.php
In a current live site build of the 2.1-alpha core code I am seeing and there are other confirmed cases of console errors in browsers.
This only affects admin pages, and can by fixed by adding `define( 'CONCATENATE_SCRIPTS', false );` to `wp-config.php`
After some debugging this can be traced back to localisation in `wp-includes/script-loader.php` - throughout the code there is a change to iss if the 'init' hook has fired and we have missed that in one location.
Local testing and on my live sites where this has been seen. After applying the patch without a fresh build the browser cache will need a force refresh
N/A - errors are resolved.
- Bug fix
> Fix for admin console errors

- src/wp-includes/post.php
The hooks fire before the general delete_post / deleted_post hooks and have the same parameters.
Props benniledl, swissspidy, dargus.
- New feature
> WP-r57853: Add 2 hooks on deletion of a specific type of post.

- src/wp-includes/class-wp-http.php
- tests/phpunit/tests/http/cpDotNetUrls.php
Add a filter `cp_dot_net_urls` in class `WP_Http` to change the request URL if it's a `classicpress.net` one.
With this filter you can change the request URL.
For security purposes only hosts ending in `classicpress.net` can be filtered and only to a value that ends in `classicpress.net`. If a hooked function tries to filter the value in a different way a "Doing it wrong" is thrown and the URL is not changed.
Example:
```php
add_filter( 'cp_dot_net_urls',  'xsx_test_filter', 10, 2 );
function xsx_test_filter( $url, $parsed_args ) {
return preg_replace( '/directory\.classicpress\.net/', 'staging-directory.classicpress.net', $url );
}
```
This (as in the example) helps to switch requests to staging classicpress.net hosts.
- Local testing
- Unit tests
- New feature
> Add a filter to change classicpress.net urls in HTTP requests

- src/wp-includes/script-loader.php
In [this commit](https://github.com/ClassicPress/ClassicPress/commit/cdeb0f4c5251b4390b5bdced0c51bb273745a451)
`$scripts->add( 'iris', "/wp-admin/js/iris$suffix.js"...` was changed to `$scripts->add( 'iris', '/wp-admin/js/iris.min.js'` and that breaks customizer in `+dev` installations.
:question: I wonder also if it's right to have the minified `/wp-admin/js/iris.min.js` in the source.
This PR reverts the change,
> Fix customizer in `+dev` installations

- src/wp-activate.php
- src/wp-admin/post.php
- src/wp-includes/class-wp-recovery-mode-cookie-service.php
- src/wp-includes/comment.php
- src/wp-includes/option.php
- src/wp-includes/pluggable.php
- src/wp-login.php
Fixes #1227 
This change updated the usage of `setcookie()` in core so that the SameSite flag is set as Strict for settings cookies, this may help avoid some CSRF cookie exploits.
This fixes an open issue (#1227) and enhances cookie security.
Local and personal live site testing. Note below that the for right SameSite column now says Strict.
- Enhancement
> Update settings cookies to add SameSite and array structure

- src/wp-includes/PHPMailer/PHPMailer.php
- src/wp-includes/PHPMailer/SMTP.php
Update external PHPMialer library to v6.9.1
Release notes list following changes (among others):
- Add support for official release of PHP 8.3, add experimental support for PHP 8.4
- Add clearCustomHeader and replaceCustomHeader methods
- Add support for the XCLIENT SMTP extension with setSMTPXclientAttribute and getSMTPXclientAttributes methods
- Don't attempt opportunistic TLS when connecting to localhost
- Add package link and example showing how to use @decomplexity's [SendOauth2 wrapper](https://github.com/decomplexity/SendOauth2)
- Update example to show a better way of using an SMTP subclass
- Avoid some more deprecation warnings
Unit tests so far but would benefit from borader testing
N/A
- Library update
> Update PHPMailer to 6.9.1

- src/wp-admin/includes/dashboard.php
- src/wp-admin/update.php
This PR adds a dashboard widget informing about the new directory and let users install the plugin with one click.
To achieve this I've changed `src/wp-admin/update.php` to allow some plugin slug to bypass WP `plugins_api()` for certain slugs and point to ClassicPress Directory API.
Local tests.
- New feature
> Add Directory Plugin dashboard widget 

- src/wp-includes/version.php
From WordPress:
A cross-site scripting (XSS) vulnerability **affecting the Avatar block type**; reported by [John Blackbourn](https://johnblackbourn.com/) of the WordPress security team.
This vulnerability does not affect ClassicPress but this PR bumps `$wp_version` to 6.2.5 to stay in sync with upstream 6.2 branch.
> Bump `$wp_version` to 6.2.5

- src/wp-includes/canonical.php
- tests/phpunit/tests/canonical.php
Canonical: Limit post types searched by redirect_guess_404_permalink().
Limit the post types searched in redirect_guess_404_permalink() to public, searchable post types. This prevents redirects to 404 pages and the exposure of private post type slugs.
Props francescocarlucci, peterwilsoncc, rajinsharwar.
Fixes [WordPress Ticket 59795](https://core.trac.wordpress.org/ticket/59795).
Other notes on [ClassicPress Forum](https://forums.classicpress.net/t/vulnerability/5156/2).
> WP-r57645: Prevents the exposure of private post type slugs.

- src/wp-admin/js/post.js
This PR is to fix the bug reported at https://forums.classicpress.net/t/custom-taxonomies-dont-work/5163
The bug is isolated to the non-hierarchical taxonomies’ (i.e. like tags) metaboxes on the edit screen of a custom post type.
Metaboxes on regular posts, and hierarchical taxonomies (i.e. like categories) on any post type work fine. The bug also does not affect non-hierarchical taxonomies added via Quick Edit.
The cause is that, while the correct JavaScript file is being loaded, it is not being initiated. The reason for this is that the code looks for a `div` while, in version 2 of ClassicPress, we replaced a lot of old JavaScript with HTML5 disclosure widgets. So the bugfix here is simply to replace `div` with `details` on a specific line.
> Update post.js to fix bug in metaboxes created for custom non-hierarchical taxonomies

- src/wp-includes/general-template.php
This is a very simple addition, which just ensures that the right icon is presented for the Enter key on virtual keyboards. See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint. It's widely recognized: https://caniuse.com/?search=enterkeyhint
This PR is motivated by the fact that I have noticed that the icon for search is often incorrect on a virtual keyboard on my Android phone. This PR corrects it.
> Update general-template.php to add `enterkeyhint="search"` to search-form

- src/wp-admin/includes/export.php
- src/wp-includes/media.php
In PHP 8.4, declaring function or method parameters with a default value of `null` is deprecated if the type is not nullable.
PHP applications are recommended to ''explicitly'' declare the type as nullable. All type declarations that have a default value of `null`, but without declaring `null` in the type declaration, will emit a deprecation notice: {{{
function test( array $value = null ) {}
}}}
`Deprecated: Implicitly marking parameter $value as nullable is deprecated, the explicit nullable type must be used instead`
**Recommended Changes**
Change the implicit nullable type declaration to a nullable type declaration, available since PHP 7.1: {{{#!diff
- function test( string $test = null ) {}
+ function test( ?string $test = null ) {} }}}
This commit updates the affected instances in …
> WP-r58009: Fix implicit nullable parameter type deprecation on PHP 8.4

- src/wp-admin/edit-form-advanced.php
This PR addresses https://github.com/ClassicPress/ClassicPress/issues/1032
Note that attempting to save an empty post already results in the post not being published but saved as an auto-draft. The issue addressed by this PR is that a message appears, which inaccurately states that the post has been published. This PR replaces that with a warning that says: "You can't publish an empty post."
I'm not wedded to that text; I just took it from the Issue referred to above. If someone has a better suggestion, I'll be happy to go with that.
> Update edit-form-advanced.php to generate correct notice when attempting to publish empty post

- src/wp-includes/admin-bar.php
This PR implements the feature request in Issue https://github.com/ClassicPress/ClassicPress/issues/1062.
Note, however, that while some of the code used here is similar to that shown by one comment in that thread, that code is designed to show the status of `WP_DEBUG` on the public-facing pages of a site, which is the opposite of what the feature request called for.
Some admins might want not to see this. In such cases, it could be removed in the same way as any other item on the adminbar or simply hidden from view by a simple bit of CSS: `#wp-admin-bar-cp-debugging { display: none; }`
> Update admin-bar.php to display current status of `WP_DEBUG` in adminbar on admin screens

- src/wp-includes/comment-template.php
There is currently no easy way to modify the default CP comment form tag. I have a couple of sites where I need to be able to allow file uploads with the comment, but I have to resort to using an output buffer to grab the whole form, like this:
```
ob_start();
comment_form();
$form = ob_get_clean();
```
and then I have to unpack and fiddle with the `$form` variable.
This PR adds a filter that would enable attributes to be added to the form tag very easily with a function like this:
```
function my_comment_tag( $tag, $args ) {
return 'enctype="multipart/form-data"';
}
add_filter( 'comment_form_tag', 'my_comment_tag', 10, 2 );
```
This PR also corrects a misleading statement in the docblock immediately following the above change.
> Update comment-template.php to add a filter to the comment form tag

- src/wp-includes/theme.php
- tests/phpunit/tests/theme/support.php
When we made HTML5 the default output, we indicated that `add_theme_support( 'html5' )` was deprecated by using the `_doing_it_wrong()` function. This has caused quite a stir in the forum, because it suggests that there's something wrong with using the `add_theme_support()` function altogether.
That is not, in fact, true. We just used the wrong deprecation function. This PR fixes that by replacing `_doing_it_wrong()` with `_deprecated_argument()`. This also necessitates swapping the second and third arguments of the function. The message is also cleaned up to replace the space at the end of the line with a full stop. This now produces the much clearer message:
```
Function add_theme_support( 'html5' ) was called with an argument that is deprecated since version CP-2.0.0! HTML5 is the …
```
> Update theme.php to use correct deprecation function

- .github/workflows/phpunit-tests.yml
- tests/phpunit/includes/abstract-testcase.php
- tests/phpunit/includes/object-cache.php
During PHPUnit tests the PHP.net document repository is checked out. To save time and RAM we can make a shallower checkout.
May help prevent occasioanl Workflow run failures.
Unit tests will run, locally tested and download size reduced from `115.85 MiB` to `34.59 MiB` according to `git` command line.
- Bug fix
> Shallower checkout of PHP.net repository

- src/wp-admin/includes/translation-install.php
- src/wp-admin/includes/update-core.php
This PR updates the translation API endpoint URL.
It further extends the `wp_download_language_pack()` function to allow language packs to be installed and overwritten, and adds `maybe_upgrade_translations()` to the update code so new language packs can be installed during updates.
**This change is contingent on getting some language packs ready on the API before `2.1.0` is released.**
The ClassicPress implementation of languages is different than upstream. 
Local testing of the API and amended `wp_download_language_pack()` function.
The update process has not been tested but sould trigger in nightly builds to confirm it works.
N/A
- New feature
> Add new translation endpoint and update functionality

- src/wp-admin/includes/class-wp-site-health-auto-updates.php
As discussed at the weekly core review meeting on May 2, 2024, a Site Health check is misconfigured for the checksum API endpoint.
The test is potentially incorrect, the wrong URL could be constructed and the version number reported is WP.
Note, these tests only run if file system access is 'direct'. Can be tested locally by adding `define( 'FS_METHOD', 'direct' );` to `wp-config.php`.
Local testing
- Bug fix
> Use correct checksum endpoint in Site Health

- src/wp-admin/includes/update-core.php
Recent code changes to enable translation package updates on core upgrade have been reported on Zulip to cause errors such as `**Fatal error**: Uncaught Error: Call to undefined function maybe_upgrade_translations()`
This is not 100% re-producible and may be linked to server caching, this PR aims to invalidate caching for the file involved in the above error message as a potential fix for the error message.
Local testing but will need further testing on cache using servers once this change in in nightly builds.
N/A
- Bug fix
> Invalidate opcache file for translation-install.php

- .github/workflows/phpunit-tests.yml
- tests/phpunit/tests/query/results.php
This PR adds experimental PHPUnit tests to PHP 8.2 and 8.3 in combinations with MySQL8.
Currently all testing runs using MySQL 5.7, this is no longer under active development with minimal future support from developers.
https://www.mysql.com/news-and-events/web-seminars/migrating-from-mysql-5-7-to-mysql-8/
Testing therefore should be extended to more current and supported versions of MySQL to allow work on any failing tests.
Unit tests will run on this PR.
N/A
- New feature
> Add experimental MySQL Testing

- tests/qunit/index.html
- tests/qunit/wp-admin/js/widgets/test-media-image-widget.js
- tests/qunit/wp-admin/js/widgets/test-media-video-widget.js
- tests/qunit/wp-includes/js/tinymce/plugins/wptextpattern/plugin.js
A recent Sinon update (17.0.2) surfaced some testing issues, the major problems were resolved with the release of Sinon-Test 3.6.1 and Sinon 18, however, while investigating the issues it was noted that 2 QUnit tests never execute.
These tests have been made functional in this PR:
- a new template section has been added to `index.html`
- the `clock()` feature in Sinon is used to ensure the tests execute
- testing is updated to assert 2 tests are expected to avoid such issues arising again
- tests are updated to check the more modern HTML implementation
- layout in anohter test file using `setTimeout` has been improved as an aside
Local testing of QUnit tests in a browser and on command line in both `local` and `compiled` states. Note in the screen shots below the same number of tests run …
> Fix for QUnit skipped tests

- src/wp-admin/includes/post.php
- src/wp-includes/post.php
- tests/phpunit/tests/admin/includesPost.php
Backport of:
- https://core.trac.wordpress.org/changeset/58175
- https://core.trac.wordpress.org/changeset/58174
The post editor uses the permalink_template property from the posts REST API to render the post slug input or not. For auto-drafts or newly created posts, this property was not set properly. This PR solves by fixing the get_sample_permalink function used to compute this property.
WP:Props youknowriad, mcsf, antonvlasenko, azaozz, peterwilsoncc, andrewserong, hellofromTonya, spacedmonkey.
Fixes https://core.trac.wordpress.org/ticket/59283.
- Bug fix
> WP-r58174: Fix get_sample_permalink to return the right permalink 

- tests/phpunit/tests/kses.php
WP-r57861: Tests: Remove unnecessary use of `utf8_encode()` in KSES tests.
One of the tests for the `wp_kses_xml_named_entities()` function used `utf8_encode( chr( 160 ) )` to set an expectation of a Unicode character for a non-breaking space.
It is understandable that this expectation was previously set this way, as it is not possible for a developer to distinguish between a ''breaking'' space and a ''non-breaking'' space visually, so the chances of the test accidentally breaking on an incorrect save when the plain Unicode character would be used, was high.
However, the `utf8_encode()` function is deprecated as of PHP 8.2, and its use needs to be removed from the WP codebase.
PHP 7.0 has introduced [https://wiki.php.net/rfc/unicode_escape Unicode escape sequences], which allows to create …
> Remove unnecessary use of `utf8_encode()` in KSES tests

- tests/phpunit/tests/rest-api/rest-schema-setup.php
Since the introduction in core of Media Categories there is some strange behaviour when running PHP unit tests.
Running `composer run phpunit -- --group=restapi` will produce changes in the `tests/qunit/fixtures/wp-api-generated.js` file with changes to the ID used. Thisis viewable using `git diff` locally.
Running `composer run phpunit -- --group=restapi-jsclient` after the above step will revert these changes.
On investigation, it seems that adding to the expected `$fixture_replacements` variable in `tests/phpunit/tests/rest-api/rest-schema-setup.php` resolves this issue such that running all PHPUnit tests of the one aimed at testing the REST-API will not result in changes to that generated file.
This may explain why a `grunt precommit` was needed on the original …
> Add $fixture_replacements for media categories

- src/wp-admin/includes/class-wp-plugin-install-list-table.php
- src/wp-admin/includes/class-wp-plugins-list-table.php
- src/wp-admin/includes/theme.php
- src/wp-admin/includes/update.php
- src/wp-admin/theme-install.php
- src/wp-admin/themes.php
- src/wp-admin/update-core.php
- src/wp-includes/customize/class-wp-customize-theme-control.php
See #1441 .
Closes #1441 
Plugin and themes that contains `Requires at least` are checked against `$wp_version`.
At now that is `6.2.5`, but users running the latest version of ClassicPress are anyway prompted to update.
Local testing.
- Bug fix
> Fix: prompt to update core for incompatible plugins and themes

- src/wp-admin/includes/update-core.php
This change lists ~~the ClassicPress child 2017 theme and~~ the newly create ClassicPress theme so they should be installed on updates.
Fixes reported issue in 2.1.0 launch that the new theme is not being installed.
Will be testing with nightly build updates.
N/A
- New feature
> List ClassicPress theme in `$_new_bundled_files`

- src/wp-admin/setup-config.php
When installing a new site the defaul table prefix is still `wp_`.
For branding we should change that to `cp_`.
Local testing
##
- Bug fix
> Use cp_ table prefix for new installs

- src/wp-includes/update.php
As reports on the chat channel, sites may fail to detect updates are available for core if there are many translations installed.
The URL for checking updates may deliver a 414 response when large amounts of data are added to the update URL as a query parameter.
`[response] => Array ( [code] => 414 [message] => Request-URI Too Long )`
This results in no update being served. The translation data are not used on the API, and this doesn't happen upstream as this same data is posted.
Tested and confirmed by OP on chat channel.
- Bug fix
> Remove translation data from update url query

- src/wp-admin/admin.php
- src/wp-admin/includes/upgrade.php
- src/wp-admin/upgrade.php
- src/wp-includes/version.php
When a change in the database schema or in the options is needed, WordPress uses `$wp_db_version` to trigger those updates.
Even if the same variable could be used, it would be better to introduce one specific to ClassicPress.
The new `$cp_db_version` located in `src/wp-includes/version.php` can be incremented to trigger an automatic update of the database if `src/wp-admin/includes/schema.php` changes. Can also trigger a new specific function to update options or else.
Initial proposed value is 20200, where 2 is major, 02 is minor and 00 is patch of the version that introduce changes.
- Check out the PR
- Play with `$cp_db_version` value
- Delete `cp_db_version` option (`wp option delete cp_db_version`)
- New feature
> Add our own database version to handle updates

- src/wp-admin/about.php
- src/wp-includes/formatting.php
- src/wp-includes/functions.php
- src/wp-includes/version.php
Grouped backport of changes made upstream in WordPress 6.2.6 consistent with `6.5.5`
Security enhancements and associated version and about changes.
Local tests passing, backport
N/A
- Bug fix
> Upstream security enhancements - changeset 58479

- .github/workflows/coding-standards.yml
- .github/workflows/php-compatibility.yml
Update `ramsey/composer-install` to version 3 in GitHub actions
Version update in action should remove warnings in GitHub actions.
PR tests will run.
This PR should remove these warnings:
- Bug fix
> Update `ramsey/composer-install` to v3

- src/wp-admin/about.php
In the admin `about.php` page there is a list of WordPress backported versions where security changes have been adopted, I noticed the layout was a bit off and tracked this to some malformed paragraph tags.
Consistent layout styling creates a better user impression and we should use syntactically correct HTML. Notice the alignments of version numbers below.
Local testing, see screen shots below.
- Bug fix
> Fix HTML paragraphs for backport information

- src/wp-admin/js/plugin-install.js
Pressing help in various "plugin" screens this error shows up in console.
In #1487 this was noticed with the "Debug Bar" plugin installed, but on my local installation it also appears without that plugin.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'remove')
at HTMLDocument.<anonymous> (plugin-install.js?ver=cp_679f8e:95:16)
```
Local testing. After this change the console has no errors.
- Bug fix
> Fix JS error when esc is pressed in plugin pages

- src/wp-includes/functions.php
- tests/phpunit/tests/functions/wpDeleteFile.php
Backport of https://core.trac.wordpress.org/changeset/58715
This addresses a discrepancy where using `unlink()` allows for checking if it was successful via the return value, but `wp_delete_file()` did not have a return value, making it impossible to verify the result without doing overhead checks if the file still exists.
This also brings more consistency with the other `wp_delete_*()` functions.
Unit tests were added in upstream.
- New feature
> WP-r58715: Filesystem API: Add a return value for `wp_delete_file()`

- src/wp-includes/classicpress/class-wp-compat.php
- tests/phpunit/tests/compat/wordpress.php
Since 3.16.4 Query Monitor [removes back-compat code for pre WordPress 5.0](https://github.com/johnbillion/query-monitor/commit/10eedafd54f858d74f3165d2cffd35770a116633).
This triggers a fatal error that renders Query Monitor unusable on some screens.
This PR adds polyfills for:
- `parse_blocks`
- `get_dynamic_block_names`
Restore Query Monitor and maybe other plugins functionality.
Local testing.
Unit tests for new polyfills.
- New feature
> Add two polyfills to fix Query Monitor

- Gruntfile.js
- package-lock.json
- package.json
This PR updates CSS dependency from `node-sass` to `sass`. The former is no longer supported or developed:
https://www.npmjs.com/package/node-sass
`sass` is recommended as a suitable alternative.
Fixes #782 
This PR is based on upstream changes here:
https://core.trac.wordpress.org/changeset/50126
Local testing and also run of `bin/compare-build-branch.sh update/sass` after creating the branch.
This does show some differences however these are line spacing and input selector syntax quotes and the changes all appear to match output used upstream.
N/A
- Dependency update
> Update from `node-sass` to `sass`

- src/wp-admin/css/common.css
This PR is designed to address the issues noted at https://forums.classicpress.net/t/summary-marker-is-too-big/5331/7.
The marker is set to a size of `1.3em` and container queries (and a negative right margin) are added to ensure that the up and down buttons are kept close to the right edge of the bounding `summary` element.
I have tested this in Firefox and Web (a Safari clone) on Linux.
Screenshots below demonstrate the improvement (ignore the background color, which just reflects the different sites used for the comparison).
Before:
After:
> Improve CSS on Post Edit and Dashboard Screens

- src/wp-admin/js/image-edit.js
This is a simple bugfix to ensure that focus works as expected when hitting the Edit Image button within the Media Item modal on the Media Grid page. It simply replaces a check for `length` (which isn't working) with a check for `null` (which does). It also significantly shortens the list of potential tabbable items to reflect the fact that they are, in fact, all buttons.
As the image below shows, the `Crop` button (or whichever button is the first not to be disabled) now gets focus, whereas it did not before.
> Bugfix for focus within Edit Image modal

- src/wp-admin/includes/schema.php
- src/wp-admin/options-general.php
- src/wp-admin/options.php
- src/wp-includes/formatting.php
- src/wp-includes/general-template.php
- src/xmlrpc.php
Add a new option (`disable_xml_rpc`), default `0` that can be toggled from Settings > General menu.
See https://github.com/ClassicPress/ClassicPress/issues/1034
Local testing.
- New feature
> Add option in General Options to disable XML-RPC

- .github/workflows/php-compatibility.yml
- .github/workflows/phpunit-tests.yml
- composer.json
Add PHPUnit  as a specific developer dependency and clean the workflow test action of a subsequently unnecessary step of unit testing.
PHPUnit is currently at version 11, but versions 10 and 11 are unsupported in current unit tests.
An upstream ticket details the issues that need addressing to use newer versions of PHPUnit:
https://core.trac.wordpress.org/ticket/62004
Local testing and GitHub actions will run for the amended testing on this branch.
N/A
- Bug fix
> Add PHPUnit 9 as developer dependency

- .github/workflows/phpunit-tests.yml
PHP 8.4 is due for full release and is currently in release candidate for testing.
This replaces #1572 to keep fixes for PHP8.4 for later.
This PR adds PHP 8.4 to the suite of PHPUnit testing as `experimental` so any issues can be identified and corrected.
Unit tests will run on GitHub
N/A
- New feature
> Add unit testing for PHP 8.4

- src/wp-admin/includes/class-wp-privacy-policy-content.php
Change a "WordPress" occurrence with "ClassicPress" on the Privacy Policy Guide page. "WordPress" should not be present here, as this page is about ClassicPress and ClassicPress privacy and additional plugins.
Keeping "WordPress" makes sense, as one can have both WordPress and ClassicPress plugins, but it makes the guide confusing, and also invalid long-term, when WordPress plugins might not be compatible with ClassicPress.
- Bug fix (branding/typo)
> Change a "WordPress" occurrence with "ClassicPress" on the Privacy Policy Guide page

- bin/check-release-files.pl
A couple of changes in ClassicPress v2.2.0 resulted in issues in the release process linked to the `bin/check-release-files.pl` file. This PR aims to address these issues ready for future releases.
It will remove errors encountered in the release process 
On this branch run the follow commands in order:
```
grunt build
cd build
cp -vaR ../.git ./
git status
git add .
git commit -m 'Test'
../bin/check-release-files.pl
```
The output should be `Release files look OK`.
On current `develop` the output will be something like:
```
--- only in src/
+++ only in build/
+ wp-includes/js/tinymce/wp-tinymce.min.js
Unexpected file(s) added to and/or removed from build!
```
N/A
- Bug fix
> Update file list for release checks

- src/wp-includes/object-relationships.php
Fixes the issues mentioned at https://forums.classicpress.net/t/please-use-placeholders-in-translation-strings/5438 about strings in the `~/wp-includes/object-relationships.php` file by using placeholders.
> Update object-relationships.php to use placeholders in translatable strings

- src/wp-admin/includes/schema.php
See #1552 .
In 2.2.0 `$cp_db_version` was introduced.
But for new installations it needs also to be in `schema.php`
- Bug fix
> Populate cp_db_version on new installations

- Gruntfile.js
- package-lock.json
- package.json
- src/wp-admin/css/colors/_admin.scss
- src/wp-admin/css/colors/_mixins.scss
- src/wp-admin/css/colors/_variables.scss
- src/wp-admin/css/colors/blue/colors.scss
- src/wp-admin/css/colors/coffee/colors.scss
- src/wp-admin/css/colors/ectoplasm/colors.scss
- src/wp-admin/css/colors/light/colors.scss
- src/wp-admin/css/colors/midnight/colors.scss
- src/wp-admin/css/colors/modern/colors.scss
- src/wp-admin/css/colors/ocean/colors.scss
- src/wp-admin/css/colors/sunrise/colors.scss
Recent updates to `SASS` have resulted in deprecation notices during the build process. This PR aims to address these notices.
Broadly there are scss syntax changes for `SASS` due to deprecation of `lighten()`, `darken()` and `hue()` but these are all relatively easily replaced.
The API is also deprecated and this is [reported](https://github.com/sindresorhus/grunt-sass/issues/311) in an upstream dependency - for now the warning can be silenced in `Gruntfile.js`.
More modern `scss` files, quieter command line reporting during builds
Local testing and comparison of output `css` shows near identical output, there are 2 minor changes: as listed below but visually I could not see any differences in admin pages.
```
diff -r ../build/wp-admin/css/current-colors/ectoplasm/colors.css …
```
> Update SCSS files for SASS 1.79.x

- .github/workflows/phpunit-tests.yml
- src/readme.html
- tests/phpunit/includes/abstract-testcase.php
- tests/phpunit/tests/external-http/basic.php
The readme.html file recommends PHP 8.0 or greater. Since ClassicPress 2.1.0 PHP 8.2 and 8.3 are fully supported. And since PHP no longer supports PHP 8.0 the readme file needs updating.
Further, the tests of the readme file happen on every new pull request, since these tests require accessing remote URLs this is prone to being slow and breaking.
- Update readme.html with supported and more secure recommendations for implemented PHP version.
- Reduce testing overhead and errors
Local testing still works and passes, these tests should now be skipped on PR tests.
Local run of `composer run phpunit -- --group=external-http` returns:
- Enhancement
> Update readme.html and supported version tests

- src/wp-admin/css/revisions.css
This fixes the broken range input control on non-Revision screens, such as theme or plugin settings pages.
Whenever am `<input type="range">` element is added to a theme or plugin settings page, it looks broken because it inherits the styles from the Revisions screen. The range input control styles should be isolated to the Revisions screen only, and appear as a native element on all the other screens.
**Revisions screen**
**A theme settings screen (before)**
**A theme settings screen (after)**
> Only style the range input control on the Revision screen

- src/wp-admin/js/common.js
When using the Customizer, one of the files called is `~wp-admin/js/common.js`, which is also called in the back-end. In the Customizer, this produces the following error:
That's because the `$adminmenu` variable is, naturally enough, accessible only in the back-end.
This PR adds a check to see whether the file `~wp-admin/js/common.js` is being called on the back-end or in the Customizer. In the latter, it now sets the JS variable, `topMenuItems`, to an empty array. (It's an array rather than a string because the code that uses it runs a `forEach` loop.) This eliminates the current error.
> Eliminate error when using Customizer

- src/wp-admin/includes/image-edit.php
- src/wp-admin/js/image-edit.js
- tests/phpunit/tests/ajax/wpAjaxImageEditor.php
Fixes an error in which the file size meta data retained the original upload's values follow a user editing the images in the media screen.
The original images' file sizes are now stored in the backup image data to allow for them to be restored when a user restores the original image.
WP:Props ankit-k-gupta, antpb, audrasjb, chaion07, gauravsingh7, joedolson, oglekler, pls78, rajinsharwar, sayedulsayem, vertisoft. 
Fixes https://core.trac.wordpress.org/ticket/59684.
Unit tests and locally cropping an image.
- Bug fix
> WP-r59202: Update file size meta data when editing images.

- src/wp-admin/js/customize-nav-menus.js
- src/wp-admin/js/customize-widgets.js
- src/wp-admin/js/gallery.js
- src/wp-admin/js/nav-menu.js
- src/wp-admin/js/postbox.js
- src/wp-admin/js/widgets.js
When we transitioned from using the jQuery UI `sortable` module to `SortableJS`, we included a polyfill (labeled `forceFallback`) for Safari, because that browser had a bug which meant that it did not implement HTML5 drag and drop properly.
Recent testing shows that that bug in Safari has now been fixed, and that the polyfill is now counter-productive. See https://forums.classicpress.net/t/unable-to-move-menu-items-after-migrate-from-wp/5457 and https://forums.classicpress.net/t/screen-elements-shifted-to-rh-sidebar/5479.
Removing the `forceFallback`s makes things work properly on Safari, as testing reported at the end of the first thread above confirms. That's what this PR accomplishes.
> Remove Safari fallbacks from SortableJS

- src/wp-includes/pluggable.php
- src/wp-login.php
This fixes a PHP error encountered when resetting passwords, something like this:
`Undefined variable $secure in /var/www/vhosts/URL/httpdocs/wp-login.php on line 873`
Cookie should be correctly set and errors avoided.
Local testing
N/A
- Bug fix
> Fix for PHP error for password reset cookie

- src/wp-admin/upload.php
When the new Media Library grid is displayed, background images are supplied for non-image files:
But when a faceted search is made using one of the dropdown select filters or the search box, no such backgrounds are seen:
This PR remedies that:
> Enable background images for non-image files in AJAX call in new Media Library grid display

- tests/phpunit/tests/http/http.php
Recently failing PHPUnit tests are due to a website having registered a URL presumed not to exist for testing purposes.
Issue also reported [upstream](https://core.trac.wordpress.org/ticket/62307) to WordPress.
This fix amends the URL to one that does not resolve again and therefore restores testing functionality.
Local testing works and GitHub Actions on this test should now pass.
- Bug fix
> Change to non-resolving URL for tests

- .github/workflows/phpunit-tests.yml
- tests/phpunit/tests/http/http.php
PHP 8.4 tests are running as standard, the definition to run the additional test as `experimental` can now be removed.
Experimental tests no longer needed and this also reduced the number of tests GitHub runs.
GitHub actions will run.
N/A
- Bug fix
> Remove experimental PHP 8.4 test

- src/wp-includes/link-template.php
- tests/phpunit/tests/link.php
- tests/phpunit/tests/link/getPagenumLink.php
Previously, a trailing slash was appended to the link returned from `get_pagenum_link()`. If the permalink structure didn't contain a trailing slash, this link could fail.
This change removes trailing slashes and only appends one if the site is set for adding trailing slashes.
This adds a new test file for the accompanying tests, `tests/phpunit/tests/link/getPagenumLink.php`, and moves an existing test for `get_pagenum_link()` to the same file.
WP:Props davemad-davenet, darkfate, Nazgul, scribu, nacin, obenland, chriscct7, jesin, matthewppelsheimer, audrasjb, petitphp, mukesh27, oglekler, mai21, webtechpooja, tejwanihemant, nicolefurlan, hellofromTonya, costdev. Fixes https://core.trac.wordpress.org/ticket/2877.
CP:Props KTS915
---
Merges https://core.trac.wordpress.org/changeset/56939 / …
> WP-r56939: Don't force trailing slash in `get_pagenum_link()`

- src/wp-includes/PHPMailer/Exception.php
- src/wp-includes/PHPMailer/PHPMailer.php
- src/wp-includes/PHPMailer/SMTP.php
This PR is a backport and updates PHPMailer to vesrion 6.9.2, this is a maintenance update.
WP-r59246: External Libraries: Upgrade PHPMailer to version 6.9.2.
This is a maintenance release with minor bug fixes.
References:
* [https://github.com/PHPMailer/PHPMailer/releases/tag/v6.9.2 PHPMailer 6.9.2 release notes]
* [https://github.com/PHPMailer/PHPMailer/compare/v6.9.1...v6.9.2 Full list of changes in PHPMailer 6.9.2]
Follow-up to https://core.trac.wordpress.org/changeset/50628, https://core.trac.wordpress.org/changeset/50799, https://core.trac.wordpress.org/changeset/51169, https://core.trac.wordpress.org/changeset/51634, https://core.trac.wordpress.org/changeset/51635, https://core.trac.wordpress.org/changeset/52252, https://core.trac.wordpress.org/changeset/52749, …
> Upgrade PHPMailer to version 6.9.2

- src/wp-includes/Requests/src/Autoload.php
- src/wp-includes/Requests/src/Capability.php
- src/wp-includes/Requests/src/Cookie.php
- src/wp-includes/Requests/src/Cookie/Jar.php
- src/wp-includes/Requests/src/IdnaEncoder.php
- src/wp-includes/Requests/src/Iri.php
- src/wp-includes/Requests/src/Requests.php
- src/wp-includes/Requests/src/Response.php
- src/wp-includes/Requests/src/Response/Headers.php
- src/wp-includes/Requests/src/Transport/Curl.php
- src/wp-includes/Requests/src/Transport/Fsockopen.php
- src/wp-includes/Requests/src/Utility/CaseInsensitiveDictionary.php
- src/wp-includes/Requests/src/Utility/FilteredIterator.php
- src/wp-includes/class-requests.php
- tests/phpunit/tests/http/includeOldRequestsClass.php
This PR replaced PR #1599 
The Requests library needs updating to at least 2.0.9 to avoid the cURL errors previously noted.
This PR includes incremental updates to move Requests to 2.0.11 and should also therefore fix a deprecation notice seen in PHP 8.4 testing
Fix cURL error and PHP 8.4 notice
Local testing and awaiting unit tests.
Note below the Deprecation notice is resolved.
- Bug fix
> Update the Requests library to version 2.0.11

- src/wp-admin/includes/ajax-actions.php
- src/wp-admin/upload.php
- src/wp-includes/js/media-grid.js
In the Media Library grid view, as merged into the ClassicPress nightly version, it's possible to select specific attributes of the media from three dropdowns  (according to file type, month, and media category), as well as by searching, in order to generate a grid of matching media via AJAX. 
Independently, it's also possible to use the pagination feature. But this causes a page reload, which causes the parameters to be lost and so always calls ALL the media.
This may be problematic on sites that have a large number of media files that match a given type, month, or media category. If that number exceeds the number of items per page selected in the Screen Options, there is no way to see the media files above that number without resorting to pagination, which then shows all the media …
> Ajax pagination in the new Media Library grid view

- src/wp-admin/css/colors/_admin.scss
- src/wp-admin/css/colors/_mixins.scss
- src/wp-admin/css/colors/_variables.scss
- src/wp-admin/css/colors/blue/colors.scss
- src/wp-admin/css/colors/coffee/colors.scss
- src/wp-admin/css/colors/ectoplasm/colors.scss
- src/wp-admin/css/colors/light/colors.scss
- src/wp-admin/css/colors/midnight/colors.scss
- src/wp-admin/css/colors/modern/colors.scss
- src/wp-admin/css/colors/ocean/colors.scss
- src/wp-admin/css/colors/sunrise/colors.scss
Recent updates to the SASS dependency (see #1597 and #1594) have started to display deprecation notices durung the `grunt sass:colors` build step.
This PR aims to address these notices by modernising and updating the scss files, rather than simply silence the warnings.
Cleaner build output.
Local testing and comparison of built files.
To compare before and after, on `develop` run `grunt sass:colors` and note the deprecation notices. Repeat that on this PR and see clean output.
To compare the built CSS before and after, use the following series of commands to build the current CSS, rename the folder in `build/`, build the CSS from the new file and then compare them. The final command should report nothing:
```
git checkout develop 
grunt sass:colors
mv build/wp-admin/css/colors …
```
> Modernise scss structure

- Gruntfile.js
- src/wp-includes/script-loader.php
Fixes #1618 
This change minified the FilePond JS and CSS files during the build process and amends loading in `script-loader.php` to use the minified files on production installations.
Fixes open issue and should reduce file load size.
Looking at current `script-loader.php` file it seems minified CSS files are expected so this may also fix a 404 error in the file uploader.
Would benefit from manual testing. Minifoed file creation confirmed on local check.
- Bug fix
> Minify filepond JS and CSS during build

- src/wp-admin/css/media-grid.css
When selecting an item in the new Media Library grid view, the delete attachment button (yes, it's a button, though it looks like a link) in the bottom right has turned blue instead of red:
This is caused by another CSS selector overriding the one for this button. This PR addresses that by increasing the specificity of the selector by changing the first part from a class to an ID, so that the button is now back to being red:
> Update media-grid.css to change selector from class to ID

- src/wp-admin/upload.php
- src/wp-includes/js/media-grid.js
In the new Media Library grid view, there are some errors when no media files have been uploaded:
-    PHP warnings in wp-admin/upload.php line 544: Undefined variable `$author_link` and Undefined variable `$author`.
-    JavaScript error in media-grid.min.js: `Uncaught TypeError: dateFilter is null`. (This one occurs because the relevant dropdown only shows if there are are uploaded media files.)
This PR addresses these issues by (a) setting `$author_link` and `$author` to empty strings if they are not defined elsewhere, and by checking for the presence of the `dateFilter` dropdown before adding a listener to it.
> Bugs when no media files have been uploaded

- src/wp-admin/css/media.css
When going to the media grid view and selecting a file, a modal dialog box opens, but it's missing the controls on the right. (This also causes the image and the details in the right-hand column to be pushed up too high.)
It's hard to show what's missing, but this PR simply deletes one line of CSS, so that the controls are back again, as below:
EDIT: Now also taken the opportunity to remove several more lines of CSS that are made obsolete by the original commit.
> Update media.css to address a regression

- src/wp-includes/js/media-grid.js
Similar to #1619, if `mediaCatSelect` is not in the DOM, images cannot be edited in Grid view.
My local editor set up has also trimmed some training white space in the affect file.
This PR applies a similar fix to that used in #1619 and testing on my live site where I don't use a media category, this restores image editing capability.
Testng on a site without a media category.
No point posting a cean console.
- Bug fix
> Fix console error when `mediaCatSelect` is undefined

- src/wp-admin/js/widgets.js
After the commits for the Custom HTML and Text widgets were merged, @xxsimoxx and I have seen instances where adding and sorting of widgets became impossible. That's because the title input of each widget input was not always instantiated first, which is required for the sorting functionality. This PR simply adds a check to ensure that the title input exists before attempting to sort.
> Bugfix: ensure widget title input instantiated before attempting to sort

- src/wp-admin/includes/schema.php
Change schema to default to an empty string for the option `ping_sites`, resulting in an empty "Update Services" list in "writing options" for new installations.
Discussion on the forum thread "[Removal of Ping-o-Matic?](https://forums.classicpress.net/t/removal-of-ping-o-matic/5604)"
New install.
> Empty "Update Services" list in writing options for new installations

- src/wp-admin/js/common.js
In PR #1590, we fixed an error message that indicated that the admin menu was undefined on the front-end. At the time, adding a conditional to check we're on an admin page seemed sufficient. But a related error message also appears after clicking on View Details for any plugin on the `plugins.php` page.
That's a minor thing. Unfortunately, Issue #1654 seems to be caused by the same problem. That issue is that, on the `update-core.php` page, clicking `Show Details` has no effect. In my own testing, it seems that that's because this bug occurs before the JavaScript for the `Show Details` link. Since JS is single-threaded, it means that the relevant code never runs.
This PR fixes the bug by adding a second thing to check for, namely `$adminmenu[0]`. (I tried just `$adminmenu`, but that …
> Fix "Show Details" button in admin Updates page

- src/wp-admin/upload.php
The current media grid view data attribute for filename incorrectly uses `name` instead of `filename`. I suspect this is a regression introduced by accident. This produces weirdly long strings. This PR corrects that by using `filename`.
> Correct a data attribute in the media grid view

- src/wp-includes/classicpress/class-wp-compat.php
- tests/phpunit/tests/compat/wordpress.php
Add polyfill for `get_block_theme_folders()` function and the relative check in PHPUnit.
Starting from version 3.17.0 [Query Monitor](https://wordpress.org/plugins/query-monitor/) uses the function and is unusable in the frontend.
Local testing and unit tests.
- New feature
> Add polyfill for get_block_theme_folders()

- Gruntfile.js
During the release of `v2.3.0` there was a minor issue whereby the `pepper.php` file was copied over from testing in `src/` to `build/`. This file is created by the ClassicPress Pepper plugin and should not be copied into builds.
Ensure local pepper keys are not inadvertently revealed and make a smoother release process.
Local build testing ensuring any `pepper.php` file in the plugin folder structure is not coped to `build/`.
N/A
- Bug fix
> Ensure `pepper.php` plugin file is not included in builds

- src/wp-includes/PHPMailer/PHPMailer.php
- src/wp-includes/PHPMailer/SMTP.php
This is a maintenance release, adding support for the release version of PHP 8.4, and experimental support for PHP 8.5.
References:
* [https://github.com/PHPMailer/PHPMailer/releases/tag/v6.9.3 PHPMailer 6.9.3 release notes]
* [https://github.com/PHPMailer/PHPMailer/compare/v6.9.2...v6.9.3 Full list of changes in PHPMailer 6.9.3]
Follow-up to https://core.trac.wordpress.org/changeset/50628, https://core.trac.wordpress.org/changeset/50799, https://core.trac.wordpress.org/changeset/51169, https://core.trac.wordpress.org/changeset/51634, https://core.trac.wordpress.org/changeset/51635, https://core.trac.wordpress.org/changeset/52252, https://core.trac.wordpress.org/changeset/52749, https://core.trac.wordpress.org/changeset/52811, https://core.trac.wordpress.org/changeset/53500, …
> Upgrade PHPMailer to version 6.9.3.

- src/wp-admin/options-general.php
Backport of https://core.trac.wordpress.org/changeset/59475.
This gives users another option when selecting how dates are displayed on their site. This change is relevant for better localization, providing more date format choices for users in regions where this format is common.
The `array_unique()` call ensures that if this format was already added by a plugin or theme, it won't be duplicated.
Follow-up to https://core.trac.wordpress.org/changeset/9131, https://core.trac.wordpress.org/changeset/22299, https://core.trac.wordpress.org/changeset/28820, https://core.trac.wordpress.org/changeset/28848.
WP:Props Daedalon, pbearne, fierevere, im3dabasia1, SergeyBiryukov. 
Fixes https://core.trac.wordpress.org/ticket/55685.
---
Merges https://core.trac.wordpress.org/changeset/59475 / …
> Add `d.m.Y` to date format presets on General Settings screen

- src/wp-admin/css/edit.css
This PR adds back a few lines of CSS previously removed so that, if enabled, the headings in the Links Manager are correctly aligned.
To get the Link Manager to disp[lay on the admin menu, install and activate the Link Manager plugin: https://wordpress.org/plugins/link-manager/
Now go to Add New. The headings are misaligned:
With these lines restored, the headings are aligned correctly:
I have actually never used the Link Manager and didn't realize it still existed. But it does. The above plugin contains just one line of code to turn it on. The issue was initially reported — and fix provided — on the forums at https://forums.classicpress.net/t/default-link-manager-layout-issue/5705
> Align headings in Link Manager correctly

- src/wp-admin/includes/class-wp-privacy-requests-table.php
- src/wp-admin/includes/class-wp-site-health-auto-updates.php
- src/wp-includes/class-wp-comment.php
- src/wp-includes/class-wp-query.php
- src/wp-includes/class-wp-recovery-mode.php
- src/wp-includes/class-wp-widget.php
- src/wp-includes/formatting.php
- src/wp-includes/ms-functions.php
- src/wp-includes/option.php
- src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php
- src/xmlrpc.php
This is a grouped set of backports that correct issues found and patched upstream by the static code analysis tool - [PHPStan](https://phpstan.org).
More efficient code base.
Some of the commits listed on the Ticket are either not required or will required deeper changes backporting other changes first.
https://core.trac.wordpress.org/ticket/52217
These are backports of upstream commits.
Local tests passing on completed PR.
N/A
- Code enhancement
> Grouped backport of PHPStan fixes

- src/wp-includes/class-walker-comment.php
- tests/phpunit/tests/comment/cpWalker.php
This PR fixes #1645 
It reintrodyced the `comment` function to the `Comment_Walker` class as a wrapper for the `html5_comment` function.
Backwards compatibility
Fixes #1645
Includes a new unit test
OP offered to test also so that would be very useful.
N/A
- Bug fix
> Restore Comment_Walker::comment function

- src/wp-admin/options.php
Add "Copy" button to "All Settings" screen (`wp-admin/options.php`) to copy the content of the option.
If the option is serialized a `var_dump` of the option will be copied.
While allowing the user to modify serialized options is risky, allowing them to copy their contents offers the possibility of extracting data from these options.
Without the ability to see serialized options this screen loses some of its usefulness.
Local testing.
- New feature
> Add "Copy" button to "All Settings" screen 

- src/license.txt
PHPUnit tests will fail until the copyright year is updated in `src/license.txt`
Fix for Unit Testing
Local testing with`composer run phpunit -- --group=basic`, this PR should pass on GitHub.
- Bug fix
> Update copyright year in license.txt

- src/wp-includes/class-wp-query.php
WP-r55558: Date / Time: Remove usage of mysql2date in generate_postdata method.
Remove usage of `mysql2date` in `generate_postdata`. `mysql2date` has a performance overhead, as it creates a `DateTimeZone` object each time it is called. Use a simple sub string function to generate the values needed for the `currentmonth` and `currentday` global variables.
WP:Props spacedmonkey, Rarst, SergeyBiryukov, flixos90. Fixes https://core.trac.wordpress.org/ticket/57683.
---
Merges https://core.trac.wordpress.org/changeset/55558 / WordPress/wordpress-develop@1eba58d5a6 to ClassicPress.
Partially fixes #1608 
Backport
N/A
- Performance enhancement
> Remove usage of mysql2date in generate_postdata method

- src/wp-includes/post.php
- tests/phpunit/tests/post/getPages.php
WP-r55569: Posts, Post Types: Use WP_Query internally in get_pages.
Convert get_pages to use WP_Query internally. Using WP_Query means that a lot of code has been removed however existing parameters supported by get_pages are transformed in to query arguments. The custom caching solution found in the old version of this function is replaced with the caching found in WP_Query (added in [[53941]](https://core.trac.wordpress.org/changeset/53941)). This change adds consistency to the codebase, as improvements and changes to WP_Query will filter down to the get_pages function.
WP:Props mikeschinkel, spacedmonkey, nacin, scribu, filosofo, jane, garyc40, markoheijnen, grandslambert, kevinB, wlindley, dbernar1, atimmer, mdawaffe, helen, benjibee, johnbillion, peterwilsoncc, costdev, flixos90, …
> Use WP_Query internally in get_pages

- src/wp-includes/class-wp-textdomain-registry.php
- src/wp-includes/l10n.php
- tests/phpunit/tests/l10n/loadTextdomainJustInTime.php
- tests/phpunit/tests/l10n/wpLocaleSwitcher.php
WP-r55865: I18N: Improve `_load_textdomain_just_in_time()` logic when there are no translation files.
Fixes a performance issue where the JIT logic is invoked for every translation call if the there are no translations in the current locale. With this change, the information is cached by adding `Noop_Translations` instances to the global `$l10n` array. This way, `get_translations_for_domain()` returns earlier, thus avoiding subsequent `_load_textdomain_just_in_time()` calls.
WP:Props swissspidy, johnbillion, ocean90.
Fixes https://core.trac.wordpress.org/ticket/58321.
---
Merges https://core.trac.wordpress.org/changeset/55865 / WordPress/wordpress-develop@bf38bd326c to ClassicPress.
Partially fixes #1608 
Backport and added additional tests
Tests passing locally
N/A
- Performance …
> Improve `_load_textdomain_just_in_time()` logic when there are no translation files

- src/wp-admin/includes/class-plugin-upgrader.php
- src/wp-admin/includes/class-theme-upgrader.php
- src/wp-admin/includes/class-wp-site-health.php
- src/wp-admin/includes/class-wp-upgrader.php
- src/wp-includes/update.php
WP-r55720
Upgrade/Install: Create a temporary backup of plugins and themes before updating.
This aims to make the update process more reliable and ensures that if a plugin or theme update fails, the previous version can be safely restored.
When updating a plugin or theme, the old version is moved to a temporary backup directory:
wp-content/upgrade-temp-backup/plugins/[plugin-slug] for plugins
wp-content/upgrade-temp-backup/themes/[theme-slug] for themes. 
If the update fails, then the backup kept in the temporary backup directory is restored to its original location.
If the update succeeds, the temporary backup is deleted. 
To further help troubleshoot plugin and theme updates, two new checks were added to the Site Health screen:
A check to make sure that the upgrade-temp-backup directory …
> Create a temporary backup of plugins and themes before updating

- src/wp-includes/default-filters.php
- src/wp-includes/deprecated.php
- src/wp-includes/media.php
- src/wp-includes/pluggable.php
- src/wp-includes/post-thumbnail-template.php
- src/wp-includes/shortcodes.php
- src/wp-includes/theme.php
- src/wp-includes/widgets/class-wp-widget-media-image.php
- tests/phpunit/tests/media.php
- tests/phpunit/tests/post/thumbnails.php
- tests/phpunit/tests/theme/customHeader.php
- tests/phpunit/tests/widgets/wpWidgetMediaImage.php
WP-r56037
Media: Automatically add fetchpriority="high" to hero image to improve load time performance.
This changeset adds support for the fetchpriority attribute, which is typically added to a single image in each HTML response with a value of "high". This enhances load time performance (also Largest Contentful Paint, or LCP) by telling the browser to prioritize this image for downloading even before the layout of the page has been computed. In lab tests, this has shown to improve LCP performance by ~10% on average.
Specifically, fetchpriority="high" is added to the first image that satisfies all of the following conditions:
The image is not lazy-loaded, i.e. does not have loading="lazy".
The image does not already have a (conflicting) fetchpriority attribute.
The size of of the image …
> Automatically add `fetchpriority="high"` to hero image to improve load time performance

- src/wp-admin/update-core.php
When a plugin update is available, change the wording from "Expected compatibility with ClassicPress 2.4.0: 100%." "Potentially compatible with ClassicPress 2.4.0.".
Also removes the "Expected Compatibility with ClassicPress 2.4.0: 70% (7 "works" votes out of 10 total).".
See [discussion on the forum](https://forums.classicpress.net/t/wp-plugins-do-not-work-on-cp-even-though-the-tag-is-100-compatible/).
The check is done comparing the `Requires at least:` header against `$wp_version` that in ClassicPress 2.3.0 is 6.2.6, but the plugin can still broke depending on the use of React, the "Compatibility mode" setting or using not polyfilled block functions.
Local testing.
- Bug fix
> Change wording for expected compatibility when updating

- src/wp-includes/class-wp-theme.php
- src/wp-includes/default-constants.php
The current core code uses `twentytwentthree` as the default theme, a theme ClassicPress has never bundled. It also does not list `the-classicpress-theme` as a core default theme.
This in turn creates warning messages in Site Health about inactive and non-core themes.
This PR updates core code to reflect that `the-classicpress-theme` is considered the ClassicPress core theme.
Local automated and manual testing.
And:
- Bug fix
> Declare ClassicPress theme as a default theme

- src/wp-admin/post.php
We have had several reports of users being told that the backup version of their post or page is different from the current post or page:
We addressed some of this in PR #1575 . But apparently not all. There have been more reports in the forums at https://forums.classicpress.net/t/question-about-restore-backup-notice-in-classicpress-theme/5639, though these have been harder to explain. However, a new user of CP has found what appears to be the problem. It is a change to a cookie that we made in PR #1372.
This caused a change to the `httponly` property from `false` to `true`. This change prevents the cookie from being accessed by JavaScript and so the version of a post or page stored in the browser does not use the same cookie as CP, which causes the versions to differ.
This PR restores …
> Eliminate erroneous restore backup notice

- src/wp-admin/css/list-tables.css
In some circumstances, the width of an uploaded image may be too small to show up in the Media View list. This PR sets the width of the image at 100% to ensure that it does show. (The height is already set to auto, and a max-width is also already set, so this change will not cause the image to expand beyond the space allotted for it.)
> Ensure images are displayed in Media List View

- src/wp-admin/includes/media.php
This PR address Issue #1710.
The problem that Issue identifies is that, when bulk editing attachments but leaving the author unchanged, the author instead becomes unset. This is because the value for an `unchanged` author is `-1`, which is interpreted as the value being set, and so triggers an author update. But no author has an ID of `-1`, so the author becomes unset.
This PR therefore adds a check to ensure that the value is not `-1`. It also slightly changes the way that the update is performed so that (a) there is no call to the database first to retrieve the attachment object (which is unnecessary as we already its ID), and (b) to return a `WP_Error` object on failure instead of the current `0` (in order to produce a more helpful error message).
> Correct bulk author update of attachments

- src/wp-admin/includes/template.php
As described in #1694, custom classes applied using the core filter `"postbox_classes_{$screen_id}_{$box_id}"` in `wp-admin/includes/template.php` on `edit` pages are not applied and the open attribute is removed if the core filter is used.
Fixes open issue and restore functionality of a core filter, and open attribute when the core filter is used.
Local testing
Steps for testing are described in the open Issue.
- Bug fix
> Preserve metabox classes when defining open attribute

- src/wp-admin/widgets-form.php
When I wrote the code to replace the jQueryUI Sortable module in core with the SortableJS library, it looks like I overlooked one place where the jQueryUI Sortable module is used. That is in the Gallery widget, where it is used to sort images via drag and drop.
At the moment, this results in it being impossible to sort images within the widget via drag and drop, though no errors appear in the browser console. It's just that nothing happens. Unfortunately, the code that performs the dragging and dropping is not in a file specific to the Gallery widget, but is instead buried deep inside the `media-views.js` file, so re-writing it to work with SortableJS is not really feasible.
I am planning to replace all the JavaScript for the media widgets (including the Gallery widget) in time (I hope) …
> Make images in gallery widget sortable via drag and drop

- .github/workflows/phpunit-tests.yml
Occasionally, GitHub Actions fail, especially PHPUnit tests. This issue presents are one failure in the list of PHP Unit tests and a Docker error is reported.
For an example see action history (may require login):
https://github.com/ClassicPress/ClassicPress/actions/runs/12696759892/job/35391515623
On investigating this, a potential solution suggested by Copilot it to add a Docker login step to the Workflow to increase pull limits.
Tests on this PR will ensure login succeeds and continued use after this is merged should eliminate these occasional errors
- Bug fix
- New feature
> Add Docker Login step to Actions

- .github/workflows/phpunit-tests.yml
- tests/phpunit/tests/image/resize.php
Running test on pull requests opened from a fork results in an error as Docker Hub credentials are not passed to forks.
From GitHub Documentation:
> Anyone with collaborator access to this repository can use these secrets and variables for actions. They are not passed to workflows that are triggered by a pull request from a fork.
Testing if this PR from `xxsimoxx/Classicpress` fork passes.
- Bug fix
> Fix test failing for Docker Login unsuccessful

- src/wp-includes/user.php
As described in an open Issue, under certain circumstances errors can be logged on servers if a users has a logged in cookie in a browser and the database tables have been dropped for a reinstall.
In testing it seems this needed a locally specified name for the logged in cookie in `wp-config.php`:
```
define( 'LOGGED_IN_COOKIE', 'session_' . AUTH_KEY );
```
Fixes #1675 
Local testing with the above cookie named in current `develop` resulted in a `debug.log` error as reported in the open issue, with this applied fix, the error is no longer logged.
N/A
- Bug fix
> Ensure LOGGED_IN_COOKIE is not validated when installing

- src/wp-includes/admin-bar.php
As proposed by @citrika in #1721  this PR adds a shortcut for plugins menu in the admin bar.
There are already already shortcuts for themes and for plugins (only in MS admin bar).
Local testing.
- New feature
> Add "plugins" in admin bar

- .github/workflows/phpunit-tests.yml
- tests/phpunit/tests/image/resize.php
Recently a unit test on resizing an avif image with Imagick was failing so the test was skipped.
This PR restores the test to allow monitoring and investigation as needed. Local tests using Imagick are orking as expected.
Restore a unit test and allow investigation into why it is failing on GitHub.
Local run of the test with Imagick available is working.
To run just the single test use `composer run phpunit -- --filter=test_resize_avif `
- Bug fix
> Restore skipped test resizing avif image

- src/wp-includes/class-walker-nav-menu.php
- tests/phpunit/tests/menu/walker-nav-menu.php
**WP-r59674: Menus: Improve performance by calling `get_privacy_policy_url()` once per `Walker_Nav_Menu` instance rather than for every nav menu item.**
The `start_el()` method in `Walker_Nav_Menu` was calling `get_privacy_policy_url()` for every menu item when building menus. This resulted in redundant queries, particularly for menus with many items. This obtains the `get_privacy_policy_url()` value in the constructor for reuse in the `start_el()` method to improve performance.
Redundant code to construct the privacy policy page is also refactored into the `set_up()` method during tests.
WP:Props arzola, swissspidy, westonruter, mukesh27.
Fixes https://core.trac.wordpress.org/ticket/62818.
---
Merges https://core.trac.wordpress.org/changeset/59674 / …
> WP-r59674: Menus: call `get_privacy_policy_url()` once

- src/wp-admin/freedoms.php
Update the 4 freedoms at page wp-admin/freedoms.php, to match the ones from WP. Are similar but much shorter. 
Did not find the current ones at the CP site, so I think they are not marked as the official CP freedoms.  
Matching freedoms is better for translators as well.
> Update the 4 freedoms in freedoms.php

- src/wp-admin/js/postbox.js
If a user on the Dashboard page goes to Screen Options and unchecks all the boxes to hide all the widgets, an error will appear when the last box is unchecked.
This PR addresses that by checking for the presence of a widget.
> Eliminate errors in browser console when deactivating all dashboard widgets

- src/wp-includes/js/media-grid.js
I experienced multiple race conditions in Media Library: one related to the media dialog displaying a wrong image flash before showing the right one, and another one related to a random error when trying to delete an attachment inside the dialog (so I applied fixes for other 2 similar functions).
I also applied a fix for a race condition related to a new feature (keyboard and touch navigation for the dialog) that I will propose in another PR.
It has been tested manually in Chromium, Brave and Firefox browsers in Linux.
- Bug fix
> Prevent multiple race conditions in Media Library

- src/wp-admin/plugin-install.php
Text is about the WordPress plugin directory.
At first I suggested changing `with the license WordPress uses` into `with the license ClassicPress uses`. 
But it's the same license, let's not change this, so it (almost) matches the string in WP core. 
Matching strings is better for translators.
Same applies to [theme-install.php#L113](https://github.com/ClassicPress/ClassicPress/blob/develop/src/wp-admin/theme-install.php#L113)
Also discussed [here](https://github.com/ClassicPress/ClassicPress/pull/1720#issuecomment-2610857653).
> Update text in plugin-install.php

- src/wp-includes/js/mediaelement/wp-mediaelement.js
Adding a video to the TinyMCE editor on a post or page causes an error to show in the browser console:
```
Uncaught ReferenceError: jQuery is not defined
```
This PR resolves that by re-writing the `~/wp-includes/js/mediaelement/wp-mediaelement.js` file so as to replace the previous jQuery with vanilla JavaScript.
> Replace jQuery with vanilla JavaScript in wp-medialement.js

- src/wp-includes/post-template.php
- tests/phpunit/tests/post/postPasswordRequired.php
**WP-r59736: Accessibility: Add invalid password message for post passwords.**
Display a message notifying the user of an incorrect password when submitting the post password form. Improve the accessibility of the form by adding a required attribute for consistent identification.
WP:Props henry.wright, jonnyauk, kreppar, tommusrhodus, joedolson, audrasjb, jdahir0789, parthvataliya, dhruvang21.
Fixes https://core.trac.wordpress.org/ticket/37332.
Merges https://core.trac.wordpress.org/changeset/59736 / https://github.com/WordPress/wordpress-develop/commit/23a215a4d0 to ClassicPress.
**WP-r59737: Docs: Add missing $text filter argument.**
Fix omitted filter argument variable name for `the_password_form_incorrect_password`. Follow up to https://core.trac.wordpress.org/changeset/59736. …
> WP-r59736: Add invalid password message for post passwords

- src/wp-includes/post.php
Unlink previous featured images from the object_relationships table when selecting a new featured image so only one attachment will be marked as "Featured image" in the Media Library instead of multiple ones.
- Bug fix
> Unlink previous featured images from the object_relationships table

- src/wp-admin/css/media-grid.css
The media grid is collapsed when bulk-selecting all the items.
- Bug fix
https://github.com/user-attachments/assets/45c4740f-a762-4cf7-8aa6-9f13791a61c4
> Prevent media grid collapse on bulk-selection

- src/wp-admin/css/media-grid.css
- src/wp-admin/upload.php
- src/wp-includes/js/media-grid.js
When PR #1756 was merged, it had just had a new commit added at the last minute to add arrow navigation within the modal. This PR addresses the issues that that commit has raised.
First, it removes a `role="navigation"` attribute from a `div` containing buttons. That role is for a menu; buttons are not a menu, so it is wrong and bad for accessibility.
Second, that PR creates an inconsistent UX when a user clicks an Edit Image button from within the modal while on mobile. A user using the arrow keys may navigate to a new file, but the buttons to provide the same experience do not appear on screen. This PR ensures that those buttons are now shown by adding a new `div` with the ID of `edit-image-navigation` to contain the relevant buttons.
Third, for the arrow keys to work, the cursor needs …
> Arrow navigation within modal on media grid

- package.json
In October when we [updated](https://github.com/ClassicPress/ClassicPress/pull/1566) to using more modern versions of SASS a PR was submitted [upstream](https://github.com/sindresorhus/grunt-sass/pull/312) to enhance one of our package dependencies.
This upstream PR has now been merged and a [new release](https://github.com/sindresorhus/grunt-sass/releases/tag/v4.0.0) made.
This PR moves the package.json file to using the main stream package rather than a branch so any future updates are notified.
To ensure future updates are notified.
PR upstream merged and looks good - PR tests will run.
N/A
- Enhancement
> Update to use official `grunt-sass` release

- src/wp-admin/includes/class-wp-upgrader.php
WP-r56550: Upgrade/Install: Fix broken `sprintf()` call when deleting a backup.
In `WP_Upgrader::delete_temp_backup()`, a malformed `sprintf()` call did not pass the value, triggering a Warning in PHP 7 and a Fatal Error in PHP 8.
This fixes the malformed `sprintf()` call by correctly passing the value.
Follow-up to https://core.trac.wordpress.org/changeset/55720.
WP:Props akihiroharai, afragen.
Fixes https://core.trac.wordpress.org/ticket/59320.
---
Merges https://core.trac.wordpress.org/changeset/56550 / WordPress/wordpress-develop@2a13d9321c to ClassicPress.
Fixes #1836 
Backport
N/A
- Bug fix
> Fix broken `sprintf()` call when deleting a backup

- src/wp-admin/includes/class-wp-plugins-list-table.php
Fixes a fatal error when listing plugins where one is incompatible with ClassicPress. `printf` requires two arguments and this call only gives one. If you compare with the [other version](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/includes/class-wp-plugins-list-table.php#L1413-L1416) it would appear this was introduced when refactoring the HTML into multiple parts.
> Fix fatal when listing incompatible plugins

- src/wp-includes/class-fix-wpcli.php
WP-CLI bootstraps CP load, so we introduced a fix to bring `$cp_version` in scope in `src/wp-includes/class-fix-wpcli.php`.
That was done at `after_wp_load` that is too late for plugins using `classicpress_version()`.
@citrika please can you check if this fix solves #1817?
Reproduced in a local installation.
- Bug fix
> Fix WP-CLI

- src/wp-includes/media.php
- tests/phpunit/tests/media.php
- tests/phpunit/tests/shortcode.php
- tests/phpunit/tests/widgets/wpWidgetMediaImage.php
Wordpress line is:
$width = $html5 ? $atts['width'] : ( 10 + $atts['width'] );
So if ClassicPress uses html5, it must be $atts['width'] without extra 10px
The code will work the same way as in WordPress, making the migration process much easier.
It just make figure width same as img width.
- Bug fix
- Breaking change maybe
> Fix unneeded extra 10px for images

- src/wp-admin/widgets-form.php
- src/wp-includes/media.php
Related issue: [Galleries not sortable](https://github.com/ClassicPress/ClassicPress/issues/1826)
Related PR: [Make images in gallery widget sortable via drag and drop](https://github.com/ClassicPress/ClassicPress/pull/1713)
> Fix gallery editor sortable functionality

- src/wp-admin/includes/class-wp-site-health.php
- src/wp-admin/includes/dashboard.php
- src/wp-includes/update.php
While updating the `en_GB` translation files in readiness for ClassicPress `2.4.0` I found a few instances in core of `WordPress` that should be changes to `ClassicPress`.
Branding.
In translation files only.
N/A
- Bug fix
> Change a few instances of WordPress to ClassicPress

- src/wp-includes/compat.php
- tests/phpunit/tests/compat/arrayAll.php
- tests/phpunit/tests/compat/arrayAny.php
- tests/phpunit/tests/compat/arrayFind.php
- tests/phpunit/tests/compat/arrayFindKey.php
PHP 8.4 introduced four new functions to provide a common way to more easily perform common operations on arrays.
- `array_find()`: https://www.php.net/manual/en/function.array-find.php
- `array_find_key()`: https://www.php.net/manual/en/function.array-find-key.php
- `array_all()`: https://www.php.net/manual/en/function.array-all.php
- `array_any()`: https://www.php.net/manual/en/function.array-any.php
These functions are now polyfilled making them available on all supported versions of PHP (currently 7.2+).
WP:Props Soean, swissspidy, TobiasBg, ayeshrajans, mukesh27, joemcgill.
Fixes https://core.trac.wordpress.org/ticket/62558.
Conflicts:
- src/wp-includes/compat.php
---
Merges https://core.trac.wordpress.org/changeset/59783 / https://github.com/WordPress/wordpress-develop/commit/6fea443 …
> WP-r59783: Introduce polyfills for new array functions in PHP 8.4

- src/wp-admin/update-core.php
The update link at page `wp-admin/update-core.php` returns a 404. 
The version number in the URL contains `.` instead of `-` (2.4.1 instead of 2-4-1).
I have fixed this by using `sanitize_title()`, which is also used in file [wp-admin/includes/update.php](https://github.com/ClassicPress/ClassicPress/blob/develop/src/wp-admin/includes/update.php#L296) (for the "please update now" message). 
- Bugfix
> Fix update link in dashboard

- src/wp-admin/upload.php
In the media grid view, the default value is currently set as the default value set on the `Settings -> Reading` page. This is typically too low; the default was formerly 80, and this PR reinstates that number as the default.
> Media grid default number of items

- phpcs.xml.dist
When a non en-US locale is used translations are installed for core, plugins and theme.
Running `phpcs` returns lot of errors on those files.
Easier testing.
`composer run phpcs`
- Bug fix
> Exclude `languages` folder from `phpcs` checks

- src/wp-content/themes/twentyseventeen/assets/js/navigation.js
For the TwentySeventeen theme and the ClassicPress child theme, there are browser deprecation warnings linked to a line in `twentyseventeen/assets/js/navigation.js` and the `.click()` handler.
Fix deprecation warning in browser console.
Local testing with Safari browser.
N/A
- Bug fix
> Fix for core theme jQuery deprecation

- src/wp-admin/css/media.css
- src/wp-includes/js/media-grid.js
I ported some of the CSS from PR #1771 skipping the sticky header because I found it complicated to adapt it to the current markup.
```css
.copy-to-clipboard-container button.copy-attachment-url {
white-space: normal;
}
```
This was ported from WP
```css
@media only screen and (max-width: 900px) {
.attachment-details .attachment-info .copy-to-clipboard-container {
margin: 10px 0 0 0;
padding-top: 0;
}
.attachment-details .compat-item label span,
.attachment-details .setting .name,
.attachment-details .setting input[type="text"],
.attachment-details .setting textarea,
.attachment-details .setting + .description {
float: none;
width: 98%;
max-width: none;
height: auto;
}
.attachment-details .setting + .description {
clear: both;
font-size: 12px;
font-style: normal;
margin-bottom: 10px;
}
} …
```
> Port some CSS from PR #1771

- src/wp-content/themes/the-classicpress-theme/footer.php
- src/wp-content/themes/the-classicpress-theme/functions.php
- src/wp-content/themes/the-classicpress-theme/style.css
You can now change the footer content from static to variable, by using widgets. 
Breakpoint of footer area is the same as sidebar now.
Temp demo site [here](https://www.webmastergroningen.nl/cp/).
Extra: I also noticed that widgets in page sidebar are hidden in mobile screen with CSS. Removed that CSS.
Footer contains static content, which may not be attractive for users,
A footer menu and static CP-related content.
By default a footer menu and static CP-related content. But you can replace this with variable content, by using widgets.
No breaking changes.
> ClassicPress theme - updated footer area

- src/wp-admin/upload.php
An `aria-describedby` attribute points to an ID of `table-paging`, but that ID is currently missing. This PR rectifies that.
> Update upload.php to add ID for aria-describedby attribute

- src/wp-admin/includes/translation-install.php
- src/wp-includes/update.php
This PR introduces and hooks a function to check for translation file updates from the ClassicPress API and where these are found, injects them into the update transient stored in the database.
This will allow for in-release translation file updates as translation packs are improved and updated.
So far only local testing.
N/A
- New feature
> Add core translation update checks

- src/wp-admin/upload.php
- src/wp-includes/js/media-grid.js
In list mode, the functionality to edit and delete attachments is disabled when the user doesn't have the required permissions. But in grid mode, the "Edit image" and "Delete permanently" buttons are always visible regardless of the permissions, and also it's possible to interact with the "Alternative Text", "Title", "Caption", "Description", "Media Categories", and "Media Tags" fields causing silent "403" errors and a WSOD.
With a user account with "Author" role.
- Bug fix
https://github.com/user-attachments/assets/75607261-5b5f-4b11-8d81-07452bcd1ba4
https://github.com/user-attachments/assets/2a290251-cc31-4a7a-a024-92ae90c3e0cd
> Disable attachment editing and deleting in media dialog when user is unauthorized

- src/wp-includes/widgets/class-wp-widget-media-image.php
- tests/phpunit/tests/widgets/wpWidgetMediaImage.php
This PR is a follow up to #1819, based on finding while reviewing and checking #1820, #1821 and #1822
The parent class `update()` function can be used without the need to create and maintain child class functions with the additional benefit that form submissions are automatically sanitized, which helps with PHPUnit tests.
Simplification of Media Widget code 
PHPUnit tests and local widget testing.
N/A
- Enhancement
> Restore use of parent class `update()` function in Image Widget

- src/wp-admin/import.php
- src/wp-admin/includes/class-custom-background.php
- src/wp-admin/update-core.php
All help tabs except 3 have the "Support forums" label.
Updated 3 files to match label from above.
And changed forum link in 1 file (from WP to CP).
To avoid more "wrong" instances I have checked the `admin-nl_NL` translation file.
- No breaking change
> Textual changes dashboard Help tab

- src/wp-content/themes/the-classicpress-theme/style.css
1) Added `#primary` prefix throughout stylesteet, that fixes visual conflict with (for example) the default Navigation Menu widget. 
2) Fixed an overlapping media query:
```
@media screen and (max-width: 900px) {
@media screen and (min-width: 900px) {
```
Changed breakpoint to `899px`, to match the one in mobile menu file `menu-resize.js`.
This PR fixes multiple visible issues and I think this will benefit all users.
No breaking changes.
> ClassicPress theme - misc CSS fixes for menu

- src/wp-admin/privacy.php
Make page `wp-admin/privacy.php` similar to the pages attached to the other tabs. 
Current page contains duplicate info from page `wp-admin/options-privacy.php`.
The new textual content is copied from file `wp-admin/freedoms.php` (was hidden).
- No breaking change
> Update page wp-admin/privacy.php

- src/wp-admin/css/list-tables.css
- src/wp-admin/includes/class-wp-media-list-table.php
While reviewing other PRs addressing the Quick Edit feature in the Media table, I noticed some layout discrepancies as compared to the Quick Edit are on the Posts table.
This PR aims to address those discrepancies and produce a consistent UI experience.
In particular this PR address the date fields indentation and ensures the tags text area is below the heading and given adequate screen space.
Local testing and screen shots below, needs assessment that HTML syntax remains valid.
Post screen for comparison
- Bug fix
> Media Quick Edit Layout improvements

- src/wp-admin/css/media-grid.css
@citrika pointed out some time ago that the header in the media grid attachment details modal should remain in place when the user scrolls down. This PR accomplishes that, as shown below at different screen widths:
To reproduce, go the media grid and select a file. Ensure that the height of the screen is less than the height of the modal contents, and scroll down. The header should stay in place while the content disappears underneath it (only to return if scrolling is reversed).
> Make media grid attachment details modal header sticky 

- src/wp-admin/js/gallery.js
This is a simple change that removes the unnecessary `#` from the selector specified by `document.getElementById`.
> Correct typo for file upload gallery

- src/wp-admin/js/widgets/media-video-widget.js
- src/wp-includes/js/mediaelement/mediaelementplayer-legacy.css
- src/wp-includes/media.php
- src/wp-includes/widgets/class-wp-widget-media-video.php
Attempting to add a video to the widget for the first time doesn't always work because an element to which it will be added does not always exist. (This does not affect occasions when one video is replaced by another.)
This PR fixes that issue.
> Ensure video can be added to media video widget

- src/wp-admin/css/list-tables.css
- src/wp-admin/includes/class-wp-media-list-table.php
> Consistent whitespace in Quick Edit across screens

- src/wp-admin/includes/ajax-actions.php
I have been fighting with this for hours and it seems to be a bug. It's been reported many times on the internet, but no-one has a fix (except where there's been an obvious typo). The problem seems to have existed for over ten years! So here are the details.
`WP_Query()` takes a number of parameters, including `'post_in'`, which must be an array. This causes no problems when only PHP is used, but there's an AJAX endpoint, `query-attachments`, that makes use of this query, and that's when the problem manifests itself.
Try using the following AJAX call:
```
var selectedIds = a comma-separated list or array of attachment IDs
var formData = new FormData();
formData.append( 'action', 'query-attachments' );
formData.append( 'query[post__in]', selectedIds );
formData.append( 'query[orderby]', …
```
> Fix problem with `post__in` parameter in wp_ajax_query_attachments()

- src/wp-admin/includes/ajax-actions.php
- src/wp-admin/includes/class-wp-media-list-table.php
- src/wp-admin/js/media.js
When comparing the table row outputted on page load and the one returned by the AJAX request after using Quick Edit, there are 3 differences that don't depend on Javascript manipulation:
```html
<a href="https://classicpress.local/forest/">View</a>
<a aria-label="Attach “forest” to existing content">Attach</a>
<td data-colname="Date">5 mins ago <time datetime="2025/03/22"></time></td>
```
```html
<a href="https://classicpress.local/wp-content/uploads/2025/03/forest.jpg">View</a>
<a aria-label="Attach “(no title)” to existing content">Attach</a>
<td data-colname="Date">2025/03/22</td>
```
https://github.com/user-attachments/assets/7ff7f2e9-4d36-4da3-9c67-df7ca37f8a49
https://github.com/user-attachments/assets/2bc7eebe-7554-4e67-abdc-ca3360e42008
```javascript
inputs = …
```
> Fix Quick Edit in Media Library

- src/wp-admin/upload.php
- src/wp-includes/js/media-grid.js
In PR #1873 I attempted to eliminate the need to use `replace()` in order to obtain an attachment's ID from the list element in the HTML. This caused a problem because there was no `data-id` attribute for the element. This PR adds that `data-id` attribute without causing extra queries because the information is already held within the `$attachment` variable.
> Add data ID to li elements in media grid

- src/wp-includes/formatting.php
While investigating a different issue, I stumbled across an empty `foreach` loop and found that there is an upstream fix available to backport.
WP-r58889: Coding Standards: Replace an empty `foreach` loop in `wp_replace_in_html_tags()`.
This aims to clarify the intention of the code and improve readability.
Follow-up to https://core.trac.wordpress.org/changeset/33359.
WP:Props jrf, TobiasBg, mi5t4n, dhruvang21, mayura8991, nadimcse, Presskopp, SergeyBiryukov. Fixes https://core.trac.wordpress.org/ticket/61860.
---
Merges https://core.trac.wordpress.org/changeset/58889 / WordPress/wordpress-develop@3476790c2e to ClassicPress.
Fix for some poor code layout.
This is a backport.
N/A
- Code enhancement
> Replace an empty `foreach` loop in `wp_replace_in_html_tags()`

- src/wp-admin/css/edit.css
- src/wp-admin/edit-form-advanced.php
- src/wp-admin/js/editor.js
- src/wp-admin/js/post.js
- src/wp-includes/class-wp-editor.php
- src/wp-includes/css/editor.css
For some time I have known that any comments within the editor content can get stripped out when switching between visual and text tabs in the editor.
I had presumed that this was linked to some JavaScript but I now think it is linked to the initiation of the Editor.
Upstream `wpautop` is configure to false if Block content is detected within post content. This PR applies simple post content check for blocks to ensure post content data is not destroyed by swapping tabs when content is migrated from WordPress.
Additionally, this PR includes an A11Y backport (https://core.trac.wordpress.org/changeset/59188) for the editor and a subsequent layout correction (https://core.trac.wordpress.org/changeset/60043).
Ensures that post content integrity is respected on site migration.
Local testing, …
> Protect comments in editor content when switching tabs

- src/wp-admin/js/theme.js
When navigating to previous items in the Themes screen with the left arrow key, the loop doesn't stop at the first item as opposed to the button navigation.
Also the "keydown" event is more convenient than the "keyup" one to keep the key pressed to navigate.
This also happens in the latest version of WordPress.
> Improve keyboard navigation in Themes screen

- src/wp-content/themes/the-classicpress-theme/style.css
- Few minor tweaks.
- Removed some duplicate or unnecessary styling.
- Relocated some styling to more logical location in stylesheet.
- Make styling between the various types of buttons more consistent (see screenshot). This means a cleanup of the various button styles that were present in the stylesheet. I think it's much cleaner this way.
- Changed a few prefixes from `#sidebar` to `.widget-container` (because of recently added footer widgets).
Makes theme look better.
- No breaking changes.
> ClassicPress theme - tweaks and such in stylesheet

- src/wp-includes/classicpress/class-cp-debug-compat.php
Update Site Health page with info about Blocks Compatibility and link to the associated setting.
As mentioned in Zulip [and here](https://github.com/ClassicPress/ClassicPress/issues/1872).
I did not understand why the list wasn't auto-updating after adding/removing themes/plugins.
Then I heard at Zulip you can force an update.
- No breaking change
> Update Site Health page with info about Blocks Compatibility 

- src/wp-admin/js/media.js
The "options.once" parameter was removed when resolving merge conflicts after merging #1837 and #1887
It prevents multiple AJAX submissions in Quick Edit.
Edit: The click event listener cleanup strategy needed to be replaced to support HTML5 validation.
> Replace click event listener cleanup strategy in Quick Edit

- src/wp-admin/includes/theme.php
This PR, as agreed in the weekly core chat, removes the Theme tag listing from the Theme modal displayed when viewing new themes from WordPress.org in the Customizer. This removed 
Fixes #1910 
Locally tested, see screen grabs below
- Bug fix
> Remove tags from Customizer theme modal for new WP themes

- src/wp-content/themes/the-classicpress-theme/editor-style.css
Because of moving file `editor-style.css` to main theme folder, the link to the woff2 files should be changed as well.
Copy-pasted whole code block from file `style.css`.
This also changed the indent (from spaces to tabs) and double quotes instead of single quotes.
Props: @citrika
No breaking change
> ClassicPress Theme - fix loading of woff2 files in editor

- src/wp-admin/includes/media.php
- src/wp-admin/upload.php
As discussed on Zulip, this PR makes all media metadata available for use by JavaScript by simply taking the third parameter exposed by the `wp_prepare_attachment_for_js` filter, which is `$meta`, and injecting it through that filter. As the metadata is already exposed by the filter, there is no additional cost to this in terms of trips to the database.
This PR then also makes immediate use of this metadata by including the artist's name and album title (if any) among the data attributes included for audio elements within the media library grid. This can be tested by using the browser inspector to check for the new data attributes, `data-artist` and `data-album` in the media library grid.
A further PR will be needed to create the fields where this information can be displayed, though I …
> Inject meta into wp prepare attachment for js()

- src/wp-admin/includes/plugin-install.php
Changed text of update notification at plugin screen, to match the other ones.
I have respected the use of the `strong` tag that is used in the file.
Same notifications throughout dashboard.
- No breaking changes
> Minor textual change in file plugin-install.php

- .github/workflows/phpunit-tests.yml
The PHPUnit tests take the longest time to complete, and we use an action to cancel in progress tests when a new commit is added to an open pull request... only it isn't working, the running process still completes.
On investigating it may be a better option to use the built in [concurrency](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs) controls. 
More efficient GitHub Action usage.
Stop using outdated and failing GitHub action
Syntax is as recommended here, will be able to test once committed and a PR is rapidly updated with another commit.
N/A
- New feature
> Update workflow runs to use concurrency

- src/wp-admin/js/widgets/text-widgets.js
In the core meeting today, there was some discussion about the Text widget not always displaying the TinyMCE editor. I have had a further look since then, and it seems to be an issue of when the relevant scripts load. This PR addresses that problem by making an explicit call to initialize TinyMCE for each text widget on page load.
> Ensure TinyMCE is always displayed in Text widget

- .github/workflows/phpunit-tests.yml
Follow up to #1936 
The addition of the concurreny syntax to the PHPUnit tests did result in job cancellation (see screen grabs below) but the `group` definition is cancelling jobs running on `develop` when it should not.
I believe this syntax may be more appropriate:
`${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}`
github.workflow ensure the cancellation applies only to this workflow.
github.event_name limits to pull requests and github.head_ref is the branch name of a PR
If the workflow is not on a PR, github.sha is used instead to avoid erros and that should always be unique.
[I have set the failed job in the image below to run again so anyone investigating the past actions may need to check for the first run]
Ensures completion of …
> Adjust concurrency group

- src/wp-admin/css/color-picker.css
- src/wp-admin/css/revisions.css
- src/wp-admin/js/iris.js
At the moment, the slider in the color picker in the Customizer won't slide. (If it gets focus, it can still be used to change the color values using the arrow keys, but the slider itself won't move.) This is because the browsers have not, until recently, agreed on how a vertical slider should work, and so each did it differently, and our code made allowances for those differences.
But now there is a shared spec, and our code no longer works properly. This PR fixes that.
A welcome by-product of this is that we can let the browsers handle the precise way that the slider gets displayed instead of needing to take over control ourselves.
To see the current problem, open the Customizer with a theme (like CP TwentyFifteen) that supports changing colors. Go to the Colors panel and attempt to …
> Update and fix color picker slider in Customizer

- .github/workflows/coding-standards.yml
Pre-commit checks in the Coding Standards workflow are currently failing because the PHPUnit.de site has an invalid SSL certificate.
On reviewing the workflow configuration, PHPUnit 8 is manually installed, but the composer.json configuration uses PHPunit 9 which should work fine, thus avoiding a manual installation step.
Simplyify workflow and reduce dependency range.
GitHub actions on this branch should confirm this PR is a solution.
- Bug fix
> Update coding standards workflow to use Composer dependencies

- src/wp-includes/pluggable.php
- tests/phpunit/tests/auth.php
As discussed in the core meeting today there are migration issues now between WordPress 6.8.x and ClassicPress due to a different approach to password hashing. This PR aims to address this issue and also close #1946
Changes broadly covers three things:
1. Any password set in WordPress 6.8 using the default configuration should now allow login after migration to ClassicPress.
2. Resetting a passord to an `md5()` hash in the database will now allow a user to login, this restore a lockout workaround often recommended in online articles about adding such a hash directly into the database tables. The above change also fixes #1946 
4. In test the above I noted that any legacy passords that start wit `$P$` are not detected as needing rehashing, this is because `$wp_hasher` is not empty after …
> Update password checks for WordPress 6.8

- src/wp-includes/widgets/class-wp-widget-custom-html.php
- src/wp-includes/widgets/class-wp-widget-media.php
- tests/phpunit/tests/widgets/wpWidgetMedia.php
After all the recent updates to media widgets, the function `render_control_template_scripts` no longer does anything. (A quick `grep` confirms this.) This PR removes the function and deletes several references to it in code comments and docblocks.
> Remove redundant function from media widgets

- src/wp-admin/setup-config.php
This is a similar approach to #1930 but avoids using a function and has also implemented a fallback when the Posix PHP module functions are not available. Lastly it also displayed a warning in the next installation screen is permissions on `wp-config.php` were set as current to 666.
Fixes #1924
Local testing
N/A
- Enhancement
> Tighter file permissions for wp-config.php

- src/wp-includes/post.php
This PR addresses Issue #1981. It does so by ensuring that, when an image is somehow deleted from the media library, its ID within a gallery widget is also deleted.
This, in turn, avoids confusing the `has_content( $instance )` function within the gallery widget itself. That works by checking for each image and, if it fails to find any of them, it reports that there is nothing to show at all. That's the cause of Issue #1981.
By ensuring that the deleted attachment's ID is deleted from the list contained in a gallery widget, the function `has_content( $instance )` no longer checks for it. Instead, it checks only for images that do exist and so the widget is shown as expected.
> Delete references to deleted images in gallery widgets

- src/wp-includes/classicpress/class-wp-compat.php
- tests/phpunit/tests/compat/wordpress.php
See https://github.com/fairpm/fair-plugin/pull/65
`wp_print_community_events_markup` will be used in the FAIR - Federated and Independent Repositories to fix an issue with ClassicPress Dashboard.
The test ensures that the function will be not backported or polyfilled (even if there is no reason to do that).
See failing actions for the first commit.
- New feature
> Add Unit Test for FAIR plugin

- src/wp-admin/includes/class-wp-comments-list-table.php
- src/wp-includes/comment.php
- tests/phpunit/tests/comment/getCommentCount.php
- tests/phpunit/tests/comment/wpCountComments.php
When Comments have been made on content created for a Custom Post Type and then that CPT is disbaled, Comments may display notices and warning in the Comments page if debug mode is set to true as desribed in #1974 
This  PR aims to resolves those notices and uspate some testing of cmment counting but attaching the comments to a post in order that the tests work successfully.
Fixes #1974 
Addressed noticed seen when debug is true
Local testing and updated unit tests.
- Bug fix
> Fix PHP notices for Comments in inactive Custom Post Types

- src/wp-admin/includes/class-wp-plugins-list-table.php
After #1963 `classicpress_has_update` is called in every plugin row in the installed plugins page.
This PR limits the call at the construction of the class.
**In normal conditions this function uses a transient and works well.** But if the API endpoint does not exists, for example for the `dev` version (see https://api-v1.classicpress.net/upgrade/2.4.1+dev.json?version=2.4.1%2Bdev), this transient is not set and so the functions calls `wp_version_check` with the options to force a connection.
In my test setup it ended hitting the API 34 or more times and took 16 seconds to load the page.
Local testing using Query Monitor
- Enhancement
> Limit API calls in `class-wp-plugins-list-table.php`

- src/wp-admin/includes/class-wp-plugins-list-table.php
This minor PR removes an orphan variable called `$available_updates` from file `wp-admin\includes\class-wp-plugins-list-table.php`. 
As you can see it's only being used in 1 file, called `class-wp-ms-themes-list-table.php`.
> Remove orphan $available_updates variable

- src/wp-includes/js/mediaelement/wp-mediaelement.css
As discussed in #1997 core playlist styling needs an update, because playlist items are wrapped in list elements from CP 2.5.
We found out **list numbers are not being displayed in Safari**, because `overflow: hidden;` is added to the `.wp-playlist-caption` element. It's added to clip long file/artist names nicely (check screenshot before). This will happen mostly in small (widget) areas and in mobile screens.
I could not find a simple fix. So I suggest removing the overflow from the `ol` playlist. 
IMO it still looks fine (check screenshot after).
There's also margin/padding that is often added by themes to the `ol` / `li` tags. 
We could add a reset (example below). Or we could decide this is theme territory. Feedback requested..
```
ol.wp-playlist-tracks {
margin-left: 1em; …
```
> Fix layout for media playlists

- src/wp-content/themes/the-classicpress-theme/style.css
Bumping patch version prior to release.
Release will contain:
- Track length layout adjustments for core themes (#2021)
- Fix empty primary menu display in The ClassicPress Theme (#1980)
> Bump The ClassicPress Theme version to 1.1.1

- src/wp-content/themes/the-classicpress-theme/style.css
- src/wp-content/themes/twentyseventeen/style.css
This PR reverts the changes from #2021 as they do not take CP 2.4.1 and before into account.
I readded the changes with prefix, so they are only being applied in CP 2.5+.
The playlist in 2.5+ is list based, instead of div based.
See [this comment](https://github.com/ClassicPress/ClassicPress/pull/2021#issuecomment-3088730015).
Local Install.
- Bug fix
> Theme track length layout adjustments fix

- src/wp-content/themes/the-classicpress-theme/js/menu-resize.js
Fixes Issue #2039. As I wrote there, if you're using the keyboard to navigate around the page and didn't have the block of code referred to by @Guido07111975, you would have to tab through every menu item to get through the menu! As regular keyboard navigators expect, this code provides a way of closing each open sub-menu by using the Escape key, so that not every menu item needs to be tabbed through. The down array key can then be used to re-open a sub-menu closed in this manner.
The problem is that the `e.preventDefault();` isn't currently limited to when a user hits the arrow key in the menu. This PR fixes that.
> Enable scrolling down via down arrow in the ClassicPress Theme

- src/wp-admin/themes.php
Some backbone code was left so in the theme screen there are some labels like `aria-label="Live Preview {{ data.name }}"` left.
Local testing
- Bug fix
> Fix aria-label in theme page

- src/wp-admin/includes/ajax-actions.php
- src/wp-admin/js/theme.js
Fixes #2047.
While working on this, I realized that the Activate/Install hyperlink in the modal overlay always shows as "Activate" once an installed them has been selected, even if (while remaining on the same page) that theme is subsequently deselected and another chosen. This PR fixes that issue too.
> Prevent activation of incompatible installed theme

- src/wp-includes/js/media-grid.js
Fixes Issue #2056 by removing the `alt` image attribute field from an open media grid modal when the media file in question is not an image.
> Update media-grid.js to remove superfluous alt attribute in modal

- .github/workflows/phpunit-tests.yml
Introduces a 'multisite' matrix parameter to the GitHub Actions PHPUnit workflow, enabling separate jobs for multisite and non-multisite environments. Updates job naming, matrix includes, and test execution steps to support multisite testing.
This PR aims to run `default` and `multisite` PHPUnit tests separately to increase the time for testing on GitHub.
Tests are currently taking 20-25 minutes to complete.
Will need to await testing on this PR.
After PR creation tests are separated and ran in less than 12 minutes.
Build / Test Enhancement
> Separate multisite testing to PHPUnit workflow

- src/wp-admin/js/theme.js
- src/wp-admin/themes.php
This PR addresses an issue that arises where an incompatible them is already installed in a CP instance and then gets an update. To test, download the Kadence theme from [wordpress.org](https://wordpress.org/themes/kadence/) and then upload it manually to a test site while downgrading the version number in its `style.css` file, so that it appears to be an old version.
On the `Appearance -> Themes` page, you will see something like this, where two warning messages overlap each other:
This PR corrects that so that the two can now both be read easily, like this:
Another current problem is that, when clicking on the `Theme Details` button that appears when hovering over the theme, an error is shown in the browser console:
This PR addresses that and allows the modal to open as intended, like …
> Improve display of warnings for incompatible theme updates

- src/wp-content/themes/the-classicpress-theme/style.css
This PR adds minor changes to the mobile menu.
The inner-header did not expand to the available space (see screenshots)
The search field in mobile menu was styled with flexbox, not needed, so removed.
Plus some leftover styling removed.
Edit: after creating the PR I added some more menu related fixes. 
For example, removed the enormous `line-height: 3.5em` from `#primary-menu.menu` and fixed elements that were affected by this.
And cleaned styling of the big page title.
Local install (in Edge and Chrome).
- Bug fix
> The ClassicPress Theme - minor CSS tweaks

- src/wp-includes/classicpress/class-wp-compat.php
A notification at plugins page is displayed if CP detects a plugin using block releated features.
This notification does not have a border-bottom (box-shadow) if there's a plugin update notification displayed as well.
But the condition to set border fails for WP-plugins.
Somehow `$plugin_data['new_version']` is always set for WP-plugins.
Replacing this with `$plugin_data['update']` fixes this. This variable is only available in case of a plugin update (also for CP plugins).
Note: this notification is not always displayed at Plugins page. Cache-related perhaps. While creating the PR and the screenshots I've changed some conditions to force the display.
Local install with WP and CP plugins.
- Bug fix
> Plugins page - block notification fix

- .github/workflows/phpunit-tests.yml
The external-http PHPUnit job now only runs when code coverage is enabled in the matrix, preventing unnecessary runs when coverage is set to 'none'.
The external-http PHPUnit tests connect to an external API so multiple instances of this test can cause timeouts on the API and multiplied testing is probably not necessary.
Tests will rin on this PR and the external-http PHPUnit should only run on the PHPUnit test that also tests using XDebug now.
Example none XDeug test
XDeug test
- Enhancement
> Add coverage check to external-http PHPUnit job

- package-lock.json
- package.json
This is a PR to list packages that are distributed with ClassiPress (after build steps) as dependencies, rather thna development depencencies.
ClassicPress should correctly differentiate between `npm` packages that are used only in the development of the project and those that contribute files to the final ClassicPress package.
Local testing of npm install and build steps.
N/A
- Enhancement
> List distributed dependencies correctly

- src/wp-admin/about.php
- src/wp-admin/js/customize-nav-menus.js
- src/wp-includes/class-wp-customize-nav-menus.php
- src/wp-includes/customize/class-wp-customize-nav-menu-item-setting.php
- src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php
- src/wp-includes/rest-api/endpoints/class-wp-rest-terms-controller.php
- src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php
- src/wp-includes/version.php
- tests/phpunit/tests/customize/nav-menu-item-setting.php
- tests/phpunit/tests/customize/nav-menus.php
- tests/phpunit/tests/rest-api/rest-users-controller.php
This is a backport of two upstream security fixes:
https://wordpress.org/news/2025/09/wordpress-6-8-3-release/
- A data exposure issue where authenticated users could access some restricted content. Independently reported by [Mike Nelson](https://hackerone.com/mnelson4), [Abu Hurayra](https://hackerone.com/hurayraiit), [Timothy Jacobs](https://profiles.wordpress.org/timothyblynjacobs/), and [Peter Wilson](https://profiles.wordpress.org/peterwilsoncc/).
- A cross-site scripting (XSS) vulnerability requiring an authenticated user role that affects the nav menus. Reported by [Phill Savage](https://x.com/Savphill).
This PR aso updates the `about.php` page and bumps the core `$wp_version` variable.
Security fix.
Backport
N/A
- Bug fix
> Backport of fixes from WordPress 6.8.3

- src/wp-includes/pluggable.php
- tests/phpunit/tests/pluggable/signatures.php
- tests/phpunit/tests/pluggable/wpMail.php
**Mail: Support inline attachments.**
MIME allows for referencing included attachments by their `Content-ID` header using the `cid` URL scheme. This can be used to embed images inline to the HTML message. For example, `<img src="cid:logo">`, will display the contents of message part with the `Content-Id: <logo>` header.
The `wp_mail()` function now supports including inline attachments through a new `$embeds` parameter. It accepts a map of `Content-ID` values to file paths. The `wp_mail_embed_args` filter can be used to customize the resulting `PHPMailer::addEmbeddedImage` method call.
WP:Props jesin, swissspidy, chrisvendiadvertisingcom, SirLouen, mukesh27, yashjawale, iamadisingh. Fixes https://core.trac.wordpress.org/ticket/28059.
---
Merges …
> WP-r60698: Add support for inline attachments in `wp_mail`
