.travis.yml
Remove the Slack notifications for WP core.
=> Run tests via Travis CI

tools/i18n/makepot.php
As #45 
I didn't changed the path so in that part the `wp-` stuff was not replace with the new prefix.
=> Remove wordpress from makepot.php

src/wp-admin/includes/class-wp-automatic-updater.php, src/wp-admin/includes/file.php, src/wp-admin/includes/misc.php, src/wp-admin/includes/schema.php, src/wp-admin/install.php, src/wp-admin/js/user-profile.js, src/wp-admin/ms-delete-site.php, src/wp-includes/ms-functions.php, src/wp-includes/user.php
PR for issue #54 which is a followup for PR #51
=> Change Howdy to Hello in src/

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This will avoid new issues that have feature suggestions by redirecting them to the right place.
=> Redirect feature suggestions for v.2.0.0

README.md
As per the discussion in the committee yesterday, this is the only file that still needed updating to reflect the new-ish tagline (or strapline).
=> update readme to reflect new-ish tagline

README.md
New paragraph that should make it easier for people to figure out what we're doing and where they can help.
> We welcome contributions of all kinds!  Have a look at [this repository's open issues](https://github.com/ClassicPress/ClassicPress/issues) and [our v1 project board](https://github.com/orgs/ClassicPress/projects/1), or if you're not sure where to start, [join us in Slack](https://join.slack.com/t/classicpress/shared_invite/enQtNDIwNjY2OTg1MjAxLWJiM2U2NmY3ZjFlZjQ4Zjk2OGI4ZTg3NzY1ZTU3NzI3OTRjMTU0YzAzOWUyZmZlODgyOWE1YTViYjcwY2Y5YzI)!
Wording improvements welcome! cc @dsnid3r @senlin @striebwj
=> Add info about contributing to the readme

src/wp-admin/includes/dashboard.php, src/wp-admin/index.php
Add links so users have a clear path to submit feedback re: the conversation on [slack](https://classicpress.slack.com/archives/CCSJGKKUP/p1540225189000200)
=> Added feedback links to dashboard widget

tools/i18n/makepot.php
=> cleaning makepot

src/wp-admin/install.php
I've changed the welcome text on the install page. 
Here is [issue-181](https://github.com/ClassicPress/ClassicPress/issues/181).
=> fix-181: changed the welcome text on the install page

src/wp-admin/about.php, src/wp-admin/credits.php, src/wp-admin/freedoms.php
Change wording about page as per suggestion issue #41
=> change wording about page as per suggestion issue #41

src/wp-includes/js/media/models/attachments.js, src/wp-includes/js/media/views/attachments/browser.js
=> Update more Trac ticket references

src/wp-includes/css/buttons.css
This reverts commit ac0fdee38776388a19b1e3ca640e3d4caa2849a3.
For explanation & discussion see: https://github.com/ClassicPress/ClassicPress/issues/210#issuecomment-439270387
=> Revert "Update admin buttons: solid color background (#223)"

src/wp-admin/includes/dashboard.php, src/wp-admin/maint/repair.php, src/wp-includes/update.php
Closes #232 
The testing was made by checking the content of the Dashboard page of ClassicPress.
=> Change links and wording from Slack to new support forums (#232)

src/wp-includes/script-loader.php
Easier than leaving a million comments.
=> Fixup static

src/wp-admin/about.php, src/wp-admin/css/about.css, src/wp-admin/css/dashboard.css, src/wp-admin/includes/dashboard.php
=> Harmonize the about.php styling inconsistency

src/wp-admin/about.php, src/wp-admin/includes/dashboard.php
Remove HTML text. Moved to about screen
https://github.com/ClassicPress/ClassicPress/issues/334#issue-399609888
SandBox
=> Dashboard: Move content from welcome widget to About page

src/wp-admin/includes/dashboard.php
> PHP Notice:  Only variables should be passed by reference in wp-admin/includes/dashboard.php on line 1486
=> Fix a PHP notice in the dashboard petitions widget

src/wp-admin/includes/misc.php, src/wp-admin/options-permalink.php, tests/phpunit/includes/phpunit6-compat.php, tests/phpunit/tests/htaccess-markers.php
Use regex for `.htaccess` boundary matching - needs more testing!
=> fix multiple rewrite blocks in .htaccess

src/wp-includes/update.php
Send it as intended, rather than a couple of pieces getting in there sort of accidentally with inaccurate comments.
=> Re-work update data

src/wp-includes/http.php
=> Remove pre-release version from '@ deprecated' tag

README.md
Fixed typo donation link in README.md file
=> Fixed typo donation link in README.md file

src/wp-admin/about.php
Add changelog notes in about.php
PR for https://github.com/ClassicPress/ClassicPress/issues/449 
Add links and information to explain CP changes and new features in new releases.
This is markup and has non-breaking changes. Code has been tested with Code standards and visually.
=> Add changelogs info #449

src/wp-admin/update-core.php
As per discussion in #462 this is a first attempt at implementing the discussed changes.
=> #462 - Compatibility with CP in plugin screen

src/wp-includes/general-template.php
See: https://forums.classicpress.net/t/classicpress-1-1-0-rc1-release-notes/1582/15
The new "custom login image" functionality in 1.1.0 should have a filter to allow further customization.
=> Add new 'login_image_html' filter

.travis.yml, README.md
- We moved from travis-ci.org to travis-ci.com, update the Travis badge in the readme accordingly
- Only run builds on the "develop" and "master" branches, builds on individual PRs will be run via the "Build pushed pull requests" setting as before
=> Update Travis CI branch settings

README.md
> ![2020-02-19T03-22-55Z](https://user-images.githubusercontent.com/227022/74798982-35096880-52c7-11ea-9ff2-bf0764a7530a.png)
> ![2020-02-19T03-23-21Z](https://user-images.githubusercontent.com/227022/74798986-376bc280-52c7-11ea-86a7-aa575d3f6a88.png)
=> Update the first section of the readme

src/wp-includes/user.php
Potential fix for #564, updated to fix the issue as described in the original report:
>Add a new entry to the `$users` array, which preserves the current user ID but indicates to the user that this post has an invalid author set.
Fix for an open issue. Fixes #564
Needs testing (manual testing with screenshots, and automated tests)
- Bug fix
=> Fix PHP notice and unexpected behavior when editing a post with an invalid author

README.md
The old petitions site was closed recently and moved to the forums. This PR updates the **Suggest features** (petitions) link in `README.md`. 
Closes #664 
The link pointed to the old petitions site at petitions.classicpress.net
The link points to the petitions area on the forums (https://forums.classicpress.net/c/governance/petitions/77)
=> Update petitions link in README.md

src/wp-content/themes/twentyfifteen/functions.php, src/wp-content/themes/twentyseventeen/functions.php, src/wp-content/themes/twentysixteen/functions.php, src/wp-includes/admin-bar.php, src/wp-includes/class.wp-scripts.php, src/wp-includes/class.wp-styles.php, src/wp-includes/embed.php, src/wp-includes/formatting.php, src/wp-includes/media.php, src/wp-includes/script-loader.php, src/wp-includes/theme.php, src/wp-includes/widgets/class-wp-widget-archives.php, src/wp-includes/widgets/class-wp-widget-categories.php, src/wp-includes/widgets/class-wp-widget-recent-comments.php, tests/phpunit/tests/dependencies/scripts.php, tests/phpunit/tests/dependencies/styles.php
Reverts ClassicPress/ClassicPress#524 which broke some things related to script/style enqueuing.
=> Revert "Remove JavaScript and CSS type attributes for HTML5 validity "

README.md, package.json
I've tweaked some text in the readme to better align with the website content, while adding financial contributors towards the bottom of the readme.md. This also includes updating package.json with Open Collective information.
Need to promote our donation links and showcase financial contributors.
See screenshot below.
- Updated text
=> Updated readme.md and package.json with Open Collective information

README.md
Primarily, I had to add organizations to the financial contributors section since we got one donor that's an organization. I also fixed a few minor text and URL issues I did not notice before.
=> Updating financial contributors in README.md

README.md
New sponsor added and I standardized sponsor logo image sizes, so they look uniform and we can fit them 3 per row in a grid format once we get more sponsors.
Sponsor perks.
https://github.com/viktorix/ClassicPress/tree/sponsor-tukutoi#sponsors
=> New sponsor added to README.md: Tukutoi

src/wp-includes/PHPMailer/PHPMailer.php, src/wp-includes/PHPMailer/SMTP.php
This is a maintenance release with minor changes:
* Add `text/csv` MIME type.
* Fix DKIM when sending to anonymous group via `mail()`.
Release notes:
https://github.com/PHPMailer/PHPMailer/releases/tag/v6.6.4
For a full list of changes in this update, see the PHPMailer GitHub:
https://github.com/PHPMailer/PHPMailer/compare/v6.6.3...v6.6.4
Follow-up to https://core.trac.wordpress.org/changeset/50628, https://core.trac.wordpress.org/changeset/50799, https://core.trac.wordpress.org/changeset/51169, https://core.trac.wordpress.org/changeset/51634, https://core.trac.wordpress.org/changeset/51635, https://core.trac.wordpress.org/changeset/52252, https://core.trac.wordpress.org/changeset/52749, https://core.trac.wordpress.org/changeset/52811, https://core.trac.wordpress.org/changeset/53500, …
=> WP-r53917: External Libraries: Upgrade PHPMailer to version 6.6.4.

src/readme.html
Updated readme.html to include updated requirements/recommendations and financial support information.
Outdated and missing information.
Viewed in a browser.
- readme.html changes
=> docs: Updated readme.html

src/wp-admin/includes/menu.php
=> Removes the Security Page Menu ref: #1014

.github/workflows/phpunit-tests.yml
Aims to fix PHP.net clone test for version checking by running it on a current PHP version
Fix for automated testing
PR tests will run
N/A
- Bug fix
=> Fix for PHP.net clone test

src/wp-content/themes/twentyseventeen/assets/js/global.js
Fix for deprecated jQuery in TwentySeventeen theme.
=> Fix `deprecated` jQuery warnings

src/wp-content/themes/twentyfifteen/js/functions.js
Fix for deprecated jQuery in TwentyFifteen theme.
=>  Fix deprecated jQuery warning message

src/license.txt
Cheers to 2024 as a new year!
Change `src/license.txt` to match 2024.
- Bug fix
=> Fix new year test

src/wp-admin/js/updates.js, src/wp-admin/plugin-install.php, src/wp-admin/plugins.php, src/wp-includes/script-loader.php
This addresses the issue discussed at the core meeting at https://classicpress.zulipchat.com/#narrow/stream/399215-core/topic/Core.20Meeting.202024-03-21/near/428132030
=> Close plugin modal when update plugin

.github/CONTRIBUTING.md
Add information about [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/) to the contributing guide, it seems this may be a useful addition on Windows to support `grunt` tasks and `npm` modules.
Fixes #854
Not able to test on Windows but this seems a reasonable addition to the Contributing documentation and we can revisit Windows compatibility in the future as needed if new developers join the community that use Windows.
N/A
- Documentation
=> Update Contributing guide about WSL

src/wp-admin/includes/deprecated.php
Fixes #1609 
Add Moment.js to the list of deprecated libraries for future removal.
Cleaner core code, address open Issue.
Local testing and correction to build steps and QUnit test framework after removing this library (further PR to follow).
N/A
- Future breaking change
=> Add deprecate notice for `Moment.js`

.github/ISSUE_TEMPLATE/feature_request.yml
Simply changes "implemantion" to "implementation".
=> Update feature_request.yml to correct typo

src/wp-admin/upload.php, src/wp-includes/js/media-grid.js
When selecting an item in the media grid view, the author is not always shown correctly in the modal. This PR ensures that the correct author is always displayed.
Props: @citrika
=> Fix wrong author in media grid view

src/wp-admin/credits.php
1. Fix 404 at page wp-admin/credits.php (removed link from string, because could not find a new or similar page). 
2) Updated link to community page.
=> Fix links in credits.php

src/wp-content/themes/the-classicpress-theme/functions.php, src/wp-content/themes/the-classicpress-theme/header.php, src/wp-content/themes/the-classicpress-theme/js/menu-resize.js, src/wp-content/themes/the-classicpress-theme/style.css
This is a list of small changes for the default "The ClassicPress Theme"
Changes should be small enough to be readable in the code:
If no logo is set, a hidden "Yo" string is placed where the website title should be. This is wrong. I have added the website name.
This class is not applied to any element in the theme.
Lots of small CSS changes to make sure the mobile menu is perfectly aligned. I am still not 100% happy, but it's a good start.
Tested with no plugins and the bleeding edge version of ClassicPress, on PHP 8.3.
- Bug fixes
- Accessibility fixes
=> Bytesize changes for The ClassicPress Theme

src/wp-admin/upload.php
=> Fix pagination in grid mode when Media Library is empty

src/wp-admin/upload.php
=> Account for uploaded file having no author

src/wp-content/themes/the-classicpress-theme/functions.php, src/wp-content/themes/the-classicpress-theme/style.css
=> Bump version and asset version

package-lock.json, package.json
Reverts ClassicPress/ClassicPress#1794
Wrong PR merged.
=> Revert "Renovate[bot]: Update dependency webpack to v5.98.0"

src/wp-admin/js/comment.js
See https://classicpress.zulipchat.com/#narrow/channel/399230-community/topic/general/near/502506799
=> Fix "postboxes is not defined"

src/wp-admin/css/media-grid.css, src/wp-admin/upload.php
Related issue: [FilePond's dropzone gets cut off at the bottom](https://github.com/ClassicPress/ClassicPress/issues/1751)
=> Fix FilePond styling issues

src/wp-includes/js/media-grid.js
There's a bug if the "mode" URL parameter is present.
=> Fix id extraction for deleteItem

src/wp-content/themes/the-classicpress-theme/style.css
1. Homepage: add white space between header section and post/page content (to match white space on pages with a page title).
2. Single post page: fix alignment of post navigation.
3. Mobile screen: move mobile menu button to top (as in previous theme versions).
This PR fixes multiple visible issues and I think this will benefit all users.
No breaking changes.
=> ClassicPress theme - misc CSS fixes

src/wp-includes/js/media-grid.js
This removes the uploaded files through FilePond from the dropzone automatically, and calls resetDataOrdering to update pagination status.
```javascript
pond.on( 'processfile', function( error, file ) {
setTimeout( function() {
pond.removeFile( file.id );
}, 100 );
resetDataOrdering();
} );
```
=> FilePond tweaks

src/wp-admin/includes/class-wp-media-list-table.php, src/wp-admin/includes/template.php, src/wp-admin/js/inline-edit-post.js, src/wp-admin/js/media.js
[Why the GOV.UK Design System team changed the input type for numbers](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/)
- New feature
=> Pattern-based HTML5 validation for date/time text inputs

src/wp-admin/css/list-tables.css, src/wp-admin/js/common.js
=> Fix ID column in post table on mobile

src/wp-admin/options-general.php
As reported by @Guido07111975 , there's a dead "Learn more" link for the Custom Login Image feature on the admin `Settings->General` screen. This PR inserts the correct URL.
=> Update "Learn More" URL

src/wp-includes/PHPMailer/PHPMailer.php, src/wp-includes/PHPMailer/SMTP.php
External library update, PHPMailer 6.10.0 has been releases recently. This update has some minor changes and supports SMTPUTF8.
External library update.
Unit tests are in core.
N/A
- Enhancement
=> Update PHPMailer to 6.10.0

.github/ISSUE_TEMPLATE/bug_report.yml
Removed unsupported PHP versions and added new ones.
=> Update bug_report.yml to account supported PHP version

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/coding-standards.yml, .github/workflows/javascript-tests.yml, .github/workflows/php-compatibility.yml, .github/workflows/phpunit-tests.yml
This PR does a few things in the `.github` folder:
1. Tidies up the inline documentation in the workflow files
2. Removed the styfle/cancel-workflow-action action from the JavaScript test file
3. Adds a new `Enhancement` PR change description to the pull template
General tidy of GitHub files
N/A
- Enhancement
=> Update inline documentation in `.github` folder

src/wp-admin/includes/ajax-actions.php
This follows PR #1972 in replacing outstanding instances of `$cp_needs_update` with `$cp_has_update`. Thanks to @Guido07111975 for noticing so fast!
=> Replace remaining `$cp_needs_update` with `$cp_has_update`
